{
    "openapi": "3.0.1",
    "info": {
        "title": "Properties",
        "description": "All HubSpot objects store data in default and custom properties. These endpoints provide access to read and modify object properties in HubSpot.",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "STARTER"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "Create a set of new custom multi-select properties for storing contract data on company records.",
        "x-hubspot-related-documentation": [
            {
                "name": "Properties Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/properties"
            }
        ],
        "x-hubspot-introduction": "Use the properties API to store information in fields on individual contact records. You can use this API to manage existing default and custom properties, create new custom properties, and more."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Groups"
        },
        {
            "name": "Core"
        }
    ],
    "paths": {
        "/crm/v3/properties/{objectType}/batch/archive": {
            "post": {
                "tags": ["Batch"],
                "summary": "Archive a batch of properties",
                "description": "Archive a provided list of properties. This method will return a 204 No Content response on success regardless of the initial state of the property (e.g. active, already archived, non-existent).",
                "operationId": "post-/crm/v3/properties/{objectType}/batch/archive_archive",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            }
        },
        "/crm/v3/properties/{objectType}/groups/{groupName}": {
            "get": {
                "tags": ["Groups"],
                "summary": "Read a property group",
                "description": "Read a property group identified by {groupName}.",
                "operationId": "get-/crm/v3/properties/{objectType}/groups/{groupName}_getByName",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["timeline"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.owners.read"]
                    },
                    {
                        "oauth2": ["crm.objects.owners.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.read"]
                    },
                    {
                        "oauth2_legacy": ["timeline"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    }
                ]
            },
            "delete": {
                "tags": ["Groups"],
                "summary": "Archive a property group",
                "description": "Move a property group identified by {groupName} to the recycling bin.",
                "operationId": "delete-/crm/v3/properties/{objectType}/groups/{groupName}_archive",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            },
            "patch": {
                "tags": ["Groups"],
                "summary": "Update a property group",
                "description": "Perform a partial update of a property group identified by {groupName}. Provided fields will be overwritten.",
                "operationId": "patch-/crm/v3/properties/{objectType}/groups/{groupName}_update",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            }
        },
        "/crm/v3/properties/{objectType}/{propertyName}": {
            "get": {
                "tags": ["Core"],
                "summary": "Read a property",
                "description": "Read a property identified by {propertyName}.",
                "operationId": "get-/crm/v3/properties/{objectType}/{propertyName}_getByName",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["timeline"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.owners.read"]
                    },
                    {
                        "oauth2": ["crm.objects.owners.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.read"]
                    },
                    {
                        "oauth2_legacy": ["timeline"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    }
                ]
            },
            "delete": {
                "tags": ["Core"],
                "summary": "Archive a property",
                "description": "Move a property identified by {propertyName} to the recycling bin.",
                "operationId": "delete-/crm/v3/properties/{objectType}/{propertyName}_archive",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            },
            "patch": {
                "tags": ["Core"],
                "summary": "Update a property",
                "description": "Perform a partial update of a property identified by {propertyName}. Provided fields will be overwritten.",
                "operationId": "patch-/crm/v3/properties/{objectType}/{propertyName}_update",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            }
        },
        "/crm/v3/properties/{objectType}/batch/read": {
            "post": {
                "tags": ["Batch"],
                "summary": "Read a batch of properties",
                "description": "Read a provided list of properties.",
                "operationId": "post-/crm/v3/properties/{objectType}/batch/read_read",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["timeline"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.owners.read"]
                    },
                    {
                        "oauth2": ["crm.objects.owners.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.read"]
                    },
                    {
                        "oauth2_legacy": ["timeline"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    }
                ]
            }
        },
        "/crm/v3/properties/{objectType}/batch/create": {
            "post": {
                "tags": ["Batch"],
                "summary": "Create a batch of properties",
                "description": "Create a batch of properties using the same rules as when creating an individual property.",
                "operationId": "post-/crm/v3/properties/{objectType}/batch/create_create",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            }
        },
        "/crm/v3/properties/{objectType}": {
            "get": {
                "tags": ["Core"],
                "summary": "Read all properties",
                "description": "Read all existing properties for the specified object type and HubSpot account.",
                "operationId": "get-/crm/v3/properties/{objectType}_getAll",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["timeline"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.owners.read"]
                    },
                    {
                        "oauth2": ["crm.objects.owners.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.read"]
                    },
                    {
                        "oauth2_legacy": ["timeline"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    }
                ]
            },
            "post": {
                "tags": ["Core"],
                "summary": "Create a property",
                "description": "Create and return a copy of a new property for the specified object type.",
                "operationId": "post-/crm/v3/properties/{objectType}_create",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            }
        },
        "/crm/v3/properties/{objectType}/groups": {
            "get": {
                "tags": ["Groups"],
                "summary": "Read all property groups",
                "description": "Read all existing property groups for the specified object type and HubSpot account.",
                "operationId": "get-/crm/v3/properties/{objectType}/groups_getAll",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["timeline"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.owners.read"]
                    },
                    {
                        "oauth2": ["crm.objects.owners.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.read"]
                    },
                    {
                        "oauth2_legacy": ["timeline"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    }
                ]
            },
            "post": {
                "tags": ["Groups"],
                "summary": "Create a property group",
                "description": "Create and return a copy of a new property group.",
                "operationId": "post-/crm/v3/properties/{objectType}/groups_create",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.schemas.custom.read": "View custom object definitions",
                            "crm.objects.marketing_events.read": "Read marketing events",
                            "tickets": "Read and write tickets",
                            "crm.objects.goals.read": "Read goals",
                            "crm.objects.marketing_events.write": "Write marketing events",
                            "crm.objects.custom.write": "Change custom object records",
                            "e-commerce": "e-commerce",
                            "timeline": "Create timeline events",
                            "crm.objects.feedback_submissions.read": "View feedback survey submissions",
                            "crm.objects.custom.read": "View custom object records",
                            "media_bridge.read": "Read media and media events",
                            "crm.pipelines.orders.read": "View details about your cart pipelines including pipeline stage information",
                            "crm.pipelines.orders.write": "Create, delete, or make to your order pipelines or their respective stages"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.schemas.carts.read": "Read cart property settings",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.owners.read": " ",
                            "crm.schemas.listings.read": "Read listings property settings",
                            "crm.schemas.courses.read": "Read courses property settings",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.deals.write": " ",
                            "crm.schemas.subscriptions.read": "Read subscriptions schema",
                            "crm.schemas.deals.read": " ",
                            "crm.objects.deals.read": " ",
                            "crm.schemas.invoices.read": "Read invoices schema",
                            "crm.objects.companies.write": " ",
                            "crm.schemas.commercepayments.read": "Read the COMMERCE_PAYMENT properties.",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.schemas.contacts.read": " ",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.schemas.line_items.read": "Line Items schemas",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.schemas.quotes.read": "Quotes schemas",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.schemas.companies.read": " ",
                            "crm.schemas.appointments.read": "Read appointments property settings",
                            "crm.schemas.orders.read": "Read order property settings",
                            "crm.schemas.services.read": "Read services property settings",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.orders.write": "Write orders",
                            "crm.schemas.listings.write": "Write listings property settings",
                            "crm.schemas.companies.write": " ",
                            "crm.schemas.appointments.write": "Write appointments property settings",
                            "crm.schemas.carts.write": "Write cart property settings",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.schemas.contacts.write": " ",
                            "crm.schemas.services.write": "Write services property settings",
                            "crm.schemas.courses.write": "Write courses property settings",
                            "crm.schemas.deals.write": " ",
                            "crm.objects.carts.write": "Write cart",
                            "crm.schemas.orders.write": "Write order property settings"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    },
    "x-hubspot-available-client-libraries": ["PHP", "Node", "Ruby", "Python"],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "STARTER"
    },
    "x-hubspot-documentation-banner": "NONE"
}
