{
    "openapi": "3.0.1",
    "info": {
        "title": "CRM Limits Tracking",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "Before importing a large file of contacts, you want to check how many contact records you've created compared to your account's limit.",
        "x-hubspot-related-documentation": [
            {
                "name": "Limits tracking guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/limits-tracking"
            }
        ],
        "x-hubspot-introduction": "Use the limits tracking API to view limits and usage for CRM data including records, associations, pipelines, and properties."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Limits"
        }
    ],
    "paths": {
        "/crm/v3/limits/associations/labels": {
            "get": {
                "tags": ["Limits"],
                "summary": "Read association label limits",
                "description": "Returns limits and usage for custom association labels",
                "operationId": "get-/crm/v3/limits/associations/labels",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/limits/associations/records/{fromObjectTypeId}/{toObjectTypeId}": {
            "get": {
                "tags": ["Limits"],
                "summary": "Read record association limits between two objects",
                "description": "Returns records approaching or at association limits between two objects",
                "operationId": "get-/crm/v3/limits/associations/records/{fromObjectTypeId}/{toObjectTypeId}",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/limits/associations/records/{fromObjectTypeId}/to": {
            "get": {
                "tags": ["Limits"],
                "summary": "Read record association limits from an object",
                "description": "Returns objects for which the from object has records approaching or at association limits",
                "operationId": "get-/crm/v3/limits/associations/records/{fromObjectTypeId}/to",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/limits/custom-object-types": {
            "get": {
                "tags": ["Limits"],
                "summary": "Read custom object limits",
                "description": "Returns limits and usage for custom object schemas",
                "operationId": "get-/crm/v3/limits/custom-object-types",
                "security": [
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    }
                ]
            }
        },
        "/crm/v3/limits/custom-properties": {
            "get": {
                "tags": ["Limits"],
                "summary": "Read custom property limits",
                "description": "Returns limits and usage per object for custom properties",
                "operationId": "get-/crm/v3/limits/custom-properties",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/limits/associations/records/from": {
            "get": {
                "tags": ["Limits"],
                "summary": "Read record association limits",
                "description": "Returns objects with records approaching or at association limits",
                "operationId": "get-/crm/v3/limits/associations/records/from",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/limits/records": {
            "get": {
                "tags": ["Limits"],
                "summary": "Read record limits",
                "description": "Returns limits and usage per object for records",
                "operationId": "get-/crm/v3/limits/records",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/limits/pipelines": {
            "get": {
                "tags": ["Limits"],
                "summary": "Read pipeline limits",
                "description": "Returns limits and usage per object for pipelines",
                "operationId": "get-/crm/v3/limits/pipelines",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/limits/calculated-properties": {
            "get": {
                "tags": ["Limits"],
                "summary": "Read calculation property limits",
                "description": "Returns overall limit and per object usage for calculated properties",
                "operationId": "get-/crm/v3/limits/calculated-properties",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "e-commerce": "e-commerce",
                            "crm.objects.custom.write": "Change custom object records",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.goals.read": "Read goals",
                            "tickets": "Read and write tickets",
                            "crm.objects.custom.read": "View custom object records",
                            "crm.schemas.custom.read": "View custom object definitions"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.contacts.read": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.deals.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.companies.write": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.orders.read": "Read Orders"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    }
}
