openapi: 3.0.1
info:
  x-ballerina-display:
    label: Hubspot Marketing
    iconPath: "resources/hubspot.marketing.svg"
  title: Marketing Events Extension
  description: This is a generated connector from [HubSpot](https://www.hubspot.com/) OpenAPI specification.
  
    These APIs allow you to interact with HubSpot's Marketing Events Extension. 
  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials.
   
    Create a [HubSpot account](https://www.hubspot.com/) and obtain the API Key following [this guide](https://knowledge.hubspot.com/integrations/how-do-i-get-my-hubspot-api-key?_ga=2.57958890.1140639136.1626730652-1097354510.162640933).
  version: v3
servers:
  - url: 'https://api.hubapi.com'
tags:
  - name: Settings
    description: Operations to interact with URL settings for an external application.
  - name: Basic
    description: Endpoints that allow you to create or modify the state of an individual Marketing Event in HubSpot.
  - name: Batch
    description: Endpoints that allow you to create or modify the state of multiple Marketing Events in HubSpot.
  - name: Search
    description: Endpoints that allow you to search for Marketing Events in HubSpot.
  - name: Subscriber State Changes
    description: 'Operations to mark HubSpot contacts as registered, attended or cancelled a registration to a Marketing Event.'
paths:
  /marketing/v3/marketing-events-beta/events:
    post:
      tags:
        - Basic
      summary: Create a marketing event
      description: Creates a new marketing event in HubSpot
      operationId: create/marketing/event
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.marketing_events.write
  /marketing/v3/marketing-events-beta/events/delete:
    post:
      tags:
        - Batch
      summary: Delete multiple marketing events
      description: Bulk delete a number of marketing events in HubSpot
      operationId: postevents/delete
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.marketing_events.write
  /marketing/v3/marketing-events-beta/events/search:
    get:
      tags:
        - Search
      summary: Search for marketing events
      description: Search for marketing events that have an event id that starts with the query string
      operationId: events/search
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.marketing_events.read
  /marketing/v3/marketing-events-beta/events/upsert:
    post:
      tags:
        - Batch
      summary: Create or update multiple marketing events
      description: 'Upset multiple Marketing Event. If there is an existing Marketing event with the specified id, it will be updated; otherwise a new event will be created.'
      operationId: events/create/or/upsert
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.marketing_events.write
  '/marketing/v3/marketing-events-beta/events/{externalEventId}':
    get:
      tags:
        - Basic
      summary: Get a marketing event
      description: 'Returns the details of the Marketing Event with the specified id, if one exists.'
      operationId: 'get/events/{externalEventId}'
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.marketing_events.read
    put:
      tags:
        - Basic
      summary: Create or update a marketing event
      description: 'Upsets a Marketing Event. If there is an existing Marketing event with the specified id, it will be updated; otherwise a new event will be created.'
      operationId: 'update/events/{externalEventId}'
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.marketing_events.write
    delete:
      tags:
        - Basic
      summary: Delete a marketing event
      description: 'Deletes an existing Marketing Event with the specified id, if one exists.'
      operationId: 'delete/events/{externalEventId}'
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.marketing_events.write
    patch:
      tags:
        - Basic
      summary: Update a marketing event
      description: 'Updates an existing Marketing Event with the specified id, if one exists.'
      operationId: 'update/events'
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.marketing_events.write
  '/marketing/v3/marketing-events-beta/events/{externalEventId}/cancel':
    post:
      tags:
        - Basic
      summary: Mark a marketing event as cancelled
      description: Mark a marketing event as cancelled.
      operationId: 'events/{externalEventId}/cancel'
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.marketing_events.write
  '/marketing/v3/marketing-events-beta/events/{externalEventId}/{subscriberState}/email-upsert':
    post:
      tags:
        - Subscriber State Changes
      summary: Record
      description: 'Record a subscription state between multiple HubSpot contacts and a marketing event, using contact email addresses.'
      operationId: '{externalEventId}/{subscriberState}/email-upsert'
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.marketing_events.write
  '/marketing/v3/marketing-events-beta/events/{externalEventId}/{subscriberState}/upsert':
    post:
      tags:
        - Subscriber State Changes
      summary: Record
      description: 'Record a subscription state between multiple HubSpot contacts and a marketing event, using HubSpot contact ids.'
      operationId: 'events/{externalEventId}/{subscriberState}/upsert'
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.marketing_events.write
  '/marketing/v3/marketing-events-beta/{appId}/settings':
    get:
      tags:
        - Settings
      summary: Retrieve the application settings
      description: Retrieve the current settings for the application.
      operationId: 'get/{appId}/settings'
      security:
        - hapikey: []
        - developer_hapikey: []
    post:
      tags:
        - Settings
      summary: Update the application settings
      description: Create or update the current settings for the application.
      operationId: 'post/{appId}/settings'
      security:
        - hapikey: []
        - developer_hapikey: []
components:
  securitySchemes:
    hapikey:
      type: apiKey
      x-ballerina-apikey-description: "Provide your API key as `hapikey`. Eg: `{\"hapikey\" : \"<API key>\"}`"
      name: hapikey
      in: query
    # developer_hapikey:
    #   type: apiKey
    #   name: hapikey
    #   in: query
    # oauth2:
    #   type: oauth2
    #   flows:
    #     authorizationCode:
    #       authorizationUrl: 'https://app.hubspot.com/oauth/authorize'
    #       tokenUrl: 'https://api.hubapi.com/oauth/v1/token'
    #       scopes:
    #         crm.objects.marketing_events.write: Write marketing events
    #         crm.objects.marketing_events.read: Read marketing events
