{
    "openapi": "3.0.1",
    "info": {
        "title": "Calls",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "If your team isn't using the HubSpot calling tool to make calls to prospects, you can use the calls API to log call information from another service to your HubSpot account.",
        "x-hubspot-related-documentation": [
            {
                "name": "Calls Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/engagements/calls"
            }
        ],
        "x-hubspot-introduction": "Use the call engagements API to associate calls with your CRM records. You can include key takeaways in the metadata of each call, including the call's outcome, recipient information, and a URL of the recording, if applicable."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/crm/v3/objects/calls/batch/read": {
            "post": {
                "tags": ["Batch"],
                "summary": "Retrieve a batch of calls",
                "description": "Retrieve a batch of calls by ID.",
                "operationId": "post-/crm/v3/objects/calls/batch/read_read",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/calls/{callId}": {
            "get": {
                "tags": ["Basic"],
                "summary": "Retrieve a call",
                "description": "Retrieve a call by its ID (`callId`) or by a unique property (`idProperty`). You can specify what is returned using the `properties` query parameter.",
                "operationId": "get-/crm/v3/objects/calls/{callId}_getById",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    }
                ]
            },
            "delete": {
                "tags": ["Basic"],
                "summary": "Archive a call",
                "description": "Delete a call by ID. A deleted call can be restored within 90 days of being deleted, but the recording will be permanently deleted. Learn more about [restoring activity records](https://knowledge.hubspot.com/records/restore-deleted-activity-in-a-record).",
                "operationId": "delete-/crm/v3/objects/calls/{callId}_archive",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            },
            "patch": {
                "tags": ["Basic"],
                "summary": "Update a call",
                "description": "Update a call by ID. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
                "operationId": "patch-/crm/v3/objects/calls/{callId}_update",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/calls/batch/archive": {
            "post": {
                "tags": ["Batch"],
                "summary": "Archive a batch of calls",
                "description": "Archive a batch of calls by ID. Deleted calls can be restored within 90 days of being deleted, but call recordings recording will be permanently deleted. Learn more about [restoring activity records](https://knowledge.hubspot.com/records/restore-deleted-activity-in-a-record).",
                "operationId": "post-/crm/v3/objects/calls/batch/archive_archive",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/calls/batch/create": {
            "post": {
                "tags": ["Batch"],
                "summary": "Create a batch of calls",
                "description": "Create a batch of calls. The `inputs` array can contain a `properties` object to define property values for each record, along with an `associations` array to define [associations](https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4) with other CRM records.",
                "operationId": "post-/crm/v3/objects/calls/batch/create_create",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/calls/batch/update": {
            "post": {
                "tags": ["Batch"],
                "summary": "Update a batch of calls",
                "description": "Update a batch of calls by ID.",
                "operationId": "post-/crm/v3/objects/calls/batch/update_update",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/calls": {
            "get": {
                "tags": ["Basic"],
                "summary": "Retrieve calls",
                "description": "Retrieve all calls, using query parameters to specify the information that gets returned.",
                "operationId": "get-/crm/v3/objects/calls_getPage",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    }
                ]
            },
            "post": {
                "tags": ["Basic"],
                "summary": "Create a call",
                "description": "Create a single call. Include a `properties` object to define property values for the record, along with an `associations` array to define call associations(https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4) with other CRM records.",
                "operationId": "post-/crm/v3/objects/calls_create",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/calls/batch/upsert": {
            "post": {
                "tags": ["Batch"],
                "summary": "Create or update a batch of calls by unique property",
                "description": "Create or update a batch of calls by ID (`callId`) or unique property value (`idProperty`).",
                "operationId": "post-/crm/v3/objects/calls/batch/upsert_upsert",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/calls/search": {
            "post": {
                "tags": ["Search"],
                "summary": "Search for calls",
                "description": "Search for calls by filtering on properties, searching through associations, and sorting results. Learn more about [CRM search](https://developers.hubspot.com/docs/guides/api/crm/search#make-a-search-request).",
                "operationId": "post-/crm/v3/objects/calls/search_doSearch",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": ["ten-secondly"]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.read": "View custom object records",
                            "e-commerce": "e-commerce",
                            "crm.objects.custom.write": "Change custom object records",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.goals.read": "Read goals",
                            "tickets": "Read and write tickets"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.services.read": "Read services",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.deals.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.companies.write": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.quotes.read": "Quotes"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    },
    "x-hubspot-available-client-libraries": ["PHP", "Node", "Ruby", "Python"],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}
