{
    "openapi": "3.0.1",
    "info": {
        "title": "CRM Pipelines",
        "description": "Pipelines represent distinct stages in a workflow, like closing a deal or servicing a support ticket. These endpoints provide access to read and modify pipelines in HubSpot. Pipelines support `deals` and `tickets` object types.\n\n## Pipeline ID validation\n\nWhen calling endpoints that take pipelineId as a parameter, that ID must correspond to an existing, un-archived pipeline. Otherwise the request will fail with a `404 Not Found` response.",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "STARTER"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "To streamline customer support processes, use this API to retrieve your existing ticket pipelines and add new stages based on your business needs. Support reps can then assign tickets to those pipeline stages to track progress on customer issues.",
        "x-hubspot-related-documentation": [
            {
                "name": "Pipelines Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/pipelines"
            }
        ],
        "x-hubspot-introduction": "Use the pipelines API to create and manage deal and ticket pipelines. Pipelines enable you to track the status or progress of deals and tickets, such as closing deals and opening support tickets."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Pipeline Stage Audits"
        },
        {
            "name": "Pipelines"
        },
        {
            "name": "Pipeline Audits"
        },
        {
            "name": "Pipeline Stages"
        }
    ],
    "paths": {
        "/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit": {
            "get": {
                "tags": ["Pipeline Stage Audits"],
                "summary": "Return an audit of all changes to the pipeline stage",
                "description": "Return a reverse chronological list of all mutations that have occurred on the pipeline stage identified by `{stageId}`.",
                "operationId": "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}/audit_getAudit",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["timeline"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.owners.read"]
                    },
                    {
                        "oauth2": ["crm.objects.owners.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.read"]
                    },
                    {
                        "oauth2_legacy": ["timeline"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    }
                ]
            }
        },
        "/crm/v3/pipelines/{objectType}/{pipelineId}": {
            "get": {
                "tags": ["Pipelines"],
                "summary": "Return a pipeline by ID",
                "description": "Return a single pipeline object identified by its unique `{pipelineId}`.",
                "operationId": "get-/crm/v3/pipelines/{objectType}/{pipelineId}_getById",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["timeline"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.owners.read"]
                    },
                    {
                        "oauth2": ["crm.objects.owners.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.read"]
                    },
                    {
                        "oauth2_legacy": ["timeline"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    }
                ]
            },
            "put": {
                "tags": ["Pipelines"],
                "summary": "Replace a pipeline",
                "description": "Replace all the properties of an existing pipeline with the values provided. This will overwrite any existing pipeline stages. The updated pipeline will be returned in the response.",
                "operationId": "put-/crm/v3/pipelines/{objectType}/{pipelineId}_replace",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            },
            "delete": {
                "tags": ["Pipelines"],
                "summary": "Delete a pipeline",
                "description": "Delete the pipeline identified by `{pipelineId}`.",
                "operationId": "delete-/crm/v3/pipelines/{objectType}/{pipelineId}_archive",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            },
            "patch": {
                "tags": ["Pipelines"],
                "summary": "Update a pipeline",
                "description": "Perform a partial update of the pipeline identified by `{pipelineId}`. The updated pipeline will be returned in the response.",
                "operationId": "patch-/crm/v3/pipelines/{objectType}/{pipelineId}_update",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            }
        },
        "/crm/v3/pipelines/{objectType}/{pipelineId}/audit": {
            "get": {
                "tags": ["Pipeline Audits"],
                "summary": "Return an audit of all changes to the pipeline",
                "description": "Return a reverse chronological list of all mutations that have occurred on the pipeline identified by `{pipelineId}`.",
                "operationId": "get-/crm/v3/pipelines/{objectType}/{pipelineId}/audit_getAudit",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["timeline"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.owners.read"]
                    },
                    {
                        "oauth2": ["crm.objects.owners.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.read"]
                    },
                    {
                        "oauth2_legacy": ["timeline"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    }
                ]
            }
        },
        "/crm/v3/pipelines/{objectType}/{pipelineId}/stages": {
            "get": {
                "tags": ["Pipeline Stages"],
                "summary": "Return all stages of a pipeline",
                "description": "Return all the stages associated with the pipeline identified by `{pipelineId}`.",
                "operationId": "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_getAll",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["timeline"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.owners.read"]
                    },
                    {
                        "oauth2": ["crm.objects.owners.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.read"]
                    },
                    {
                        "oauth2_legacy": ["timeline"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    }
                ]
            },
            "post": {
                "tags": ["Pipeline Stages"],
                "summary": "Create a pipeline stage",
                "description": "Create a new stage associated with the pipeline identified by `{pipelineId}`. The entire stage object, including its unique ID, will be returned in the response.",
                "operationId": "post-/crm/v3/pipelines/{objectType}/{pipelineId}/stages_create",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            }
        },
        "/crm/v3/pipelines/{objectType}": {
            "get": {
                "tags": ["Pipelines"],
                "summary": "Retrieve all pipelines",
                "description": "Return all pipelines for the object type specified by `{objectType}`.",
                "operationId": "get-/crm/v3/pipelines/{objectType}_getAll",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["timeline"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.owners.read"]
                    },
                    {
                        "oauth2": ["crm.objects.owners.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.read"]
                    },
                    {
                        "oauth2_legacy": ["timeline"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    }
                ]
            },
            "post": {
                "tags": ["Pipelines"],
                "summary": "Create a pipeline",
                "description": "Create a new pipeline with the provided property values. The entire pipeline object, including its unique ID, will be returned in the response.",
                "operationId": "post-/crm/v3/pipelines/{objectType}_create",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            }
        },
        "/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}": {
            "get": {
                "tags": ["Pipeline Stages"],
                "summary": "Return a pipeline stage by ID",
                "description": "Return the stage identified by `{stageId}` associated with the pipeline identified by `{pipelineId}`.",
                "operationId": "get-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_getById",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["timeline"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.feedback_submissions.read"
                        ]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.commercepayments.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.owners.read"]
                    },
                    {
                        "oauth2": ["crm.objects.owners.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.quotes.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.marketing_events.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "crm.objects.marketing_events.write"
                        ]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.read"]
                    },
                    {
                        "oauth2_legacy": ["timeline"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.read"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.read"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.schemas.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    }
                ]
            },
            "put": {
                "tags": ["Pipeline Stages"],
                "summary": "Replace a pipeline stage",
                "description": "Replace all the properties of an existing pipeline stage with the values provided. The updated stage will be returned in the response.",
                "operationId": "put-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_replace",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            },
            "delete": {
                "tags": ["Pipeline Stages"],
                "summary": "Delete a pipeline stage",
                "description": "Delete the pipeline stage identified by `{stageId}` associated with the pipeline identified by `{pipelineId}`.",
                "operationId": "delete-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_archive",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            },
            "patch": {
                "tags": ["Pipeline Stages"],
                "summary": "Update a pipeline stage",
                "description": "Perform a partial update of the pipeline stage identified by `{stageId}` associated with the pipeline identified by `{pipelineId}`. Any properties not included in this update will keep their existing values. The updated stage will be returned in the response.",
                "operationId": "patch-/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}_update",
                "security": [
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.contacts.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "private_apps": ["crm.schemas.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.courses.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.courses.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.carts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    },
                    {
                        "private_apps_legacy": ["crm.pipelines.orders.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "oauth2": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.deals.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "oauth2": ["crm.schemas.companies.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.schemas.companies.write"]
                    },
                    {
                        "oauth2": ["crm.schemas.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.schemas.deals.write"]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.schemas.custom.read": "View custom object definitions",
                            "crm.objects.marketing_events.read": "Read marketing events",
                            "tickets": "Read and write tickets",
                            "crm.objects.goals.read": "Read goals",
                            "crm.objects.marketing_events.write": "Write marketing events",
                            "crm.objects.custom.write": "Change custom object records",
                            "e-commerce": "e-commerce",
                            "timeline": "Create timeline events",
                            "crm.objects.feedback_submissions.read": "View feedback survey submissions",
                            "crm.objects.custom.read": "View custom object records",
                            "media_bridge.read": "Read media and media events",
                            "crm.pipelines.orders.read": "View details about your cart pipelines including pipeline stage information",
                            "crm.pipelines.orders.write": "Create, delete, or make to your order pipelines or their respective stages"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.schemas.carts.read": "Read cart property settings",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.owners.read": " ",
                            "crm.schemas.listings.read": "Read listings property settings",
                            "crm.schemas.courses.read": "Read courses property settings",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.deals.write": " ",
                            "crm.schemas.subscriptions.read": "Read subscriptions schema",
                            "crm.schemas.deals.read": " ",
                            "crm.objects.deals.read": " ",
                            "crm.schemas.invoices.read": "Read invoices schema",
                            "crm.objects.companies.write": " ",
                            "crm.schemas.commercepayments.read": "Read the COMMERCE_PAYMENT properties.",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.schemas.contacts.read": " ",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.schemas.line_items.read": "Line Items schemas",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.schemas.quotes.read": "Quotes schemas",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.schemas.companies.read": " ",
                            "crm.schemas.appointments.read": "Read appointments property settings",
                            "crm.schemas.orders.read": "Read order property settings",
                            "crm.schemas.services.read": "Read services property settings",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.orders.write": "Write orders",
                            "crm.schemas.listings.write": "Write listings property settings",
                            "crm.schemas.companies.write": " ",
                            "crm.schemas.appointments.write": "Write appointments property settings",
                            "crm.schemas.carts.write": "Write cart property settings",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.schemas.contacts.write": " ",
                            "crm.schemas.services.write": "Write services property settings",
                            "crm.schemas.courses.write": "Write courses property settings",
                            "crm.schemas.deals.write": " ",
                            "crm.objects.carts.write": "Write cart",
                            "crm.schemas.orders.write": "Write order property settings"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    },
    "x-hubspot-available-client-libraries": ["PHP", "Node", "Ruby", "Python"],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "STARTER"
    },
    "x-hubspot-documentation-banner": "NONE"
}
