{
    "openapi": "3.0.1",
    "info": {
        "title": "Domains",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "PROFESSIONAL",
            "cms": "STARTER"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "Retrieve all currently connected domains to see which sites are live in a given account.",
        "x-hubspot-related-documentation": [
            {
                "name": "Domains Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/cms/domains"
            }
        ],
        "x-hubspot-introduction": "Use the domain management API to return information about the domains connected to a HubSpot account. You can return data for all currently connected domains, or for a single domain by ID."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Domains"
        }
    ],
    "paths": {
        "/cms/v3/domains/": {
            "get": {
                "tags": ["Domains"],
                "summary": "Get current domains",
                "description": "Returns all existing domains that have been created. Results can be limited and filtered by creation or updated date.",
                "operationId": "get-/cms/v3/domains/_getPage",
                "security": [
                    {
                        "private_apps_legacy": ["content"]
                    },
                    {
                        "oauth2": ["cms.domains.read"]
                    },
                    {
                        "private_apps": ["cms.domains.read"]
                    },
                    {
                        "private_apps": ["cms.domains.write"]
                    },
                    {
                        "oauth2": ["cms.domains.write"]
                    },
                    {
                        "oauth2_legacy": ["cms.knowledge_base.settings.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "cms.knowledge_base.settings.write"
                        ]
                    },
                    {
                        "oauth2_legacy": ["cms.knowledge_base.settings.write"]
                    },
                    {
                        "oauth2_legacy": ["content"]
                    },
                    {
                        "private_apps_legacy": [
                            "cms.knowledge_base.settings.read"
                        ]
                    }
                ]
            }
        },
        "/cms/v3/domains/{domainId}": {
            "get": {
                "tags": ["Domains"],
                "summary": "Get a single domain",
                "description": "Returns a single domains with the id specified.",
                "operationId": "get-/cms/v3/domains/{domainId}_getById",
                "security": [
                    {
                        "private_apps_legacy": ["content"]
                    },
                    {
                        "oauth2": ["cms.domains.read"]
                    },
                    {
                        "private_apps": ["cms.domains.read"]
                    },
                    {
                        "private_apps": ["cms.domains.write"]
                    },
                    {
                        "oauth2": ["cms.domains.write"]
                    },
                    {
                        "oauth2_legacy": ["cms.knowledge_base.settings.read"]
                    },
                    {
                        "private_apps_legacy": [
                            "cms.knowledge_base.settings.write"
                        ]
                    },
                    {
                        "oauth2_legacy": ["cms.knowledge_base.settings.write"]
                    },
                    {
                        "oauth2_legacy": ["content"]
                    },
                    {
                        "private_apps_legacy": [
                            "cms.knowledge_base.settings.read"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "cms.knowledge_base.settings.read": "View knowledge base settings",
                            "cms.knowledge_base.settings.write": "Update knowledge base settings",
                            "content": "Read from and write to my Content"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "cms.domains.write": "Create or update domains.",
                            "cms.domains.read": "Read domains."
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    },
    "x-hubspot-available-client-libraries": ["PHP", "Node", "Ruby", "Python"],
    "x-hubspot-product-tier-requirements": {
        "marketing": "PROFESSIONAL",
        "cms": "STARTER"
    },
    "x-hubspot-documentation-banner": "NONE"
}
