// Copyright (c) 2021 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
//
// WSO2 Inc. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

# The groupitem resource.
public type GroupItemResource record {
    # The channel, video, playlist, or asset ID that YouTube uses to uniquely identify the item that is being added to the group.
    string id?;
    # Identifies the type of resource being added to the group. Valid values for this property are: * `youtube#channel` * `youtube#playlist` * `youtube#video` * `youtubePartner#asset`
    string kind?;
};

# Request Error information. The presence of an error field signals that the operation has failed.
public type Errors record {
    # Global error code. Deprecated and ignored. Set custom error codes in ErrorProto.domain and ErrorProto.code instead.
    string code?;
    # Specific error description and codes
    ErrorProto[] _error?;
    # Request identifier generated by the service, which can be used to identify the error in the logs
    string requestId?;
};

# A group.
public type Group record {
    # A group's content details.
    GroupContentDetails contentDetails?;
    # Request Error information. The presence of an error field signals that the operation has failed.
    Errors errors?;
    # The Etag of this resource.
    string etag?;
    # The ID that YouTube uses to uniquely identify the group.
    string id?;
    # Identifies the API resource's type. The value will be `youtube#group`.
    string kind?;
    # A group snippet.
    GroupSnippet snippet?;
};

# Describes one specific error.
public type ErrorProto record {
    # Error arguments, to be used when building user-friendly error messages given the error domain and code. Different error codes require different arguments.
    string[] argument?;
    # Error code in the error domain. This should correspond to a value of the enum type whose name is in domain. See the core error domain in error_domain.proto.
    string code?;
    # Debugging information, which should not be shared externally.
    string debugInfo?;
    # Error domain. RoSy services can define their own domain and error codes. This should normally be the name of an enum type, such as: gdata.CoreErrorDomain
    string domain?;
    # A short explanation for the error, which can be shared outside Google. Please set domain, code and arguments whenever possible instead of this error message so that external APIs can build safe error messages themselves. External messages built in a RoSy interface will most likely refer to information and concepts that are not available externally and should not be exposed. It is safer if external APIs can understand the errors and decide what the error message should look like.
    string externalErrorMessage?;
    # Location of the error, as specified by the location type. If location_type is PATH, this should be a path to a field that's relative to the request, using FieldPath notation (net/proto2/util/public/field_path.h). Examples: authenticated_user.gaia_id resource.address[2].country
    string location?;
    # Location type.
    string locationType?;
};

# Response message for GroupsService.ListGroups.
public type ListGroupsResponse record {
    # Request Error information. The presence of an error field signals that the operation has failed.
    Errors errors?;
    # The Etag of this resource.
    string etag?;
    # A list of groups that match the API request parameters. Each item in the list represents a `group` resource.
    Group[] items?;
    # Identifies the API resource's type. The value will be `youtube#groupListResponse`.
    string kind?;
    # The token that can be used as the value of the `pageToken` parameter to retrieve the next page in the result set.
    string nextPageToken?;
};

# Response message for TargetedQueriesService.Query.
public type QueryResponse record {
    # This value specifies information about the data returned in the `rows` fields. Each item in the `columnHeaders` list identifies a field returned in the `rows` value, which contains a list of comma-delimited data. The `columnHeaders` list will begin with the dimensions specified in the API request, which will be followed by the metrics specified in the API request. The order of both dimensions and metrics will match the ordering in the API request. For example, if the API request contains the parameters `dimensions=ageGroup,gender&metrics=viewerPercentage`, the API response will return columns in this order: `ageGroup`, `gender`, `viewerPercentage`.
    ResultTableColumnHeader[] columnHeaders?;
    # Request Error information. The presence of an error field signals that the operation has failed.
    Errors errors?;
    # This value specifies the type of data included in the API response. For the query method, the kind property value will be `youtubeAnalytics#resultTable`.
    string kind?;
    # The list contains all rows of the result table. Each item in the list is an array that contains comma-delimited data corresponding to a single row of data. The order of the comma-delimited data fields will match the order of the columns listed in the `columnHeaders` field. If no data is available for the given query, the `rows` element will be omitted from the response. The response for a query with the `day` dimension will not contain rows for the most recent days.
    anydata[][] rows?;
};

# The description of a column of the result table.
public type ResultTableColumnHeader record {
    # The type of the column (`DIMENSION` or `METRIC`).
    string columnType?;
    # The type of the data in the column (`STRING`, `INTEGER`, `FLOAT`, etc.).
    string dataType?;
    # The name of the dimension or metric.
    string name?;
};

# A group item.
public type GroupItem record {
    # Request Error information. The presence of an error field signals that the operation has failed.
    Errors errors?;
    # The Etag of this resource.
    string etag?;
    # The ID that YouTube uses to uniquely identify the group that contains the item.
    string groupId?;
    # The ID that YouTube uses to uniquely identify the `channel`, `video`, `playlist`, or `asset` resource that is included in the group. Note that this ID refers specifically to the inclusion of that resource in a particular group and is different than the channel ID, video ID, playlist ID, or asset ID that uniquely identifies the resource itself. The `resource.id` property's value specifies the unique channel, video, playlist, or asset ID.
    string id?;
    # Identifies the API resource's type. The value will be `youtube#groupItem`.
    string kind?;
    # The groupitem resource.
    GroupItemResource 'resource?;
};

# A group snippet.
public type GroupSnippet record {
    # The date and time that the group was created. The value is specified in ISO 8601 (YYYY-MM-DDThh:mm:ss.sZ) format.
    string publishedAt?;
    # The group name. The value must be a non-empty string.
    string title?;
};

# A group's content details.
public type GroupContentDetails record {
    # The number of items in the group.
    string itemCount?;
    # The type of resources that the group contains. Valid values for this property are: * `youtube#channel` * `youtube#playlist` * `youtube#video` * `youtubePartner#asset`
    string itemType?;
};

# Response message for GroupsService.ListGroupItems.
public type ListGroupItemsResponse record {
    # Request Error information. The presence of an error field signals that the operation has failed.
    Errors errors?;
    # The Etag of this resource.
    string etag?;
    # A list of groups that match the API request parameters. Each item in the list represents a `groupItem` resource.
    GroupItem[] items?;
    # Identifies the API resource's type. The value will be `youtube#groupItemListResponse`.
    string kind?;
};
