{
    "openapi": "3.0.1",
    "info": {
        "title": "Schemas",
        "description": "The CRM uses schemas to define how custom objects should store and represent information in the HubSpot CRM. Schemas define details about an object's type, properties, and associations. The schema can be uniquely identified by its **object type ID**.",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "ENTERPRISE",
            "sales": "ENTERPRISE",
            "service": "ENTERPRISE",
            "cms": "ENTERPRISE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "Create a new object for storing information about cars at a car dealership. Your object definition could include properties to store information as well as the filters available on the custom object index page.",
        "x-hubspot-related-documentation": [
            {
                "name": "Custom Object Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/objects/custom-objects"
            }
        ],
        "x-hubspot-introduction": "Use the custom objects schema API to define new types of CRM records in your account. After setting up an object schema, you'll then be able to create records for that custom object both in HubSpot and using the objects API."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Core"
        }
    ],
    "paths": {
        "/crm-object-schemas/v3/schemas": {
            "get": {
                "tags": ["Core"],
                "summary": "Get all schemas",
                "description": "Returns all object schemas that have been defined for your account.",
                "operationId": "get-/crm-object-schemas/v3/schemas_getAll",
                "security": [
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    }
                ]
            },
            "post": {
                "tags": ["Core"],
                "summary": "Create a new schema",
                "description": "Define a new object schema, along with custom properties and associations. The entire object schema, including its object type ID, properties, and associations will be returned in the response.",
                "operationId": "post-/crm-object-schemas/v3/schemas_create",
                "security": [
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    }
                ]
            }
        },
        "/crm-object-schemas/v3/schemas/{objectType}": {
            "get": {
                "tags": ["Core"],
                "summary": "Get an existing schema",
                "description": "Returns an existing object schema.",
                "operationId": "get-/crm-object-schemas/v3/schemas/{objectType}_getById",
                "security": [
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.schemas.custom.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.schemas.custom.read"]
                    }
                ]
            },
            "delete": {
                "tags": ["Core"],
                "summary": "Delete a schema",
                "description": "Deletes a schema. Any existing records of this schema must be deleted **first**. Otherwise this call will fail.",
                "operationId": "delete-/crm-object-schemas/v3/schemas/{objectType}_archive",
                "security": [
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    }
                ]
            },
            "patch": {
                "tags": ["Core"],
                "summary": "Update a schema",
                "description": "Update the details for an existing object schema.",
                "operationId": "patch-/crm-object-schemas/v3/schemas/{objectType}_update",
                "security": [
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    }
                ]
            }
        },
        "/crm-object-schemas/v3/schemas/{objectType}/associations": {
            "post": {
                "tags": ["Core"],
                "summary": "Create an association",
                "description": "Defines a new association between the primary schema's object type and other object types.",
                "operationId": "post-/crm-object-schemas/v3/schemas/{objectType}/associations_createAssociation",
                "security": [
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    }
                ]
            }
        },
        "/crm-object-schemas/v3/schemas/{objectType}/associations/{associationIdentifier}": {
            "delete": {
                "tags": ["Core"],
                "summary": "Remove an association",
                "description": "Removes an existing association from a schema.",
                "operationId": "delete-/crm-object-schemas/v3/schemas/{objectType}/associations/{associationIdentifier}_archiveAssociation",
                "security": [
                    {
                        "private_apps_legacy": ["crm.schemas.custom.write"]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.read": "View custom object records",
                            "crm.schemas.custom.read": "View custom object definitions"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            }
        }
    },
    "x-hubspot-available-client-libraries": ["PHP", "Node", "Ruby", "Python"],
    "x-hubspot-product-tier-requirements": {
        "marketing": "ENTERPRISE",
        "sales": "ENTERPRISE",
        "service": "ENTERPRISE",
        "cms": "ENTERPRISE"
    },
    "x-hubspot-documentation-banner": "NONE"
}
