{
    "openapi": "3.0.1",
    "info": {
        "title": "Subscriptions",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "Fetch the currently active subscriptions in a given account.",
        "x-hubspot-related-documentation": [
            {
                "name": "Subscriptions Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/commerce/subscriptions"
            }
        ],
        "x-hubspot-introduction": "Use the subscriptions API to fetch information about an account's subscriptions. This is a read-only API, so it cannot be used for creating new or managing existing subscriptions. Note that the account must be set up to collect payments through either HubSpot payments or Stripe payment processing."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/crm/v3/objects/subscriptions/{subscriptionId}": {
            "get": {
                "tags": ["Basic"],
                "summary": "Retrieve a subscription",
                "description": "Retrieve a subscription by its ID (`subscriptionId`) or by a unique property (`idProperty`). You can specify what is returned using the `properties` query parameter.",
                "operationId": "get-/crm/v3/objects/subscriptions/{subscriptionId}",
                "security": [
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/subscriptions": {
            "get": {
                "tags": ["Basic"],
                "summary": "Retrieve subscriptions",
                "description": "Retrieve all subscriptions, using query parameters to specify the information that gets returned.",
                "operationId": "get-/crm/v3/objects/subscriptions",
                "security": [
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/subscriptions/search": {
            "post": {
                "tags": ["Search"],
                "summary": "Search for subscriptions",
                "description": "Search for subscriptions by filtering on properties, searching through associations, and sorting results. Learn more about [CRM search](https://developers.hubspot.com/docs/guides/api/crm/search#make-a-search-request).",
                "operationId": "post-/crm/v3/objects/subscriptions/search",
                "security": [
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": ["ten-secondly"]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.write": "Change custom object records",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.goals.read": "Read goals",
                            "tickets": "Read and write tickets",
                            "crm.objects.custom.read": "View custom object records",
                            "e-commerce": "e-commerce"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.companies.write": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.deals.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    }
}
