{
    "openapi": "3.0.1",
    "info": {
        "title": "Objects",
        "description": "CRM objects such as companies, contacts, deals, line items, products, tickets, and quotes are standard objects in HubSpot’s CRM. These core building blocks support custom properties, store critical information, and play a central role in the HubSpot application.\n\n## Supported Object Types\n\nThis API provides access to collections of CRM objects, which return a map of property names to values. Each object type has its own set of default properties, which can be found by[...]",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "After creating a Cars custom object, you can create a record for each car, then associate it with the contact who bought it.",
        "x-hubspot-related-documentation": [
            {
                "name": "Objects Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/using-object-apis"
            }
        ],
        "x-hubspot-introduction": "Use the objects API to create and manage records for an object. The endpoints can be used for objects included in all accounts, such as contacts and companies, as well as for custom objects in Enterprise accounts."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/crm/v3/objects/{objectType}/batch/read": {
            "post": {
                "tags": ["Batch"],
                "summary": "Read a batch of objects by internal ID, or unique property values",
                "operationId": "post-/crm/v3/objects/{objectType}/batch/read_read",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/{objectType}/{objectId}": {
            "get": {
                "tags": ["Basic"],
                "summary": "Read",
                "description": "Read an Object identified by `{objectId}`. `{objectId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/{objectType}/{objectId}_getById",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            },
            "delete": {
                "tags": ["Basic"],
                "summary": "Archive",
                "description": "Move an Object identified by `{objectId}` to the recycling bin.",
                "operationId": "delete-/crm/v3/objects/{objectType}/{objectId}_archive",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            },
            "patch": {
                "tags": ["Basic"],
                "summary": "Update",
                "description": "Perform a partial update of an Object identified by `{objectId}`or optionally a unique property value as specified by the `idProperty` query param. `{objectId}` refers to the internal object ID by default, and the `idProperty` query param refers to a property whose values are unique for the object. Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string[...]",
                "operationId": "patch-/crm/v3/objects/{objectType}/{objectId}_update",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/{objectType}/batch/archive": {
            "post": {
                "tags": ["Batch"],
                "summary": "Archive a batch of objects by ID",
                "operationId": "post-/crm/v3/objects/{objectType}/batch/archive_archive",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/{objectType}/batch/create": {
            "post": {
                "tags": ["Batch"],
                "summary": "Create a batch of objects",
                "operationId": "post-/crm/v3/objects/{objectType}/batch/create_create",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/{objectType}/batch/update": {
            "post": {
                "tags": ["Batch"],
                "summary": "Update a batch of objects by internal ID, or unique property values",
                "operationId": "post-/crm/v3/objects/{objectType}/batch/update_update",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/{objectType}": {
            "get": {
                "tags": ["Basic"],
                "summary": "List",
                "description": "Read a page of objects. Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/{objectType}_getPage",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            },
            "post": {
                "tags": ["Basic"],
                "summary": "Create",
                "description": "Create a CRM object with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard objects is provided.",
                "operationId": "post-/crm/v3/objects/{objectType}_create",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/{objectType}/batch/upsert": {
            "post": {
                "tags": ["Batch"],
                "summary": "Create or update a batch of objects by unique property values",
                "description": "Create or update records identified by a unique property value as specified by the `idProperty` query param. `idProperty` query param refers to a property whose values are unique for the object.",
                "operationId": "post-/crm/v3/objects/{objectType}/batch/upsert_upsert",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/{objectType}/search": {
            "post": {
                "tags": ["Search"],
                "operationId": "post-/crm/v3/objects/{objectType}/search_doSearch",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": ["ten-secondly"]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.read": "View custom object records",
                            "tickets": "Read and write tickets",
                            "crm.objects.goals.read": "Read goals",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.custom.write": "Change custom object records",
                            "e-commerce": "e-commerce"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.services.read": "Read services",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.companies.write": " ",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.deals.write": " ",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.deals.read": " ",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.companies.read": " ",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.orders.read": "Read Orders"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    },
    "x-hubspot-available-client-libraries": ["PHP", "Node", "Ruby", "Python"],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}
