{
    "openapi": "3.0.1",
    "info": {
        "title": "Goal Targets",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "Use goals data to create reports for your sales or service team to analyze how your reps are performing.",
        "x-hubspot-related-documentation": [
            {
                "name": "Goals Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/objects/goals"
            }
        ],
        "x-hubspot-introduction": "Goals in HubSpot are user-specific quotas for their sales and services teams based on templates provided by HubSpot. The goals API allows you to retrieve goals data in your HubSpot account. "
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/crm/v3/objects/goal_targets/batch/read": {
            "post": {
                "tags": ["Batch"],
                "summary": "Read a batch of goal targets by internal ID, or unique property values",
                "operationId": "post-/crm/v3/objects/goal_targets/batch/read_read",
                "security": [
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/goal_targets/{goalTargetId}": {
            "get": {
                "tags": ["Basic"],
                "summary": "Read",
                "description": "Read an Object identified by `{goalTargetId}`. `{goalTargetId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/goal_targets/{goalTargetId}_getById",
                "security": [
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    }
                ]
            },
            "delete": {
                "tags": ["Basic"],
                "summary": "Archive",
                "description": "Move an Object identified by `{goalTargetId}` to the recycling bin.",
                "operationId": "delete-/crm/v3/objects/goal_targets/{goalTargetId}",
                "security": [
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    }
                ]
            },
            "patch": {
                "tags": ["Basic"],
                "summary": "Update",
                "description": "Perform a partial update of an Object identified by `{goalTargetId}`. `{goalTargetId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param. Provided property values will be overwritten. Read-only and non-existent properties will be ignored. Properties values can be cleared by passing an empty string.",
                "operationId": "patch-/crm/v3/objects/goal_targets/{goalTargetId}",
                "security": [
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/goal_targets/batch/archive": {
            "post": {
                "tags": ["Batch"],
                "summary": "Archive a batch of goal targets by ID",
                "operationId": "post-/crm/v3/objects/goal_targets/batch/archive",
                "security": [
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/goal_targets/batch/create": {
            "post": {
                "tags": ["Batch"],
                "summary": "Create a batch of goal targets",
                "operationId": "post-/crm/v3/objects/goal_targets/batch/create",
                "security": [
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/goal_targets/batch/update": {
            "post": {
                "tags": ["Batch"],
                "summary": "Update a batch of goal targets",
                "operationId": "post-/crm/v3/objects/goal_targets/batch/update",
                "security": [
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/goal_targets": {
            "get": {
                "tags": ["Basic"],
                "summary": "List",
                "description": "Read a page of goal targets. Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/goal_targets_getPage",
                "security": [
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    }
                ]
            },
            "post": {
                "tags": ["Basic"],
                "summary": "Create",
                "description": "Create a goal target with the given properties and return a copy of the object, including the ID. Documentation and examples for creating standard goal targets is provided.",
                "operationId": "post-/crm/v3/objects/goal_targets",
                "security": [
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/goal_targets/batch/upsert": {
            "post": {
                "tags": ["Batch"],
                "summary": "Create or update a batch of goal targets by unique property values",
                "operationId": "post-/crm/v3/objects/goal_targets/batch/upsert",
                "security": [
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/goal_targets/search": {
            "post": {
                "tags": ["Search"],
                "operationId": "post-/crm/v3/objects/goal_targets/search_doSearch",
                "security": [
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": ["ten-secondly"]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.read": "View custom object records",
                            "tickets": "Read and write tickets",
                            "crm.objects.goals.read": "Read goals",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.custom.write": "Change custom object records",
                            "e-commerce": "e-commerce"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.services.read": "Read services",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.companies.write": " ",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.deals.write": " ",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.deals.read": " ",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.companies.read": " ",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.orders.read": "Read Orders"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    },
    "x-hubspot-available-client-libraries": ["PHP", "Node", "Ruby", "Python"],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}
