// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2025, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/constraint;
import ballerina/http;

# Provides Auth configurations needed when communicating with a remote HTTP endpoint.
public type ConnectionConfig record {|
    # Provides Auth configurations needed when communicating with a remote HTTP endpoint.
    http:BearerTokenConfig|ApiKeysConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional,
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

public type ApiKeysConfig record {|
    string api\-key;
    string authorization;
|};

# Represents the Queries record for the operation: createChatCompletion
public type CreateChatCompletionQueries record {
    # The explicit Azure AI Foundry Models API version to use for this request.
    # `v1` if not otherwise specified.
    AzureAIFoundryModelsApiVersion api\-version?;
};

public type AzureAIFoundryModelsApiVersion "v1"|"preview";

public type chat_completions_body record {
    # Set of 16 key-value pairs that can be attached to an object. This can be
    # useful for storing additional information about the object in a structured
    # format, and querying for objects via API or the dashboard.
    # Keys are strings with a maximum length of 64 characters. Values are strings
    # with a maximum length of 512 characters.
    OpenAI\.Metadata metadata?;
    int? top_logprobs?;
    decimal? temperature = 1;
    decimal? top_p = 1;
    # A unique identifier representing your end-user, which can help to
    # monitor and detect abuse.
    #
    # # Deprecated
    @deprecated
    string user?;
    # A stable identifier used to help detect users of your application that may be violating OpenAI's usage policies.
    #   The IDs should be a string that uniquely identifies each user. We recommend hashing their username or email address, in order to avoid sending us any identifying information. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).
    string safety_identifier?;
    # Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces the `user` field. [Learn more](https://platform.openai.com/docs/guides/prompt-caching).
    string prompt_cache_key?;
    "in-memory"|"24h"? prompt_cache_retention?;
    # A list of messages comprising the conversation so far. Depending on the
    # model you use, different message types (modalities) are supported,
    # like text, images, and audio.
    @constraint:Array {minLength: 1}
    OpenAI\.ChatCompletionRequestMessage[] messages;
    # Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI
    #   offers a wide range of models with different capabilities, performance
    #   characteristics, and price points. Refer to the [model guide](https://platform.openai.com/docs/models)
    #   to browse and compare available models.
    string model;
    # Output types that you would like the model to generate.
    # Most models are capable of generating text, which is the default:
    # `["text"]`
    # The `gpt-4o-audio-preview` model can also be used to
    # [generate audio](https://platform.openai.com/docs/guides/audio). To request that this model generate
    # both text and audio responses, you can use:
    # `["text", "audio"]`
    OpenAI\.ResponseModalities? modalities?;
    # Constrains the verbosity of the model's response. Lower values will result in
    # more concise responses, while higher values will result in more verbose responses.
    # Currently supported values are `low`, `medium`, and `high`.
    OpenAI\.Verbosity? verbosity?;
    # Constrains effort on reasoning for
    # [reasoning models](https://platform.openai.com/docs/guides/reasoning).
    # Currently supported values are `none`, `minimal`, `low`, `medium`, `high`, and `xhigh`. Reducing
    # reasoning effort can result in faster responses and fewer tokens used
    # on reasoning in a response.
    # - `gpt-5.1` defaults to `none`, which does not perform reasoning. The supported reasoning values for `gpt-5.1` are `none`, `low`, `medium`, and `high`. Tool calls are supported for all reasoning values in gpt-5.1.
    # - All models before `gpt-5.1` default to `medium` reasoning effort, and do not support `none`.
    # - The `gpt-5-pro` model defaults to (and only supports) `high` reasoning effort.
    # - `xhigh` is supported for all models after `gpt-5.1-codex-max`.
    OpenAI\.ReasoningEffort? reasoning_effort?;
    # An upper bound for the number of tokens that can be generated for a
    # completion, including visible output tokens and reasoning tokens.
    int? max_completion_tokens?;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on
    #   their existing frequency in the text so far, decreasing the model's
    #   likelihood to repeat the same line verbatim.
    decimal? frequency_penalty?;
    # Number between -2.0 and 2.0. Positive values penalize new tokens based on
    #   whether they appear in the text so far, increasing the model's likelihood
    #   to talk about new topics.
    decimal? presence_penalty?;
    # An object specifying the format that the model must output.
    #
    # Setting to `{ "type": "json_schema", "json_schema": {...} }` enables
    # Structured Outputs which ensures the model will match your supplied JSON
    # schema.
    #
    # Setting to `{ "type": "json_object" }` enables JSON mode, which ensures
    # the message the model generates is valid JSON.
    #
    # **Important:** when using JSON mode, you **must** also instruct the model
    # to produce JSON yourself via a system or user message. Without this, the
    # model may generate an unending stream of whitespace until the generation
    # reaches the token limit, resulting in a long-running and seemingly "stuck"
    # request. Also note that the message content may be partially cut off if
    # `finish_reason="length"`, which indicates the generation exceeded
    # `max_tokens` or the conversation exceeded the max context length.
    OpenAI\.CreateChatCompletionRequestResponseFormat response_format?;
    OpenAI\.CreateChatCompletionRequestAudio audio?;
    # Whether or not to store the output of this chat completion request for
    # use in model distillation or evals products.
    boolean? store?;
    # If set to true, the model response data will be streamed to the client
    # as it is generated using server-sent events.
    boolean? 'stream?;
    # Not supported with latest reasoning models `o3` and `o4-mini`.
    # Up to 4 sequences where the API will stop generating further tokens. The
    # returned text will not contain the stop sequence.
    OpenAI\.StopConfiguration? stop?;
    # Modify the likelihood of specified tokens appearing in the completion.
    #   Accepts a JSON object that maps tokens (specified by their token ID in the
    #   tokenizer) to an associated bias value from -100 to 100. Mathematically,
    #   the bias is added to the logits generated by the model prior to sampling.
    #   The exact effect will vary per model, but values between -1 and 1 should
    #   decrease or increase likelihood of selection; values like -100 or 100
    #   should result in a ban or exclusive selection of the relevant token.
    record {}? logit_bias?;
    # Whether to return log probabilities of the output tokens or not. If true,
    #   returns the log probabilities of each output token returned in the
    #   `content` of `message`.
    boolean? logprobs?;
    # The maximum number of tokens that can be generated in the chat completion.
    # This value can be used to control costs for text generated via API.
    #
    # This value is now deprecated in favor of `max_completion_tokens`, and is
    # not compatible with o1 series models.
    #
    # # Deprecated
    @deprecated
    int? max_tokens?;
    # How many chat completion choices to generate for each input message. Note that you will be charged based on the number of generated tokens across all of the choices. Keep `n` as `1` to minimize costs.
    int? n = 1;
    # Configuration for a predicted output, which can greatly improve
    # response times when large parts of the model response are known
    # ahead of time. This is most common when you are regenerating a
    # file with only minor changes to most of the content.
    OpenAI\.PredictionContent prediction?;
    # This feature is in Beta.
    #   If specified, our system will make a best effort to sample deterministically, such that repeated requests with the same `seed` and parameters should return the same result.
    #   Determinism is not guaranteed, and you should refer to the `system_fingerprint` response parameter to monitor changes in the backend.
    #
    # # Deprecated
    @deprecated
    int? seed?;
    # Options for streaming response. Only set this when you set `stream: true`.
    OpenAI\.ChatCompletionStreamOptions stream_options?;
    # A list of tools the model may call. You can provide either
    #   [custom tools](https://platform.openai.com/docs/guides/function-calling#custom-tools) or
    #   [function tools](https://platform.openai.com/docs/guides/function-calling).
    (OpenAI\.ChatCompletionTool|OpenAI\.CustomToolChatCompletions)[] tools?;
    # Controls which (if any) tool is called by the model.
    # `none` means the model will not call any tool and instead generates a message.
    # `auto` means the model can pick between generating a message or calling one or more tools.
    # `required` means the model must call one or more tools.
    # Specifying a particular tool via `{"type": "function", "function": {"name": "my_function"}}` forces the model to call that tool.
    # `none` is the default when no tools are present. `auto` is the default if tools are present.
    OpenAI\.ChatCompletionToolChoiceOption tool_choice?;
    # Whether to enable [parallel function calling](https://platform.openai.com/docs/guides/function-calling#configuring-parallel-function-calling) during tool use.
    OpenAI\.ParallelToolCalls parallel_tool_calls?;
    # Deprecated in favor of `tool_choice`.
    #   Controls which (if any) function is called by the model.
    #   `none` means the model will not call a function and instead generates a
    #   message.
    #   `auto` means the model can pick between generating a message or calling a
    #   function.
    #   Specifying a particular function via `{"name": "my_function"}` forces the
    #   model to call that function.
    #   `none` is the default when no functions are present. `auto` is the default
    #   if functions are present.
    #
    # # Deprecated
    @deprecated
    "none"|"auto"|OpenAI\.ChatCompletionFunctionCallOption function_call?;
    # Deprecated in favor of `tools`.
    #   A list of functions the model may generate JSON inputs for.
    #
    # # Deprecated
    @constraint:Array {maxLength: 128, minLength: 1}
    @deprecated
    OpenAI\.ChatCompletionFunctions[] functions?;
    # User security context contains several parameters that describe the application itself, and the end user that interacts with the application. These fields assist your security operations teams to investigate and mitigate security incidents by providing a comprehensive approach to protecting your AI applications. [Learn more](https://aka.ms/TP4AI/Documentation/EndUserContext) about protecting AI applications using Microsoft Defender for Cloud.
    AzureUserSecurityContext user_security_context?;
};

public type inline_response_200 record {string id; OpenAI\.CreateChatCompletionResponseChoices[] choices; int created; string model; string system_fingerprint?; "chat.completion" 'object; OpenAI\.CompletionUsage usage?; inline_response_200_prompt_filter_results[] prompt_filter_results?;}|record {string id; OpenAI\.CreateChatCompletionStreamResponseChoices[] choices; int created; string model; string system_fingerprint?; "chat.completion.chunk" 'object; OpenAI\.CompletionUsage usage?; OpenAI\.ChatCompletionStreamResponseDelta delta?; AzureContentFilterResultForChoice content_filter_results?;};

# Request message types

public type OpenAI\.ChatCompletionRequestMessage record {
    OpenAI\.ChatCompletionRequestMessageType role;
};

public type OpenAI\.ChatCompletionRequestMessageType string|"developer"|"system"|"user"|"assistant"|"tool"|"function";

public type OpenAI\.ChatCompletionRequestMessageContentPartText record {
    "text" 'type;
    string text;
};

# Request format and modality types

public type OpenAI\.Metadata record {
};

public type OpenAI\.ResponseModalities ("text"|"audio")[]?;

public type OpenAI\.Verbosity "low"|"medium"|"high"?;

public type OpenAI\.ReasoningEffort "none"|"minimal"|"low"|"medium"|"high"|"xhigh"?;

public type OpenAI\.StopConfiguration string|string[]??;

public type OpenAI\.ParallelToolCalls boolean;

public type OpenAI\.CreateChatCompletionRequestResponseFormat record {
    OpenAI\.CreateChatCompletionRequestResponseFormatType 'type;
};

public type OpenAI\.CreateChatCompletionRequestResponseFormatType string|"text"|"json_schema"|"json_object";

public type OpenAI\.CreateChatCompletionRequestAudio record {
    OpenAI\.VoiceIdsShared voice;
    "wav"|"aac"|"mp3"|"flac"|"opus"|"pcm16" format;
};

public type OpenAI\.VoiceIdsShared string|"alloy"|"ash"|"ballad"|"coral"|"echo"|"sage"|"shimmer"|"verse"|"marin"|"cedar";

public type OpenAI\.ChatCompletionStreamOptions record {
    boolean include_usage?;
    boolean include_obfuscation?;
};

public type OpenAI\.PredictionContent record {
    "content" 'type;
    string|OpenAI\.ChatCompletionRequestMessageContentPartText[] content;
};

# Tool types

public type OpenAI\.ChatCompletionTool record {
    "function" 'type;
    OpenAI\.FunctionObject 'function;
};

public type OpenAI\.FunctionObject record {
    string description?;
    string name;
    OpenAI\.FunctionParameters parameters?;
    boolean? strict?;
};

public type OpenAI\.FunctionParameters record {
};

public type OpenAI\.CustomToolChatCompletions record {
    "custom" 'type;
    OpenAI\.CustomToolChatCompletionsCustom custom;
};

public type OpenAI\.CustomToolChatCompletionsCustom record {
    string name;
    string description?;
    OpenAI\.CustomToolChatCompletionsCustomFormatText|OpenAI\.CustomToolChatCompletionsCustomFormatGrammar format?;
};

public type OpenAI\.CustomToolChatCompletionsCustomFormatText record {
    "text" 'type;
};

public type OpenAI\.CustomToolChatCompletionsCustomFormatGrammar record {
    "grammar" 'type;
    OpenAI\.CustomToolChatCompletionsCustomFormatGrammarGrammar grammar;
};

public type OpenAI\.CustomToolChatCompletionsCustomFormatGrammarGrammar record {
    string definition;
    "lark"|"regex" syntax;
};

# Tool choice types

public type OpenAI\.ChatCompletionToolChoiceOption "none"|"auto"|"required"|OpenAI\.ChatCompletionAllowedToolsChoice|OpenAI\.ChatCompletionNamedToolChoice|OpenAI\.ChatCompletionNamedToolChoiceCustom;

public type OpenAI\.ChatCompletionAllowedToolsChoice record {
    "allowed_tools" 'type;
    OpenAI\.ChatCompletionAllowedTools allowed_tools;
};

public type OpenAI\.ChatCompletionAllowedTools record {
    "auto"|"required" mode;
    record {}[] tools;
};

public type OpenAI\.ChatCompletionNamedToolChoice record {
    "function" 'type;
    OpenAI\.ChatCompletionNamedToolChoiceFunction 'function;
};

public type OpenAI\.ChatCompletionNamedToolChoiceFunction record {
    string name;
};

public type OpenAI\.ChatCompletionNamedToolChoiceCustom record {
    "custom" 'type;
    OpenAI\.ChatCompletionNamedToolChoiceCustomCustom custom;
};

public type OpenAI\.ChatCompletionNamedToolChoiceCustomCustom record {
    string name;
};

# Deprecated function call types

public type OpenAI\.ChatCompletionFunctionCallOption record {
    string name;
};

public type OpenAI\.ChatCompletionFunctions record {
    string description?;
    string name;
    OpenAI\.FunctionParameters parameters?;
};

# Azure user security context

# User security context contains several parameters that describe the application itself, and the end user that interacts with the application. These fields assist your security operations teams to investigate and mitigate security incidents by providing a comprehensive approach to protecting your AI applications. [Learn more](https://aka.ms/TP4AI/Documentation/EndUserContext) about protecting AI applications using Microsoft Defender for Cloud.
public type AzureUserSecurityContext record {
    # The name of the application. Sensitive personal information should not be included in this field.
    string application_name?;
    # This identifier is the Microsoft Entra ID (formerly Azure Active Directory) user object ID used to authenticate end-users within the generative AI application. Sensitive personal information should not be included in this field.
    string end_user_id?;
    # The Microsoft 365 tenant ID the end user belongs to. It's required when the generative AI application is multitenant.
    string end_user_tenant_id?;
    # Captures the original client's IP address.
    string source_ip?;
};

# Non-streaming response types

public type OpenAI\.CreateChatCompletionResponseChoices record {
    "stop"|"length"|"tool_calls"|"content_filter"|"function_call" finish_reason;
    int index;
    OpenAI\.ChatCompletionResponseMessage message;
    OpenAI\.CreateChatCompletionResponseChoicesLogprobs logprobs;
    AzureContentFilterResultForChoice content_filter_results?;
};

public type OpenAI\.ChatCompletionResponseMessage record {
    string? content;
    string? refusal;
    OpenAI\.ChatCompletionMessageToolCallsItem tool_calls?;
    OpenAI\.ChatCompletionResponseMessageAnnotations[] annotations?;
    "assistant" role;
    OpenAI\.ChatCompletionResponseMessageFunctionCall function_call?;
    OpenAI\.ChatCompletionResponseMessageAudio audio?;
    string reasoning_content?;
};

public type OpenAI\.ChatCompletionMessageToolCallsItem (OpenAI\.ChatCompletionMessageToolCall|OpenAI\.ChatCompletionMessageCustomToolCall)[];

public type OpenAI\.ChatCompletionMessageToolCall record {
    string id;
    "function" 'type;
    OpenAI\.ChatCompletionMessageToolCallFunction 'function;
};

public type OpenAI\.ChatCompletionMessageToolCallFunction record {
    string name;
    string arguments;
};

public type OpenAI\.ChatCompletionMessageCustomToolCall record {
    string id;
    "custom" 'type;
    OpenAI\.ChatCompletionMessageCustomToolCallCustom custom;
};

public type OpenAI\.ChatCompletionMessageCustomToolCallCustom record {
    string name;
    string input;
};

public type OpenAI\.ChatCompletionResponseMessageAnnotations record {
    "url_citation" 'type;
    OpenAI\.ChatCompletionResponseMessageAnnotationsUrlCitation url_citation;
};

public type OpenAI\.ChatCompletionResponseMessageAnnotationsUrlCitation record {
    int end_index;
    int start_index;
    string url;
    string title;
};

public type OpenAI\.ChatCompletionResponseMessageFunctionCall record {
    string arguments;
    string name;
};

public type OpenAI\.ChatCompletionResponseMessageAudio record {
    string id;
    int expires_at;
    string data;
    string transcript;
};

public type OpenAI\.CreateChatCompletionResponseChoicesLogprobs record {
    OpenAI\.ChatCompletionTokenLogprob[]? content;
    OpenAI\.ChatCompletionTokenLogprob[]? refusal;
};

# Streaming response types

public type OpenAI\.CreateChatCompletionStreamResponseChoices record {
    OpenAI\.ChatCompletionStreamResponseDelta delta;
    OpenAI\.CreateChatCompletionStreamResponseChoicesLogprobs logprobs?;
    "stop"|"length"|"tool_calls"|"content_filter"|"function_call"? finish_reason;
    int index;
};

public type OpenAI\.ChatCompletionStreamResponseDelta record {
    string? content?;
    OpenAI\.ChatCompletionStreamResponseDeltaFunctionCall function_call?;
    OpenAI\.ChatCompletionMessageToolCallChunk[] tool_calls?;
    "developer"|"system"|"user"|"assistant"|"tool" role?;
    string? refusal?;
    string reasoning_content?;
};

public type OpenAI\.ChatCompletionStreamResponseDeltaFunctionCall record {
    string arguments?;
    string name?;
};

public type OpenAI\.ChatCompletionMessageToolCallChunk record {
    int index;
    string id?;
    "function" 'type?;
    OpenAI\.ChatCompletionMessageToolCallChunkFunction 'function?;
};

public type OpenAI\.ChatCompletionMessageToolCallChunkFunction record {
    string name?;
    string arguments?;
};

public type OpenAI\.CreateChatCompletionStreamResponseChoicesLogprobs record {
    OpenAI\.ChatCompletionTokenLogprob[]? content;
    OpenAI\.ChatCompletionTokenLogprob[]? refusal;
};

# Token and logprob types

public type OpenAI\.ChatCompletionTokenLogprob record {
    string token;
    decimal logprob;
    int[]? bytes;
    OpenAI\.ChatCompletionTokenLogprobTopLogprobs[] top_logprobs;
};

public type OpenAI\.ChatCompletionTokenLogprobTopLogprobs record {
    string token;
    decimal logprob;
    int[]? bytes;
};

# Usage types

public type OpenAI\.CompletionUsage record {
    int completion_tokens;
    int prompt_tokens;
    int total_tokens;
    OpenAI\.CompletionUsageCompletionTokensDetails completion_tokens_details?;
    OpenAI\.CompletionUsagePromptTokensDetails prompt_tokens_details?;
};

public type OpenAI\.CompletionUsageCompletionTokensDetails record {
    int accepted_prediction_tokens?;
    int audio_tokens?;
    int reasoning_tokens?;
    int rejected_prediction_tokens?;
};

public type OpenAI\.CompletionUsagePromptTokensDetails record {
    int audio_tokens?;
    int cached_tokens?;
};

# Azure content filter types

public type inline_response_200_prompt_filter_results record {
    # The index of the input prompt that this content filter result corresponds to.
    int:Signed32 prompt_index;
    # The content filter results associated with the indexed input prompt.
    AzureContentFilterResultForPrompt content_filter_results;
};

# A content filter result associated with a single input prompt item into a generative AI system.
public type AzureContentFilterResultForPrompt record {
    # The index of the input prompt associated with the accompanying content filter result categories.
    int:Signed32 prompt_index?;
    # The content filter category details for the result.
    AzureContentFilterResultForPrompt_content_filter_results content_filter_results?;
};

# The content filter category details for the result.
public type AzureContentFilterResultForPrompt_content_filter_results record {
    # A content filter category for language related to anatomical organs and genitals, romantic relationships, acts
    # portrayed in erotic or affectionate terms, pregnancy, physical sexual acts, including those portrayed as an
    # assault or a forced sexual violent act against one's will, prostitution, pornography, and abuse.
    AzureContentFilterSeverityResult sexual?;
    # A content filter category that can refer to any content that attacks or uses pejorative or discriminatory
    # language with reference to a person or identity group based on certain differentiating attributes of these groups
    # including but not limited to race, ethnicity, nationality, gender identity and expression, sexual orientation,
    # religion, immigration status, ability status, personal appearance, and body size.
    AzureContentFilterSeverityResult hate?;
    # A content filter category for language related to physical actions intended to hurt, injure, damage, or kill
    # someone or something; describes weapons, guns and related entities, such as manufactures, associations,
    # legislation, and so on.
    AzureContentFilterSeverityResult violence?;
    # A content filter category that describes language related to physical actions intended to purposely hurt, injure,
    # damage one's body or kill oneself.
    AzureContentFilterSeverityResult self_harm?;
    # A detection result that identifies whether crude, vulgar, or otherwise objection language is present in the
    # content.
    AzureContentFilterDetectionResult profanity?;
    # A collection of binary filtering outcomes for configured custom blocklists.
    AzureContentFilterBlocklistResult custom_blocklists?;
    # A collection of binary filtering outcomes for configured custom topics.
    AzureContentFilterCustomTopicResult custom_topics?;
    # If present, details about an error that prevented content filtering from completing its evaluation.
    AzureContentFilterResultForChoice_error 'error?;
    # A detection result that describes user prompt injection attacks, where malicious users deliberately exploit
    # system vulnerabilities to elicit unauthorized behavior from the LLM. This could lead to inappropriate content
    # generation or violations of system-imposed restrictions.
    AzureContentFilterDetectionResult jailbreak?;
    # A detection result that describes attacks on systems powered by Generative AI models that can happen every time
    # an application processes information that wasn't directly authored by either the developer of the application or
    # the user.
    AzureContentFilterDetectionResult indirect_attack?;
};

# A content filter result for a single response item produced by a generative AI system.
public type AzureContentFilterResultForChoice record {
    # A content filter category for language related to anatomical organs and genitals, romantic relationships, acts
    # portrayed in erotic or affectionate terms, pregnancy, physical sexual acts, including those portrayed as an
    # assault or a forced sexual violent act against one's will, prostitution, pornography, and abuse.
    AzureContentFilterSeverityResult sexual?;
    # A content filter category that can refer to any content that attacks or uses pejorative or discriminatory
    # language with reference to a person or identity group based on certain differentiating attributes of these groups
    # including but not limited to race, ethnicity, nationality, gender identity and expression, sexual orientation,
    # religion, immigration status, ability status, personal appearance, and body size.
    AzureContentFilterSeverityResult hate?;
    # A content filter category for language related to physical actions intended to hurt, injure, damage, or kill
    # someone or something; describes weapons, guns and related entities, such as manufactures, associations,
    # legislation, and so on.
    AzureContentFilterSeverityResult violence?;
    # A content filter category that describes language related to physical actions intended to purposely hurt, injure,
    # damage one's body or kill oneself.
    AzureContentFilterSeverityResult self_harm?;
    # A detection result that identifies whether crude, vulgar, or otherwise objection language is present in the
    # content.
    AzureContentFilterDetectionResult profanity?;
    # A collection of binary filtering outcomes for configured custom blocklists.
    AzureContentFilterBlocklistResult custom_blocklists?;
    # A collection of binary filtering outcomes for configured custom topics.
    AzureContentFilterCustomTopicResult custom_topics?;
    # If present, details about an error that prevented content filtering from completing its evaluation.
    AzureContentFilterResultForChoice_error 'error?;
    # A detection result that describes a match against text protected under copyright or other status.
    AzureContentFilterDetectionResult protected_material_text?;
    # A detection result that describes a match against licensed code or other protected source material.
    AzureContentFilterResultForChoice_protected_material_code protected_material_code?;
    AzureContentFilterCompletionTextSpanDetectionResult ungrounded_material?;
    # A detection result that describes matches against Personal Identifiable Information with configurable subcategories.
    AzureContentFilterPersonallyIdentifiableInformationResult personally_identifiable_information?;
};

# A labeled content filter result item that indicates whether the content was filtered and what the qualitative
# severity level of the content was, as evaluated against content filter configuration for the category.
public type AzureContentFilterSeverityResult record {
    # Whether the content severity resulted in a content filtering action.
    boolean filtered;
    # The labeled severity of the content.
    "safe"|"low"|"medium"|"high" severity;
};

public type AzureContentFilterDetectionResult record {
    # Whether the content detection resulted in a content filtering action.
    boolean filtered;
    # Whether the labeled content category was detected in the content.
    boolean detected;
};

# A collection of true/false filtering results for configured custom blocklists.
public type AzureContentFilterBlocklistResult record {
    # A value indicating whether any of the detailed blocklists resulted in a filtering action.
    boolean filtered;
    # The pairs of individual blocklist IDs and whether they resulted in a filtering action.
    AzureContentFilterBlocklistResult_details[] details?;
};

public type AzureContentFilterBlocklistResult_details record {
    # A value indicating whether the blocklist produced a filtering action.
    boolean filtered;
    # The ID of the custom blocklist evaluated.
    string id;
};

# A collection of true/false filtering results for configured custom topics.
public type AzureContentFilterCustomTopicResult record {
    # A value indicating whether any of the detailed topics resulted in a filtering action.
    boolean filtered;
    # The pairs of individual topic IDs and whether they are detected.
    AzureContentFilterCustomTopicResult_details[] details?;
};

public type AzureContentFilterCustomTopicResult_details record {
    # A value indicating whether the topic is detected.
    boolean detected;
    # The ID of the custom topic evaluated.
    string id;
};

public type AzureContentFilterResultForChoice_error record {
    # A distinct, machine-readable code associated with the error.
    int:Signed32 code;
    # A human-readable message associated with the error.
    string message;
};

# A detection result that describes a match against licensed code or other protected source material.
public type AzureContentFilterResultForChoice_protected_material_code record {
    # Whether the content detection resulted in a content filtering action.
    boolean filtered;
    # Whether the labeled content category was detected in the content.
    boolean detected;
    # If available, the citation details describing the associated license and its location.
    AzureContentFilterResultForChoice_protected_material_code_citation citation?;
};

public type AzureContentFilterResultForChoice_protected_material_code_citation record {
    # The name or identifier of the license associated with the detection.
    string license?;
    # The URL associated with the license.
    string URL?;
};

public type AzureContentFilterCompletionTextSpanDetectionResult record {
    # Whether the content detection resulted in a content filtering action.
    boolean filtered;
    # Whether the labeled content category was detected in the content.
    boolean detected;
    # Detailed information about the detected completion text spans.
    AzureContentFilterCompletionTextSpan[] details;
};

# A representation of a span of completion text as used by Azure OpenAI content filter results.
public type AzureContentFilterCompletionTextSpan record {
    # Offset of the UTF32 code point which begins the span.
    int:Signed32 completion_start_offset;
    # Offset of the first UTF32 code point which is excluded from the span. This field is always equal to completion_start_offset for empty spans. This field is always larger than completion_start_offset for non-empty spans.
    int:Signed32 completion_end_offset;
};

# A content filter detection result for Personally Identifiable Information that includes harm extensions.
public type AzureContentFilterPersonallyIdentifiableInformationResult AzureContentFilterDetectionResult;
