openapi: 3.0.0
servers:
  - url: https://api.zoom.us/v2
info:
  contact:
    email: developersupport@zoom.us
    name: Zoom Developers
    url: https://developer.zoom.us/
  description: Client endpoint for Zoom API
  license:
    name: MIT for OAS 2.0
    url: https://opensource.org/licenses/MIT
  termsOfService: https://zoom.us/docs/en-us/zoom_api_license_and_tou.html
  title: Zoom API
  version: 2.0.0
  x-display:
    label: Zoom Client
security:
  - OAuth: []
tags:
  - description: Meeting operations
    name: Meetings
  - description: Meeting operations
    name: Webinars
paths:
  "/users/{userId}/meetings":
    get:
      description: >-
        List all the meetings that were scheduled for a user (meeting
        host). This API only supports scheduled meetings and thus, details on
        instant meetings are not returned via this API.

        **Scopes:** `meeting:read:admin` `meeting:read`
         
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      summary: List meetings
      operationId: listMeetings
      x-display:
        label: List Meetings
      security:
        - OAuth: []
      tags:
        - Meetings
    post:
      description: >-
        [Create a
        meeting](https://support.zoom.us/hc/en-us/articles/201362413-Scheduling-meetings)
        for a user. This API has a daily rate limit of 100 requests per day.
        Therefore, only 100 **Create a Meeting** API requests are permitted
        within a 24 hour window for a user.


        <aside>The <code>start_url</code> of a meeting is a URL using which a host or an alternative host can start a meeting. The expiration time for the <code>start_url</code> field is two hours for all regular users. 
          
        For custCreate meeting hosts( i.e., users created using the <code>custCreate</code> option via the [Create Users](https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usercreate) API), the expiration time of the <code>start_url</code> field is 90 days from the generation of the <code>start_url</code>.
          
        For security reasons, the recommended way to retrieve the updated value for the <code>start_url</code> field programmatically (after expiry) is by calling the [Retrieve a Meeting API](https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meeting) and referring to the value of the <code>start_url</code> field in the response.</aside>

        Scopes: `meeting:write:admin` `meeting:write`
         
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: createMeeting
      x-display:
        label: Create Meeting
      summary: Create a meeting
      tags:
        - Meetings
  "/meetings/{meetingId}/registrants":
    get:
      description: A host or a user with admin permission can require [registration
        for a Zoom meeting
      operationId: listMeetingRegistrants
      x-display:
        label: List Meeting Registrants
      security:
        - OAuth: []
      summary: List meeting registrants
      tags:
        - Meetings
    post:
      description: >-
        Register a participant for a meeting. Note that there is a
        maximum limit of 4999 registrants per meeting and users will see an
        error if the capacity has reached.


        **Prerequisite:**

        * Host user type must be "Licensed".


        **Scopes:** `meeting:write:admin` `meeting:write`
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: addMeetingRegistrant
      x-display:
        label: Add Meeting Registrant
      security:
        - OAuth: []
      summary: Add meeting registrant
      tags:
        - Meetings
  "/meetings/{meetingId}":
    delete:
      description: >+
        Delete a meeting.

        **Scopes:** `meeting:write:admin` `meeting:write`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` 

      operationId: deleteMeeting
      x-display:
        label: Delete Meeting
      security:
        - OAuth: []
      summary: Delete a meeting
      tags:
        - Meetings
    get:
      description: >+
        Retrieve the details of a meeting.

        **Scopes:** `meeting:read:admin` `meeting:read`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` 

      operationId: getMeetingById
      x-display:
        label: Get Meeting Details
      security:
        - OAuth: []
      summary: Get a meeting
      tags:
        - Meetings
  "/past_meetings/{meetingUUID}/participants":
    get:
      description: >
        Retrieve information on participants from a past meeting. <br><br>

        **Scopes:** `meeting:read:admin` `meeting:read`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
        **Prerequisites:**<br>

        * Paid account on a Pro or higher plan.


        <br> <br>  **Note**: Please double encode your UUID when using this API if the UUID begins with a '/'or contains '//' in it.
      operationId: listPastMeetingParticipants
      x-display:
        label: List Past Meeting Participants
      security:
        - OAuth: []
      summary: List past meeting participants
      tags:
        - Meetings
  "/webinars/{webinarId}/registrants":
    get:
      description: >+
        Zoom users with a [Webinar Plan](https://zoom.us/webinar) have
        access to creating and managing Webinars. Webinar allows a host to
        broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a
        [Webinar with
        registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration)
        requires your registrants to complete a brief form before receiving the
        link to join the Webinar. 

        Use this API to list all the users that have registered for a webinar.  

        **Prerequisites:**

        * Pro or higher plan with a Webinar Add-on. 

        **Scopes:** `webinar:read:admin` `webinar:read`  
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` 

      operationId: listWebinarRegistrants
      x-display:
        label: List Webinar Meeting Registrants
      security:
        - OAuth: []
      summary: List webinar registrants
      tags:
        - Webinars
  "/past_webinars/{webinarId}/participants":
    get:
      description: >+
        Use this API to list all the participants who attended a webinar
        hosted in the past.  


        **Prerequisites:**

        * Pro or higher plan with a Webinar Add-on. 

        **Scopes:** `webinar:read:admin` `webinar:read`  

         

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` 



      operationId: listWebinarParticipants
      x-display:
        label: List Webinar Participants
      summary: List webinar participants
      tags:
        - Webinars
  "/past_webinars/{WebinarUUID}/absentees":
    get:
      description: >-
        List absentees of a webinar.  

        **Scopes:** `webinar:read:admin` `webinar:read` 
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`
      operationId: listWebinarAbsentees
      x-display:
        label: List Webinar Absentees
      security:
        - OAuth: []
      summary: List webinar absentees
      tags:
        - Webinars
components:
  securitySchemes:
    OAuth:
      flows:
        authorizationCode:
          authorizationUrl: https://zoom.us/oauth/authorize
          scopes: {}
          tokenUrl: https://zoom.us/oauth/token
      type: oauth2