[package]
license = ["Apache-2.0"]
keywords = ["Messaging", "Cost/Freemium", "Vendor/Ably", "Area/Messaging", "Type/Connector"]
org = "ballerinax"
name = "ably"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/ably"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
