openapi: 3.0.1
info:
  x-ballerina-display:
    label: Bitbucket
    iconPath: "icon.png"
  title: Bitbucket API
  description: >-
    This is a generated connector for [Bitbucket API v2.0](https://developer.atlassian.com/bitbucket/api/2/reference/) OpenAPI Specification.
    Code against the Bitbucket API to automate simple tasks, embed Bitbucket data into your own site, build mobile or desktop apps, 
    or even add custom UI add-ons into Bitbucket itself using the Connect framework.
  x-ballerina-init-description: >- 
    The connector initialization requires setting the API credentials.
    Create an [Bitbucket account](https://bitbucket.org/product/) and obtain tokens following 
    [this guide](https://developer.atlassian.com/bitbucket/api/2/reference/meta/authentication).
  termsOfService: https://www.atlassian.com/legal/customer-agreement
  contact:
    name: Bitbucket Support
    url: https://support.atlassian.com/bitbucket-cloud/
    email: support@bitbucket.org
  version: "2.0"
servers:
  - url: https://api.bitbucket.org/2.0
tags:
  - name: Addon
    description: |
      The addon resource is intended to use used by Bitbucket Cloud Connect
      Apps, and only supports JWT authentication.
  - name: Branch restrictions
    description: |
      Repository owners and administrators can set branch management
      rules on a repository that control what can be pushed by whom.
      Through these rules, you can enforce a project or team
      workflow. For example, owners or administrators can:

      * Limit push powers
      * Prevent branch deletion
      * Prevent history re-writes (Git only)
  - name: Branching model
    description: |
      The branching model resource is used to modify the branching model
      for a repository.

      You can use the branching model to define a branch based workflow
      for your repositories. When you map your workflow to branch types,
      you can ensure that branches are named consistently by configuring
      which branch types to make available.
  - name: Commit statuses
    description: |
      Commit statuses provide a way to tag commits with meta data,
      like automated build results.
  - name: Commits
    description: |
      These are the repository's commits. They are paginated and returned in
      reverse chronological order, similar to the output of git log.
  - name: Deployments
    description: |
      Teams are deploying code faster than ever, thanks to continuous
      delivery practices and tools like Bitbucket Pipelines. Bitbucket
      Deployments gives teams visibility into their deployment
      environments and helps teams to track how far changes have
      progressed in their deployment pipeline.
  - name: Downloads
    description: Access the list of download links associated with the repository.
  - name: Issue tracker
    description: |
      The issue resources provide functionality for getting information on
      issues in an issue tracker, creating new issues, updating them and deleting
      them.

      You can access public issues without authentication, but you can't gain access
      to private repositories' issues. By authenticating, you will get the ability
      to create issues, as well as access to updating data or deleting issues you
      have access to.
  - name: Pipelines
    description: |
      Bitbucket Pipelines brings continuous delivery to Bitbucket
      Cloud, empowering teams with full branching to deployment
      visibility and faster feedback loops.
  - name: Projects
    description: |
      Bitbucket Cloud projects make it easier for teams to focus on
      a goal, product, or process by organizing their repositories.
  - name: Pullrequests
    description: |
      Pull requests are a feature that makes it easier for developers
      to collaborate using Bitbucket. They provide a user-friendly web
      interface for discussing proposed changes before integrating them
      into the official project.
  - name: Refs
    description: |
      The refs resource allows you access branches and tags in a repository.
      By default, results will be in the order the underlying source control
      system returns them and identical to the ordering one sees when running
      "$ git show-ref". Note that this follows simple lexical ordering of the
       ref names.
  - name: Reports
    description: |
      Code insights provides reports, annotations, and metrics to help you
      and your team improve code quality in pull requests throughout the code
      review process. Some of the available code insights are static analysis
      reports, security scan results, artifact links, unit tests, and build
      status.
  - name: Repositories
    description: |
      A Git repository is a virtual storage of your project. It
      allows you to save versions of your code, which you can access
      when needed. The repo resource allows you to access public repos,
      or repos that belong to a specific workspace.
  - name: Snippets
    description: |
      Snippets allow you share code segments or files with yourself, members of
      your workspace, or the world.

      Like pull requests, repositories and workspaces, the full set of snippets
      is defined by what the current user has access to. This includes all
      snippets owned by any of the workspaces the user is a member of, or
      snippets by other users that the current user is either watching or has
       collaborated on (for instance by commenting on it).
  - name: Source
    description: |-
      Browse the source code in the repository and
                                    create new commits by uploading.
  - name: Ssh
    description: |
      The SSH resource allows you to manage SSH keys.
  - name: Teams
    description: |
      The teams resource has been deprecated, and the workspaces
      endpoint should be used instead.

      The teams resource returns all the teams that the authenticated
      user is associated with.
  - name: Users
    description: |
      The users resource allows you to access public information
      associated with a user account. Most resources in the users
      endpoint have been deprecated in favor of workspaces.
  - name: Webhooks
    description: |
      Webhooks provide a way to configure Bitbucket Cloud to make requests to
      your server (or another external service) whenever certain events occur in
      Bitbucket Cloud.

      A webhook consists of:

      * A subject -- The resource that generates the events. Currently, this resource
      is the repository, user account, or team where you create the webhook.
      * One or more event -- The default event is a repository push, but you can
      select multiple events that can trigger the webhook.
      * A URL -- The endpoint where you want Bitbucket to send the event payloads
      when a matching event happens.

      There are two parts to getting a webhook to work: creating the webhook and
      triggering the webhook. After you create a webhook for an event, every time
      that event occurs, Bitbucket sends a payload request that describes the event
      to the specified URL. Thus, you can think of webhooks as a kind of
      notification system.

      Use webhooks to integrate applications with Bitbucket Cloud. The following
      use cases provides examples of when you would want to use webhooks:

      * Every time a user pushes commits in a repository, you may want to notify
      your CI server to start a build.
      * Every time a user pushes commits or creates a pull request, you may want to
      display a notification in your application.
  - name: Wiki
    description: |
      The wiki is a simple place to keep documents. Some people use it
      as their project home page. The wiki is a Git repository, so you
      can clone it and edit it like any other source files.
  - name: Workspaces
    description: |
      A workspace is where you create repositories, collaborate on
      your code, and organize different streams of work in your Bitbucket
      Cloud account. Workspaces replace the use of teams and users in API
      calls.
paths:
  /repositories/{workspace}:
    get:
      tags:
      - Repositories
      operationId: listWorkspaces
      summary: Returns a list of all repositories
      description: |-
        Returns a paginated list of all repositories owned by the specified
        account or UUID.

        The result can be narrowed down based on the authenticated user's role.

        E.g. with `?role=contributor`, only those repositories that the
        authenticated user has write access to are returned (this includes any
        repo the user is an admin on, as that implies write access).

        This endpoint also supports filtering and sorting of the results. See
        [filtering and sorting](../../meta/filtering) for more details.
      security:
      - oauth2:
        - repository
  /repositories/{workspace}/{repo_slug}/pullrequests:
    get:
      tags:
      - Pullrequests
      operationId: listPullrequets
      summary: Returns all pull requests
      description: Returns all pull requests on the specified repository. By default only open pull requests are returned. This can be controlled using the `state` query parameter. To retrieve pull requests that are in one of multiple states, repeat the `state` parameter for each individual state.
      security:
      - oauth2:
        - pullrequest
  /repositories/{workspace}/{repo_slug}/pullrequests/{pull_request_id}:
    get:
      tags:
        - Pullrequests
      summary: Returns the specified pull request
      operationId: getPullRequestByID
      security:
        - oauth2:
            - pullrequest
  /repositories/{workspace}/{repo_slug}:
    get:
      tags:
        - Repositories
      summary: Returns the object describing this repository
      operationId: GetRepositoryDetail
      security:
        - oauth2:
            - repository
    post:
      tags:
        - Repositories
      summary: Creates a new repository
      description: |-
        Creates a new repository.

        Note: In order to set the project for the newly created repository,
        pass in either the project key or the project UUID as part of the
        request body as shown in the examples below:

        ```
        $ curl -X POST -H "Content-Type: application/json" -d '{
            "scm": "git",
            "project": {
                "key": "MARS"
            }
        }' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding
        ```

        or

        ```
        $ curl -X POST -H "Content-Type: application/json" -d '{
            "scm": "git",
            "project": {
                "key": "{ba516952-992a-4c2d-acbd-17d502922f96}"
            }
        }' https://api.bitbucket.org/2.0/repositories/teamsinspace/hablanding
        ```

        The project must be assigned for all repositories. If the project is not provided,
        the repository is automatically assigned to the oldest project in the workspace.

        Note: In the examples above, the workspace ID `teamsinspace`,
        and/or the repository name `hablanding` can be replaced by UUIDs.
      operationId: CreateNewRepository
      security:
        - oauth2:
            - repository:admin
    delete:
      tags:
        - Repositories
      summary: Deletes the repository
      description: |-
        Deletes the repository. This is an irreversible operation

        This does not affect its forks.
      operationId: DeleteRepository
      security:
        - oauth2:
            - repository:delete
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}:
    get:
      tags:
        - Issue tracker
      summary: Returns the specified issue
      operationId: getIssueByID
      security:
        - oauth2:
            - issue
    delete:
      tags:
        - Issue tracker
      summary: Deletes the specified issue
      description: |-
        Deletes the specified issue. This requires write access to the repository
      operationId: DeleteIssue
      security:
        - oauth2:
            - issue:write
  /repositories/{workspace}/{repo_slug}/issues:
    get:
      tags:
        - Issue tracker
      summary: Returns the issues in the issue tracker
      operationId: ListIssues
      security:
        - oauth2:
            - issue
    post:
      tags:
        - Issue tracker
      summary: Creates a new issue
      description: |-
        Creates a new issue.

        This call requires authentication. Private repositories or private
        issue trackers require the caller to authenticate with an account that
        has appropriate authorization.

        The authenticated user is used for the issue's `reporter` field.
      operationId: CreateIssue
      security:
        - oauth2:
            - issue:write
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/comments:
    get:
      tags:
        - Issue tracker
      summary: Returns a list of all comments on an issue
      description: |-
        Returns a paginated list of all comments that were made on the
        specified issue.

        The default sorting is oldest to newest and can be overridden with
        the `sort` query parameter.
      operationId: listComments
      security:
        - oauth2:
            - issue
    post:
      tags:
        - Issue tracker
      summary: Creates a new issue comment
      description: |-
        Creates a new issue comment.

        ```
        $ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/issues/42/comments/ \
          -X POST -u evzijst \
          -H 'Content-Type: application/json' \
          -d '{"content": {"raw": "Lorem ipsum."}}'
        ```
      operationId: CreateNewIssueComment
      security:
        - oauth2:
            - issue:write
  /repositories/{workspace}/{repo_slug}/issues/{issue_id}/comments/{comment_id}:
    get:
      tags:
        - Issue tracker
      summary: Returns the specified issue comment object
      operationId: getCommentByID
      security:
        - oauth2:
            - issue
    put:
      tags:
        - Issue tracker
      summary: Updates the content of the specified issue comment
      description: |-
        Updates the content of the specified issue comment. Note that only
        the `content.raw` field can be modified.

        ```
        $ curl https://api.bitbucket.org/2.0/repositories/atlassian/prlinks/issues/42/comments/5728901 \
          -X PUT -u evzijst \
          -H 'Content-Type: application/json' \
          -d '{"content": {"raw": "Lorem ipsum."}'
        ```
      operationId: UpdateComment
      security:
        - oauth2:
            - issue:write
    delete:
      tags:
        - Issue tracker
      summary: Deletes the specified comment
      operationId: DeleteComment
      security:
        - oauth2:
            - issue:write
  /workspaces/{workspace}:
    get:
      tags:
        - Workspaces
      summary: Returns the requested workspace
      operationId: getWorkSpaceByID
      security:
        - oauth2: []
  /workspaces/{workspace}/projects/{project_key}:
    get:
      tags:
        - Projects
        - Workspaces
      summary: Returns the requested project
      operationId: getProjectByProjectKey
      security:
        - oauth2:
            - project
    put:
      tags:
        - Projects
      summary: Creates or Updates a project
      description: |-
        Since this endpoint can be used to both update and to create a
        project, the request body depends on the intent.

        ### Creation

        See the POST documentation for the project collection for an
        example of the request body.

        Note: The `key` should not be specified in the body of request
        (since it is already present in the URL). The `name` is required,
        everything else is optional.

        ### Update

        See the POST documentation for the project collection for an
        example of the request body.

        Note: The key is not required in the body (since it is already in
        the URL). The key may be specified in the body, if the intent is
        to change the key itself. In such a scenario, the location of the
        project is changed and is returned in the `Location` header of the
        response.
      operationId: createOrUpdateProject
      security:
        - oauth2:
            - project:write
    delete:
      tags:
        - Projects
      summary: Deletes a project.
      description: |-
        Deletes this project. This is an irreversible operation.

        You cannot delete a project that still contains repositories.
        To delete the project, [delete](../../../repositories/%7Bworkspace%7D/%7Brepo_slug%7D#delete)
        or transfer the repositories first.

        Example:
        ```
        $ curl -X DELETE https://api.bitbucket.org/2.0/bbworkspace1/PROJ
        ```
      operationId: deleteProject
      security:
        - oauth2:
            - project:write
components:
  securitySchemes:
    oauth2:
      type: oauth2
      description: OAuth 2 as per [RFC-6749](https://tools.ietf.org/html/rfc6749).
      flows:
        authorizationCode:
          authorizationUrl: https://bitbucket.org/site/oauth2/authorize
          tokenUrl: https://bitbucket.org/site/oauth2/access_token
          scopes:
            wiki: Read and modify your repositories' wikis
            pullrequest:write: Read and modify your repositories and their pull requests
            pipeline:variable:
              Access your repositories' build pipelines and configure
              their variables
            project:write:
              Read and modify your workspace's project settings, and
              read and transfer repositories within your workspace's projects
            pipeline:write: Access and rerun your repositories' build pipelines
            snippet: Read your snippets
            repository:delete: Delete your repositories
            repository:write: Read and modify your repositories
            issue: Read your repositories' issues
            email: Read your account's primary email address
            repository: Read your repositories
            issue:write: Read and modify your repositories' issues
            webhook: Read and modify your repositories' webhooks
            pipeline: Access your repositories' build pipelines
            snippet:write: Read and modify your snippets
            account: Read your account information
            repository:admin: Administer your repositories
            pullrequest: Read your repositories and their pull requests
            project:
              Read your workspace's project settings and read repositories
              contained within your workspace's projects
            team: Read your team membership information
            team:write: Read and modify your team membership information
            account:write: Read and modify your account information
