openapi: 3.0.0
servers:
  - url: https://blogger.googleapis.com
info:
  x-ballerina-display:
    label: Google Blogger
    iconPath: "icon.png"
  contact:
    name: Google
    url: https://google.com
    x-twitter: youtube
  description: |
    This is a generated connector for [Google Blogger API v3.0](https://developers.google.com/blogger/docs/3.0/getting_started) OpenAPI specification.
    The Blogger API provides access to posts, comments and pages of a Blogger blog.
  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials. 
    Create a [Google account](https://accounts.google.com/signup) and obtain tokens by following [this guide](https://developers.google.com/identity/protocols/oauth2).
  license:
    name: Creative Commons Attribution 3.0
    url: http://creativecommons.org/licenses/by/3.0/
  termsOfService: https://developers.google.com/terms/
  title: Blogger API v3
  version: v3
  x-apiClientRegistration:
    url: https://console.developers.google.com
  x-apisguru-categories:
    - analytics
    - media
  x-logo:
    url: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
  x-origin:
    - converter:
        url: https://github.com/mermade/oas-kit
        version: 7.0.4
      format: google
      url: https://blogger.googleapis.com/$discovery/rest?version=v3
      version: v1
  x-preferred: false
  x-providerName: googleapis.com
  x-serviceName: blogger
tags:
  - name: blogs
  - name: blogUserInfos
  - name: comments
  - name: pages
  - name: pageViews
  - name: posts
  - name: postUserInfos
  - name: users
paths:
  /v3/blogs/byurl:
    get:
      summary: Gets a blog by url.
      operationId: getByUrl.blogger.blogs
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - blogs
  "/v3/blogs/{blogId}":
    get:
      summary: Gets a blog by id.
      operationId: get.blogger.blogs
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - blogs
  "/v3/blogs/{blogId}/comments":
    get:
      summary: Lists comments by blog.
      operationId: listByBlog.blogger.comments
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - comments
  "/v3/blogs/{blogId}/pages":
    get:
      summary: Lists pages.
      operationId: list.blogger.pages
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - pages
    post:
      summary: Inserts a page.
      operationId: insert.blogger.pages
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
  "/v3/blogs/{blogId}/pages/{pageId}":
    delete:
      summary: Deletes a page by blog id and page id.
      operationId: delete.blogger.pages
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
    get:
      summary: Gets a page by blog id and page id.
      operationId: get.blogger.pages
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - pages
    patch:
      summary: Patches a page.
      operationId: patch.blogger.pages
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
    put:
      summary: Updates a page by blog id and page id.
      operationId: update.blogger.pages
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
  "/v3/blogs/{blogId}/pages/{pageId}/publish":
    post:
      summary: Publishes a page.
      operationId: publish.blogger.pages
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
  "/v3/blogs/{blogId}/pages/{pageId}/revert":
    post:
      summary: Reverts a published or scheduled page to draft state.
      operationId: revert.blogger.pages
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pages
  "/v3/blogs/{blogId}/pageviews":
    get:
      summary: Gets page views by blog id.
      operationId: get.blogger.pageViews
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - pageViews
  "/v3/blogs/{blogId}/posts":
    get:
      summary: Lists posts.
      operationId: list.blogger.posts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - posts
    post:
      summary: Inserts a post.
      operationId: insert.blogger.posts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
  "/v3/blogs/{blogId}/posts/bypath":
    get:
      summary: Gets a post by path.
      operationId: getByPath.blogger.posts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - posts
  "/v3/blogs/{blogId}/posts/search":
    get:
      summary: Searches for posts matching given query terms in the specified blog.
      operationId: search.blogger.posts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - posts
  "/v3/blogs/{blogId}/posts/{postId}":
    delete:
      summary: Deletes a post by blog id and post id.
      operationId: delete.blogger.posts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
    get:
      summary: Gets a post by blog id and post id
      operationId: get.blogger.posts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - posts
    patch:
      summary: Patches a post.
      operationId: patch.blogger.posts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
    put:
      summary: Updates a post by blog id and post id.
      operationId: update.blogger.posts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
  "/v3/blogs/{blogId}/posts/{postId}/comments":
    get:
      summary: Lists comments.
      operationId: list.blogger.comments
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - comments
  "/v3/blogs/{blogId}/posts/{postId}/comments/{commentId}":
    delete:
      summary: Deletes a comment by blog id, post id and comment id.
      operationId: delete.blogger.comments
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - comments
    get:
      summary: Gets a comment by id.
      operationId: get.blogger.comments
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - comments
  "/v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/approve":
    post:
      summary: Marks a comment as not spam by blog id, post id and comment id.
      operationId: approve.blogger.comments
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - comments
  "/v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent":
    post:
      summary: Removes the content of a comment by blog id, post id and comment id.
      operationId: removeContent.blogger.comments
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - comments
  "/v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/spam":
    post:
      summary: Marks a comment as spam by blog id, post id and comment id.
      operationId: markAsSpam.blogger.comments
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - comments
  "/v3/blogs/{blogId}/posts/{postId}/publish":
    post:
      summary: Publishes a post.
      operationId: publish.blogger.posts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
  "/v3/blogs/{blogId}/posts/{postId}/revert":
    post:
      summary: Reverts a published or scheduled post to draft state.
      operationId: revert.blogger.posts
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
      tags:
        - posts
  "/v3/users/{userId}":
    get:
      summary: Gets one user by user_id.
      operationId: get.blogger.users
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - users
  "/v3/users/{userId}/blogs":
    get:
      summary: Lists blogs by user.
      operationId: listByUser.blogger.blogs
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - blogs
  "/v3/users/{userId}/blogs/{blogId}":
    get:
      summary: Gets one blog and user info pair by blog id and user id.
      operationId: get.blogger.blogUserInfos
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - blogUserInfos
  "/v3/users/{userId}/blogs/{blogId}/posts":
    get:
      summary: Lists post and user info pairs.
      operationId: list.blogger.postUserInfos
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - postUserInfos
  "/v3/users/{userId}/blogs/{blogId}/posts/{postId}":
    get:
      summary: Gets one post and user info pair, by post_id and user_id.
      operationId: get.blogger.postUserInfos
      security:
        - Oauth2:
            - https://www.googleapis.com/auth/blogger
          Oauth2c:
            - https://www.googleapis.com/auth/blogger
        - Oauth2:
            - https://www.googleapis.com/auth/blogger.readonly
          Oauth2c:
            - https://www.googleapis.com/auth/blogger.readonly
      tags:
        - postUserInfos
components:
  securitySchemes:
    Oauth2:
      description: Oauth 2.0 implicit authentication
      flows:
        implicit:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/blogger: Manage your Blogger account
            https://www.googleapis.com/auth/blogger.readonly: View your Blogger account
      type: oauth2
    Oauth2c:
      description: Oauth 2.0 authorizationCode authentication
      flows:
        authorizationCode:
          authorizationUrl: https://accounts.google.com/o/oauth2/auth
          scopes:
            https://www.googleapis.com/auth/blogger: Manage your Blogger account
            https://www.googleapis.com/auth/blogger.readonly: View your Blogger account
          tokenUrl: https://accounts.google.com/o/oauth2/token
      type: oauth2
