{
    "openapi": "3.0.1",
    "info": {
        "title": "Payments",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "Fetch all refunded payments in the account.",
        "x-hubspot-introduction": "Use the payments API to fetch information about an account's payments. This is a read-only API, so it cannot be used for creating new or managing existing payments. Note that the account must be set up to collect payments through either HubSpot payments or Stripe payment processing."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/crm/v3/objects/payments/batch/read": {
            "post": {
                "tags": ["Batch"],
                "summary": "Read a batch of payments by internal ID, or unique property values",
                "operationId": "post-/crm/v3/objects/payments/batch/read",
                "security": []
            }
        },
        "/crm/v3/objects/payments/{paymentsId}": {
            "get": {
                "tags": ["Basic"],
                "summary": "Read",
                "description": "Read an Object identified by `{paymentsId}`. `{paymentsId}` refers to the internal object ID by default, or optionally any unique property value as specified by the `idProperty` query param.  Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/payments/{paymentsId}",
                "security": []
            }
        },
        "/crm/v3/objects/payments": {
            "get": {
                "tags": ["Basic"],
                "summary": "List",
                "description": "Read a page of payments. Control what is returned via the `properties` query param.",
                "operationId": "get-/crm/v3/objects/payments",
                "security": []
            }
        },
        "/crm/v3/objects/payments/search": {
            "post": {
                "tags": ["Search"],
                "operationId": "post-/crm/v3/objects/payments/search",
                "security": [],
                "x-hubspot-rate-limit-exemptions": ["ten-secondly"]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.write": "Change custom object records",
                            "crm.objects.custom.read": "View custom object records",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "tickets": "Read and write tickets",
                            "e-commerce": "e-commerce",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.goals.read": "Read goals"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.deals.write": " ",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.companies.write": " ",
                            "crm.objects.companies.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.deals.read": " "
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    }
}
