{
    "openapi": "3.0.1",
    "info": {
        "title": "Commerce Payments",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "Fetch all refunded payments in the account.",
        "x-hubspot-related-documentation": [
            {
                "name": "Payments Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/commerce/payments"
            }
        ],
        "x-hubspot-introduction": "Use the payments API to fetch information about an account's payments. This is a read-only API, so it cannot be used for creating new or managing existing payments. Note that the account must be set up to collect payments through either HubSpot payments or Stripe payment processing."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/crm/v3/objects/commerce_payments/batch/read": {
            "post": {
                "tags": ["Batch"],
                "summary": "Retrieve a batch of payments",
                "description": "Retrieve a batch of payments by ID (`commercePaymentId`) or unique property value (`idProperty`). ",
                "operationId": "post-/crm/v3/objects/commerce_payments/batch/read",
                "security": [
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/commerce_payments/{commercePaymentId}": {
            "get": {
                "tags": ["Basic"],
                "summary": "Retrieve a payment",
                "description": "Retrieve a payment by its ID (`commercePaymentId`) or by a unique property (`idProperty`). You can specify what is returned using the `properties` query parameter.",
                "operationId": "get-/crm/v3/objects/commerce_payments/{commercePaymentId}",
                "security": [
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/commerce_payments": {
            "get": {
                "tags": ["Basic"],
                "summary": "Retrieve payments",
                "description": "Retrieve all payments, using query parameters to specify the information that gets returned.",
                "operationId": "get-/crm/v3/objects/commerce_payments",
                "security": [
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/commerce_payments/search": {
            "post": {
                "tags": ["Search"],
                "summary": "Search for payments",
                "description": "Search for payments by filtering on properties, searching through associations, and sorting results. Learn more about [CRM search](https://developers.hubspot.com/docs/guides/api/crm/search#make-a-search-request).",
                "operationId": "post-/crm/v3/objects/commerce_payments/search",
                "security": [
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": ["ten-secondly"]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.write": "Change custom object records",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.goals.read": "Read goals",
                            "tickets": "Read and write tickets",
                            "crm.objects.custom.read": "View custom object records",
                            "e-commerce": "e-commerce"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.companies.write": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.deals.read": " ",
                            "crm.objects.invoices.read": "Read invoices objects"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    }
}
