openapi: 3.0.0
servers:
  - url: https://api.zoom.us/v2
info:
  contact:
    email: developersupport@zoom.us
    name: Zoom Developers
    url: https://developer.zoom.us/
  description: >
    This is a generated connector for [Zoom API Version 2.0.0](https://marketplace.zoom.us/docs/api-reference/zoom-api) OpenAPI Specification.
    The Zoom API allows developers to access information from Zoom. You can use this API to build private services or public applications on the [Zoom App Marketplace](http://marketplace.zoom.us). To learn how to get your credentials and create private/public applications, read our [Authorization Guide](https://marketplace.zoom.us/docs/guides/authorization/credentials). 
    All endpoints are available via `https` and are located at `api.zoom.us/v2/`. For instance you can list all users on an account via `https://api.zoom.us/v2/users/`.
  license:
    name: MIT for OAS 2.0
    url: https://opensource.org/licenses/MIT
  termsOfService: https://zoom.us/docs/en-us/zoom_api_license_and_tou.html
  title: Zoom API
  version: 2.0.0
  x-ballerina-display:
    label: Zoom
    iconPath: "icon.png"
  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials. 
    Please create a [Zoom account](https://marketplace.zoom.us/) and obtain tokens following [this guide](https://marketplace.zoom.us/docs/guides/auth/oauth). Configure required scopes when obtaining the tokens. 
security:
  - OAuth: []
tags:
  - description: Meeting operations
    name: Meetings
  - description: Meeting operations
    name: Webinars
paths:
  "/users":
    get:
      description: >-
        Use this API to list your account's users. 

        **Scopes:** `user:read:admin` 

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      summary: List users
      operationId: listUsers
      x-ballerina-display:
        label: List Users
      security:
        - OAuth: []
      tags:
        - Users
  "/metrics/meetings":
    get:
      description: >-
        List total live or past meetings that occurred during a specified period of time. This overview will show if features such as audio, video, screen sharing, and recording were being used in the meeting. You can also see the license types of each user on your account.<br> You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months.

        **Scopes:** `dashboard_meetings:read:admin` 

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Resource-intensive`

        **Prerequisites:** Business or a higher plan.
      summary: List dashboard meetings
      operationId: listDashboardMeetings
      x-ballerina-display:
        label: List Dashboard Meetings
      security:
        - OAuth: []
      tags:
        - Dashboards
  "/metrics/meetings/{meetingId}/participants":
    get:
      description: |-
        Use this API to return a list of participants from live or past meetings. 

         If you do not provide the `type` query parameter, the default value will be set to the `live` value. This API will only return metrics for participants in a live meeting, if any exist. You can specify a monthly date range for the dashboard data using the `from` and `to` query parameters. The month should fall within the last six months. 

        **Note:** 

        This API may return empty values for participants' `user_name`, `ip_address`, `location`, and `email` responses when the account calling this API: 
        * Does **not** have a signed HIPAA business associate agreement (BAA). 
        * Is a [**legacy** HIPAA BAA account](https://marketplace.zoom.us/docs/api-reference/other-references/legacy-business-associate-agreements). 
        * Displays data for any users who are **not** part of the host's account (external users) unless they meet certain conditions. See [Email address display rules](https://marketplace.zoom.us/docs/api-reference/using-zoom-apis#email-address) for details. 

        **Scopes:** `dashboard_meetings:read:admin` <br> **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy` 

        **Prerequisites:** 
        * A Business or higher plan.
      summary: List dashboard meeting participants
      operationId: listDashboardMeetingParticipants
      x-ballerina-display:
        label: List Dashboard Meeting Participants
      security:
        - OAuth: []
      tags:
        - Dashboards
  "/users/{userId}/meetings":
    get:
      description: >-
        List all the meetings that were scheduled for a user (meeting
        host). This API only supports scheduled meetings and thus, details on
        instant meetings are not returned via this API.

        **Scopes:** `meeting:read:admin` `meeting:read`
         
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      summary: List meetings
      operationId: listMeetings
      x-ballerina-display:
        label: List Meetings
      security:
        - OAuth: []
      tags:
        - Meetings
    post:
      description: >-
        [Create a
        meeting](https://support.zoom.us/hc/en-us/articles/201362413-Scheduling-meetings)
        for a user. This API has a daily rate limit of 100 requests per day.
        Therefore, only 100 **Create a Meeting** API requests are permitted
        within a 24 hour window for a user.


        <aside>The <code>start_url</code> of a meeting is a URL using which a host or an alternative host can start a meeting. The expiration time for the <code>start_url</code> field is two hours for all regular users. 
          
        For custCreate meeting hosts( i.e., users created using the <code>custCreate</code> option via the [Create Users](https://marketplace.zoom.us/docs/api-reference/zoom-api/users/usercreate) API), the expiration time of the <code>start_url</code> field is 90 days from the generation of the <code>start_url</code>.
          
        For security reasons, the recommended way to retrieve the updated value for the <code>start_url</code> field programmatically (after expiry) is by calling the [Retrieve a Meeting API](https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meeting) and referring to the value of the <code>start_url</code> field in the response.</aside>

        Scopes: `meeting:write:admin` `meeting:write`
         
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: createMeeting
      x-ballerina-display:
        label: Create Meeting
      summary: Create a meeting
      tags:
        - Meetings
  "/meetings/{meetingId}/registrants":
    get:
      description: A host or a user with admin permission can require [registration
        for a Zoom meeting
      operationId: listMeetingRegistrants
      x-ballerina-display:
        label: List Meeting Registrants
      security:
        - OAuth: []
      summary: List meeting registrants
      tags:
        - Meetings
    post:
      description: >-
        Register a participant for a meeting. Note that there is a
        maximum limit of 4999 registrants per meeting and users will see an
        error if the capacity has reached.


        **Prerequisite:**

        * Host user type must be "Licensed".


        **Scopes:** `meeting:write:admin` `meeting:write`
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: addMeetingRegistrant
      x-ballerina-display:
        label: Add Meeting Registrant
      security:
        - OAuth: []
      summary: Add meeting registrant
      tags:
        - Meetings
  "/meetings/{meetingId}/registrants/questions":
    get:
      description: >+
        List registration questions that will be displayed to users while
        [registering for a
        meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).<br>


        **Scopes:** `meeting:read`, `meeting:read:admin`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: getMeetingRegistrantsQuestions
      x-ballerina-display:
        label: List Registrant Questions
      security:
        - OAuth: []
      summary: "List registration questions "
      tags:
        - Meetings
    patch:
      description: >+
        Update registration questions that will be displayed to users while
        [registering for a
        meeting](https://support.zoom.us/hc/en-us/articles/211579443-Registration-for-Meetings).<br><br>

        **Scopes:** `meeting:write`, `meeting:write:admin`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
         

      operationId: updateMeetingRegistrantQuestions
      x-ballerina-display:
        label: Update Registration Questions
      security:
        - OAuth: []
      summary: Update registration questions
      tags:
        - Meetings
  "/meetings/{meetingId}/registrants/status":
    put:
      description: >-
        Update a meeting registrant's status by either approving,
        cancelling or denying a registrant from joining the meeting.<br><br>

        **Scopes:** `meeting:write:admin` `meeting:write`
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: updateMeetingRegistrantStatus
      x-ballerina-display:
        label: Update Meeting Registrant's Status
      security:
        - OAuth: []
      summary: Update registrant's status
      tags:
        - Meetings
  "/meetings/{meetingId}/registrants/{registrantId}":
    delete:
      description: >-
        Delete a meeting registrant.<br><br>

        **Scopes**: `meeting:write:admin` `meeting:write`<br>
         <br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: deleteMeetingregistrant
      x-ballerina-display:
        label: Delete Meeting Registrant
      summary: Delete a meeting registrant
      tags:
        - Meetings
  "/meetings/{meetingId}":
    delete:
      description: >+
        Delete a meeting.

        **Scopes:** `meeting:write:admin` `meeting:write`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` 

      operationId: deleteMeeting
      x-ballerina-display:
        label: Delete Meeting
      security:
        - OAuth: []
      summary: Delete a meeting
      tags:
        - Meetings
    get:
      description: >+
        Retrieve the details of a meeting.

        **Scopes:** `meeting:read:admin` `meeting:read`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` 

      operationId: getMeetingById
      x-ballerina-display:
        label: Get Meeting Details
      security:
        - OAuth: []
      summary: Get a meeting
      tags:
        - Meetings
    patch:
      description: >+
        Update the details of a meeting.<br>This API has a rate limit of
        100 requests per day. Therefore, a meeting can only be updated for a
        maximum of 100 times within a 24 hour window.<br>

        **Scopes:** `meeting:write:admin` `meeting:write`<br>
         
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: updateMeeting
      x-ballerina-display:
        label: Update Meeting
      security:
        - OAuth: []
      summary: Update a meeting
      tags:
        - Meetings  
  "/meetings/{meetingId}/status":
    put:
      description: >-
        Update the status of a meeting.<br><br>

        **Scopes:** `meeting:write:admin` `meeting:write`
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
      operationId: updateMeetingStatus
      x-ballerina-display:
        label: Update Meeting Status
      security:
        - OAuth: []
      summary: Update meeting status
      tags:
        - Meetings
  "/past_meetings/{meetingId}/instances":
    get:
      description: >-
        Get a list of ended meeting instances<br><br>

        **Scopes:** `meeting:read:admin` `meeting:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` 
      operationId: listPastMeetings
      x-ballerina-display:
        label: List Past Meetings
      security:
        - OAuth: []
      summary: List ended meeting instances
      tags:
        - Meetings
  "/past_meetings/{meetingId}/polls":
    get:
      description: >-
        [Polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)
        allow the meeting host to survey attendees. Use this API to list poll
        results of a meeting.<br><br>


        **Scopes**: `meeting:read:admin`, `meeting:read`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` <br>
        **Prerequisites**:<br>

        * Host user type must be **Pro**.

        * Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.
      operationId: listPastMeetingPolls
      x-ballerina-display:
        label: List Meeting Polls
      security:
        - OAuth: []
      summary: List past meeting's poll results
      tags:
        - Meetings
  "/past_meetings/{meetingUUID}":
    get:
      description: >-
        Get details on a past meeting. <br><br>

        **Scopes:** `meeting:read:admin` `meeting:read`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`
        > **Note**: Please double encode your UUID when using this API if the UUID begins with a '/'or contains '//' in it.
      operationId: getPastMeetingDetails
      x-ballerina-display:
        label: Get Past Meeting Details
      security:
        - OAuth: []
      summary: Get past meeting details
      tags:
        - Meetings
  "/past_meetings/{meetingUUID}/participants":
    get:
      description: >
        Retrieve information on participants from a past meeting. <br><br>

        **Scopes:** `meeting:read:admin` `meeting:read`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
        **Prerequisites:**<br>

        * Paid account on a Pro or higher plan.


        <br> <br>  **Note**: Please double encode your UUID when using this API if the UUID begins with a '/'or contains '//' in it.
      operationId: listPastMeetingParticipants
      x-ballerina-display:
        label: List Past Meeting Participants
      security:
        - OAuth: []
      summary: List past meeting participants
      tags:
        - Meetings
  "/meetings/{meetingId}/polls":
    get:
      description: >-
        Polls allow the meeting host to survey attendees. Use this API to
        list
        [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)
        of a meeting.<br><br>


        **Scopes**: `meeting:read:admin` `meeting:read`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites**:<br>

        * Host user type must be **Pro** or higher plan.

        * Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.
      operationId: getMeetingPolls
      x-ballerina-display:
        label: Get Meeting Polls
      security:
        - OAuth: []
      summary: List meeting polls
      tags:
        - Meetings
    post:
      description: >-
        Polls allow the meeting host to survey attendees. Use this API to
        create a
        [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)
        for a meeting.<br><br>


        **Scopes**: `meeting:write:admin` `meeting:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites**:<br>

        * Host user type must be **Pro** or higher plan.

        * Polling feature must be enabled in the host's account.

        * Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.
      operationId: createMeetingPoll
      x-ballerina-display:
        label: Create Meeting Poll
      security:
        - OAuth: []
      summary: Create a meeting poll
      tags:
        - Meetings
  "/meetings/{meetingId}/polls/{pollId}":
    delete:
      description: >-
        Polls allow the meeting host to survey attendees. Use this API to
        delete a meeting
        [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).<br>

        **Scopes**: `meeting:write:admin` `meeting:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` <br>
        **Prerequisites**:<br>

        * Host user type must be **Pro**.

        * Polling feature should be enabled in the host's account.

        * Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.
      operationId: deleteMeetingPoll
      x-ballerina-display:
        label: Delete Meeting Poll
      security:
        - OAuth: []
      summary: Delete a meeting poll
      tags:
        - Meetings
    get:
      description: >+
        Polls allow the meeting host to survey attendees. Use this API to
        get information about a specific meeting
        [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings).<br><br>

        **Scopes**: `meeting:read:admin` `meeting:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`


      operationId: getMeetingPoll
      x-ballerina-display:
        label: Get Meeting Poll
      security:
        - OAuth: []
      summary: Get a meeting poll
      tags:
        - Meetings
    put:
      description: >+
        Polls allow the meeting host to survey attendees. Use this API to
        update information of a specific meeting
        [poll](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)<br><br>

        **Scopes**: `meeting:write:admin` `meeting:write`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light` 

      operationId: updateMeetingPoll
      x-ballerina-display:
        label: Update Meeting Poll
      security:
        - OAuth: []
      summary: Update a meeting poll
      tags:
        - Meetings
  "/meetings/{meetingId}/batch_polls":
    post:
      description: >-
        Polls allow the meeting host to survey attendees. Use this API to
        create batch
        [polls](https://support.zoom.us/hc/en-us/articles/213756303-Polling-for-Meetings)
        for a meeting.<br><br>


        **Scopes**: `meeting:write:admin` `meeting:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`<br>
        **Prerequisites**:<br>

        * Host user type must be **Pro** or higher plan.

        * Polling feature must be enabled in the host's account.

        * Meeting must be a scheduled meeting. Instant meetings do not have polling features enabled.
      operationId: createBatchPolls
      x-ballerina-display:
        label: Create Batch Polls
      summary: Perform batch poll creation
      tags:
        - Meetings
  "/meetings/{meetingId}/invitation":
    get:
      description: >+
        Retrieve the meeting invite note that was sent for a specific
        meeting.<br><br>

        **Scopes:** `meeting:read:admin` `meeting:read`<br>

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`

      operationId: getMeetingInvitation
      x-ballerina-display:
        label: Get Meeting Invitation
      security:
        - OAuth: []
      summary: Get meeting invitation
      tags:
        - Meetings
  "/meetings/{meetingId}/livestream":
    get:
      description: >+
        Zoom allows users to [live stream a
        meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)
        to a custom platform. Use this API to get a meeting's live stream
        configuration details such as Stream URL, Stream Key and Page
        URL.<br><br>

        **Prerequisites:**<br>

        * Meeting host must be a licensed user with a Pro or higher plan.<br>

        * Live streaming details must have been [configured](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service#h_01589a6f-a40a-4e18-a448-cb746e52ebc5) for the meeting.<br><br>

        **Scopes:** `meeting:read:admin` `meeting:read`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`



      operationId: getLiveStreamDetails
      x-ballerina-display:
        label: Get Live Stream Details
      summary: Get live stream details
      tags:
        - Meetings
    patch:
      description: >+
        Zoom allows users to [live stream a
        meeting](https://support.zoom.us/hc/en-us/articles/115001777826-Live-Streaming-Meetings-or-Webinars-Using-a-Custom-Service)
        to a custom platform. Use this API to update a meeting's live stream
        information.<br><br>

        **Prerequisites:**<br>

        * Meeting host must have a Pro license.<br>

        **Scopes:** `meeting:write:admin` `meeting:write`<br>
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Light`


      operationId: updateMeetingLiveStream
      x-ballerina-display:
        label: Update Meeting Live Stream
      security:
        - OAuth: []
      summary: Update a live stream
      tags:
        - Meetings
  "/webinars/{webinarId}/registrants":
    get:
      description: >+
        Zoom users with a [Webinar Plan](https://zoom.us/webinar) have
        access to creating and managing Webinars. Webinar allows a host to
        broadcast a Zoom meeting to up to 10,000 attendees. Scheduling a
        [Webinar with
        registration](https://support.zoom.us/hc/en-us/articles/204619915-Scheduling-a-Webinar-with-Registration)
        requires your registrants to complete a brief form before receiving the
        link to join the Webinar. 

        Use this API to list all the users that have registered for a webinar.  

        **Prerequisites:**

        * Pro or higher plan with a Webinar Add-on. 

        **Scopes:** `webinar:read:admin` `webinar:read`  
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` 

      operationId: listWebinarRegistrants
      x-ballerina-display:
        label: List Webinar Meeting Registrants
      security:
        - OAuth: []
      summary: List webinar registrants
      tags:
        - Webinars
  "/past_webinars/{webinarId}/participants":
    get:
      description: >+
        Use this API to list all the participants who attended a webinar
        hosted in the past.  


        **Prerequisites:**

        * Pro or higher plan with a Webinar Add-on. 

        **Scopes:** `webinar:read:admin` `webinar:read`  

         

        **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium` 



      operationId: listWebinarParticipants
      x-ballerina-display:
        label: List Webinar Participants
      summary: List webinar participants
      tags:
        - Webinars
  "/past_webinars/{WebinarUUID}/absentees":
    get:
      description: >-
        List absentees of a webinar.  

        **Scopes:** `webinar:read:admin` `webinar:read` 
         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Heavy`
      operationId: listWebinarAbsentees
      x-ballerina-display:
        label: List Webinar Absentees
      security:
        - OAuth: []
      summary: List webinar absentees
      tags:
        - Webinars
  "/users/{userId}/meeting_templates":
    get:
      description: >
        Use this API to list [meeting
        templates](https://support.zoom.us/hc/en-us/articles/360036559151-Meeting-templates)
        that are available to be used by a user.


        **Scope:** `meeting:read` or `meeting:read:admin`

         **[Rate Limit Label](https://marketplace.zoom.us/docs/api-reference/rate-limits#rate-limits):** `Medium`
      operationId: listMeetingTemplates
      x-ballerina-display:
        label: List Meeting Templates
      summary: List meeting templates
      tags:
        - Meetings
components:
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT  
    OAuth:
      flows:
        authorizationCode:
          authorizationUrl: https://zoom.us/oauth/authorize
          scopes: {}
          tokenUrl: https://zoom.us/oauth/token
      type: oauth2