openapi: 3.0.1
info:
  x-ballerina-display:
    label: HubSpot CRM Schema
    iconPath: "icon.png"
  title: Schemas
  description: 'This is a generated connector from [HubSpot](https://www.hubspot.com/) OpenAPI specification. 
  
    The CRM uses schemas to define how custom objects should store and represent information in the HubSpot CRM. Schemas define details about an object''s type, properties, and associations. The schema can be uniquely identified by its **object type ID**.'
  version: v3
  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials.
  
    Create a [HubSpot account](https://www.hubspot.com/) and obtain OAuth tokens following [this guide](https://developers.hubspot.com/docs/api/working-with-oauth4).
servers:
  - url: 'https://api.hubapi.com'
tags:
  - name: Core
  - name: Public_Object_Schemas
paths:
  /crm/v3/schemas:
    get:
      tags:
        - Core
      summary: Get all schemas
      description: Returns all object schemas that have been defined for your account.
      operationId: getAll
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.custom.read
            - crm.schemas.custom.read
    post:
      tags:
        - Core
      summary: Create a new schema
      description: 'Define a new object schema, along with custom properties and associations. The entire object schema, including its object type ID, properties, and associations will be returned in the response.'
      operationId: create
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.custom.write
  '/crm/v3/schemas/{objectType}':
    get:
      tags:
        - Core
      summary: Get an existing schema
      description: Returns an existing object schema.
      operationId: 'getById'
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.custom.read
            - crm.schemas.custom.read
    delete:
      tags:
        - Core
      summary: Delete a schema
      description: Deletes a schema. Any existing records of this schema must be deleted **first**. Otherwise this call will fail.
      operationId: 'archive'
      security:
        - hapikey: []
    patch:
      tags:
        - Core
      summary: Update a schema
      description: Update the details for an existing object schema.
      operationId: 'update'
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.custom.write
  '/crm/v3/schemas/{objectType}/associations':
    post:
      tags:
        - Core
      summary: Create an association
      description: Defines a new association between the primary schema's object type and other object types.
      operationId: 'associations_createAssociation'
      security:
        - hapikey: []
        - oauth2:
            - crm.objects.custom.write
  '/crm/v3/schemas/{objectType}/associations/{associationIdentifier}':
    delete:
      tags:
        - Core
      summary: Remove an association
      description: Removes an existing association from a schema.
      operationId: 'associations/archiveAssociation'
      security:
        - hapikey: []
  '/crm/v3/schemas/{objectType}/purge':
    delete:
      tags:
        - Public_Object_Schemas
      operationId: 'purge'
      summary: Purge schemas
      deprecated: true
      security:
        - hapikey: []
components:
  securitySchemes:
    # hapikey:
    #   type: apiKey
    #   name: hapikey
    #   in: query
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://app.hubspot.com/oauth/authorize'
          tokenUrl: 'https://api.hubapi.com/oauth/v1/token'
          scopes:
            crm.schemas.custom.read: View custom object definitions
            crm.objects.custom.read: View custom object records
            crm.objects.custom.write: Change custom object records
x-hubspot-available-client-libraries:
  - PHP
  - Node
  - Python
  - Ruby
