[package]
license = ["Apache-2.0"]
keywords = ["Type/Connector", "Vendor/SAP", "Area/ERP & Business Operations", "Business Management/ERP", "Cost/Paid", "Name/SAP S/4HANA Watch List Screening - Hits"]
org = "ballerinax"
name = "saps4hana.wls.screeninghits"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/saps4hana.wls.screeninghits"
version = "1.4.2"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
