openapi: 3.0.1
info:
  title: Properties
  description: All HubSpot objects store data in default and custom properties. These endpoints provide access to read and modify object properties in HubSpot.
  version: v3
servers:
  - url: 'https://api.hubapi.com/'
tags:
  - name: Core
  - name: Batch
  - name: Groups
paths:
  '/crm/v3/properties/{objectType}':
    get:
      tags:
        - Core
      summary: Read all properties
      description: Read all existing properties for the specified object type and HubSpot account.
      operationId: 'getAll'
      security:
        - oauth2:
            - e-commerce
            - tickets
            - crm.schemas.contacts.read
            - contacts
            - media_bridge.read
            - crm.schemas.custom.read
            - timeline
            - crm.schemas.deals.read
            - crm.schemas.companies.read
        - hapikey: []
    post:
      tags:
        - Core
      summary: Create a property
      description: Create and return a copy of a new property for the specified object type.
      operationId: 'create'
      security:
        - hapikey: []
        - oauth2:
            - e-commerce
            - tickets
            - contacts
            - crm.schemas.companies.write
            - crm.schemas.deals.write
            - crm.schemas.contacts.write
  '/crm/v3/properties/{objectType}/batch/archive':
    post:
      tags:
        - Batch
      summary: Archive a batch of properties
      description: 'Archive a provided list of properties. This method will return a 204 No Content response on success regardless of the initial state of the property (e.g. active, already archived, non-existent).'
      operationId: 'batch/archive_archive'
      security:
        - hapikey: []
        - oauth2:
            - e-commerce
            - tickets
            - contacts
            - crm.schemas.companies.write
            - crm.schemas.deals.write
            - crm.schemas.contacts.write
  '/crm/v3/properties/{objectType}/batch/create':
    post:
      tags:
        - Batch
      summary: Create a batch of properties
      description: Create a batch of properties using the same rules as when creating an individual property.
      operationId: 'batch/create_create'
      security:
        - hapikey: []
        - oauth2:
            - e-commerce
            - tickets
            - contacts
            - crm.schemas.companies.write
            - crm.schemas.deals.write
            - crm.schemas.contacts.write
  '/crm/v3/properties/{objectType}/batch/read':
    post:
      tags:
        - Batch
      summary: Read a batch of properties
      description: Read a provided list of properties.
      operationId: 'batch/read_read'
      security:
        - oauth2:
            - e-commerce
            - tickets
            - crm.schemas.contacts.read
            - contacts
            - media_bridge.read
            - crm.schemas.custom.read
            - timeline
            - crm.schemas.deals.read
            - crm.schemas.companies.read
        - hapikey: []
  '/crm/v3/properties/{objectType}/groups':
    get:
      tags:
        - Groups
      summary: Read all property groups
      description: Read all existing property groups for the specified object type and HubSpot account.
      operationId: 'groups_getAll'
      security:
        - oauth2:
            - e-commerce
            - tickets
            - crm.schemas.contacts.read
            - contacts
            - media_bridge.read
            - crm.schemas.custom.read
            - timeline
            - crm.schemas.deals.read
            - crm.schemas.companies.read
        - hapikey: []
    post:
      tags:
        - Groups
      summary: Create a property group
      description: Create and return a copy of a new property group.
      operationId: 'groups_create'
      security:
        - hapikey: []
        - oauth2:
            - e-commerce
            - tickets
            - contacts
            - crm.schemas.companies.write
            - crm.schemas.deals.write
            - crm.schemas.contacts.write
  '/crm/v3/properties/{objectType}/groups/{groupName}':
    get:
      tags:
        - Groups
      summary: Read a property group
      description: 'Read a property group identified by {groupName}.'
      operationId: 'groups/getByName'
      security:
        - oauth2:
            - e-commerce
            - tickets
            - crm.schemas.contacts.read
            - contacts
            - media_bridge.read
            - crm.schemas.custom.read
            - timeline
            - crm.schemas.deals.read
            - crm.schemas.companies.read
        - hapikey: []
    delete:
      tags:
        - Groups
      summary: Archive a property group
      description: 'Move a property group identified by {groupName} to the recycling bin.'
      operationId: 'groups/archive'
      security:
        - hapikey: []
        - oauth2:
            - e-commerce
            - tickets
            - contacts
            - crm.schemas.companies.write
            - crm.schemas.deals.write
            - crm.schemas.contacts.write
    patch:
      tags:
        - Groups
      summary: Update a property group
      description: 'Perform a partial update of a property group identified by {groupName}. Provided fields will be overwritten.'
      operationId: 'groups/update'
      security:
        - hapikey: []
        - oauth2:
            - e-commerce
            - tickets
            - contacts
            - crm.schemas.companies.write
            - crm.schemas.deals.write
            - crm.schemas.contacts.write
  '/crm/v3/properties/{objectType}/{propertyName}':
    get:
      tags:
        - Core
      summary: Read a property
      description: 'Read a property identified by {propertyName}.'
      operationId: 'property_getByName'
      security:
        - oauth2:
            - e-commerce
            - tickets
            - crm.schemas.contacts.read
            - contacts
            - media_bridge.read
            - crm.schemas.custom.read
            - timeline
            - crm.schemas.deals.read
            - crm.schemas.companies.read
        - hapikey: []
    delete:
      tags:
        - Core
      summary: Archive a property
      description: 'Move a property identified by {propertyName} to the recycling bin.'
      operationId: 'property_archive'
      security:
        - hapikey: []
        - oauth2:
            - e-commerce
            - tickets
            - contacts
            - crm.schemas.companies.write
            - crm.schemas.deals.write
            - crm.schemas.contacts.write
    patch:
      tags:
        - Core
      summary: Update a property
      description: 'Perform a partial update of a property identified by {propertyName}. Provided fields will be overwritten.'
      operationId: 'property_update'
      security:
        - hapikey: []
        - oauth2:
            - e-commerce
            - tickets
            - contacts
            - crm.schemas.companies.write
            - crm.schemas.deals.write
            - crm.schemas.contacts.write
components:
  securitySchemes:
    # hapikey:
    #   type: apiKey
    #   name: hapikey
    #   in: query
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://app.hubspot.com/oauth/authorize'
          tokenUrl: 'https://api.hubapi.com/oauth/v1/token'
          scopes:
            crm.schemas.deals.read: ' '
            media_bridge.read: Read media and media events
            crm.schemas.companies.read: ' '
            timeline: Create timeline events
            tickets: Read and write tickets
            crm.schemas.contacts.read: ' '
            crm.schemas.custom.read: View custom object definitions
            contacts: Read from and write to my Contacts
            e-commerce: e-commerce
            crm.schemas.companies.write: ' '
            crm.schemas.deals.write: ' '
            crm.schemas.contacts.write: ' '
x-hubspot-available-client-libraries:
  - PHP
  - Node
  - Python
  - Ruby
