{
    "openapi": "3.0.1",
    "info": {
        "title": "Contacts",
        "description": "",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "Retrieve a contact by ID to bring that contact data into your external system.",
        "x-hubspot-related-documentation": [
            {
                "name": "Contacts Guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/objects/contacts"
            }
        ],
        "x-hubspot-introduction": "Use the contacts API to create and manage contacts."
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        },
        {
            "name": "Basic"
        },
        {
            "name": "Search"
        }
    ],
    "paths": {
        "/crm/v3/objects/contacts/batch/read": {
            "post": {
                "tags": ["Batch"],
                "summary": "Retrieve a batch of contacts",
                "description": "Retrieve a batch of contacts by ID (`contactId`) or unique property value (`idProperty`). ",
                "operationId": "post-/crm/v3/objects/contacts/batch/read_read",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    }
                ]
            }
        },
        "/crm/v3/objects/contacts/{contactId}": {
            "get": {
                "tags": ["Basic"],
                "summary": "Retrieve a contact",
                "description": "Retrieve a contact by its ID (`contactId`) or by a unique property (`idProperty`). You can specify what is returned using the `properties` query parameter.",
                "operationId": "get-/crm/v3/objects/contacts/{contactId}_getById",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    }
                ]
            },
            "delete": {
                "tags": ["Basic"],
                "summary": "Archive a contact",
                "description": "Delete a contact by ID. Deleted contacts can be restored within 90 days of deletion. Learn more about the [data impacted by contact deletions](https://knowledge.hubspot.com/privacy-and-consent/understand-restorable-and-permanent-contact-deletions) and how to [restore archived records](https://knowledge.hubspot.com/records/restore-deleted-records).",
                "operationId": "delete-/crm/v3/objects/contacts/{contactId}_archive",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            },
            "patch": {
                "tags": ["Basic"],
                "summary": "Update a contact",
                "description": "Update a contact by ID (`contactId`) or unique property value (`idProperty`). Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
                "operationId": "patch-/crm/v3/objects/contacts/{contactId}_update",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/contacts/merge": {
            "post": {
                "tags": ["Basic"],
                "summary": "Merge two contacts",
                "description": "Merge two contact records. Learn more about [merging records](https://knowledge.hubspot.com/records/merge-records). ",
                "operationId": "post-/crm/v3/objects/contacts/merge_merge",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/contacts/batch/archive": {
            "post": {
                "tags": ["Batch"],
                "summary": "Archive a batch of contacts",
                "description": "Archive a batch of contacts by ID. Archived contacts can be restored within 90 days of deletion. Learn more about the [data impacted by contact deletions](https://knowledge.hubspot.com/privacy-and-consent/understand-restorable-and-permanent-contact-deletions) and how to [restore archived records](https://knowledge.hubspot.com/records/restore-deleted-records).",
                "operationId": "post-/crm/v3/objects/contacts/batch/archive_archive",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/contacts/batch/create": {
            "post": {
                "tags": ["Batch"],
                "summary": "Create a batch of contacts",
                "description": "Create a batch of contacts. The `inputs` array can contain a `properties` object to define property values for each record, along with an `associations` array to define [associations](https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4) with other CRM records.",
                "operationId": "post-/crm/v3/objects/contacts/batch/create_create",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/contacts/batch/update": {
            "post": {
                "tags": ["Batch"],
                "summary": "Update a batch of contacts",
                "description": "Update a batch of contacts by ID (`contactId`) or unique property value (`idProperty`). Provided property values will be overwritten. Read-only and non-existent properties will result in an error. Properties values can be cleared by passing an empty string.",
                "operationId": "post-/crm/v3/objects/contacts/batch/update_update",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/contacts/gdpr-delete": {
            "post": {
                "tags": ["Basic"],
                "summary": "Permanently delete a contact (GDPR-compliant)",
                "description": "Permanently delete a contact and all associated content to follow GDPR. Use optional property `idProperty` set to `email` to identify contact by email address. If email address is not found, the email address will be added to a blocklist and prevent it from being used in the future. Learn more about [permanently deleting contacts](https://knowledge.hubspot.com/privacy-and-consent/how-do-i-perform-a-gdpr-delete-in-hubspot).",
                "operationId": "post-/crm/v3/objects/contacts/gdpr-delete_purge",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/contacts": {
            "get": {
                "tags": ["Basic"],
                "summary": "Retrieve contacts",
                "description": "Retrieve all contacts, using query parameters to specify the information that gets returned.",
                "operationId": "get-/crm/v3/objects/contacts_getPage",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    }
                ]
            },
            "post": {
                "tags": ["Basic"],
                "summary": "Create a contact",
                "description": "Create a single contact. Include a `properties` object to define [property values](https://developers.hubspot.com/docs/guides/api/crm/properties) for the contact, along with an `associations` array to define [associations](https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4) with other CRM records.",
                "operationId": "post-/crm/v3/objects/contacts_create",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/contacts/batch/upsert": {
            "post": {
                "tags": ["Batch"],
                "summary": "Create or update a batch of contacts",
                "description": "Create a batch of contacts. The `inputs` array can contain a `properties` object to define property values for each record, along with an `associations` array to define [associations](https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v4) with other CRM records.",
                "operationId": "post-/crm/v3/objects/contacts/batch/upsert_upsert",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    }
                ]
            }
        },
        "/crm/v3/objects/contacts/search": {
            "post": {
                "tags": ["Search"],
                "summary": "Search for contacts",
                "description": "Search for contacts by filtering on properties, searching through associations, and sorting results. Learn more about [CRM search](https://developers.hubspot.com/docs/guides/api/crm/search#make-a-search-request).",
                "operationId": "post-/crm/v3/objects/contacts/search_doSearch",
                "security": [
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    }
                ],
                "x-hubspot-rate-limit-exemptions": ["ten-secondly"]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.read": "View custom object records",
                            "tickets": "Read and write tickets",
                            "crm.objects.goals.read": "Read goals",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.custom.write": "Change custom object records",
                            "e-commerce": "e-commerce"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.quotes.write": "Quotes",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.deals.write": " ",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.deals.read": " ",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.invoices.write": "Write invoices",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.companies.read": " ",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.companies.write": " ",
                            "crm.objects.leads.write": "Modify lead objects"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    },
    "x-hubspot-available-client-libraries": ["PHP", "Node", "Ruby", "Python"],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}
