[package]
license = ["Apache-2.0"]
keywords = ["Type/Connector", "Productivity/Task Management", "Cost/Free", "Vendor/Google", "Area/Productivity & Collaboration"]
org = "ballerinax"
name = "googleapis.tasks"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/googleapis.tasks"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
