openapi: 3.0.1
info:
  x-ballerina-display:
    label: Hubspot Crm Pipeline
    iconPath: "resources/hubspot.crm.pipeline.svg"
  title: CRM Pipelines
  description: |-
    This is a generated connector from [HubSpot](https://www.hubspot.com/) OpenAPI specification.
    
    Pipelines represent distinct stages in a workflow, like closing a deal or servicing a support ticket. These endpoints provide access to read and modify pipelines in HubSpot. Pipelines support `deals` and `tickets` object types.

    When calling endpoints that take pipelineId as a parameter, that ID must correspond to an existing, un-archived pipeline. Otherwise the request will fail with a `404 Not Found` response.

  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials.
  
    Create a [HubSpot account](https://www.hubspot.com/) and obtain OAuth tokens following [this guide](https://developers.hubspot.com/docs/api/working-with-oauth4).
  version: v3
servers:
  - url: 'https://api.hubapi.com'
tags:
  - name: Pipelines
  - name: Pipeline Stages
paths:
  '/crm/v3/pipelines/{objectType}':
    get:
      tags:
        - Pipelines
      summary: Retrieve all pipelines
      description: 'Return all pipelines for the object type specified by `{objectType}`.'
      operationId: 'getAll'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
    post:
      tags:
        - Pipelines
      summary: Create a pipeline
      description: 'Create a new pipeline with the provided property values. The entire pipeline object, including its unique ID, will be returned in the response.'
      operationId: 'create'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
  '/crm/v3/pipelines/{objectType}/{pipelineId}':
    get:
      tags:
        - Pipelines
      summary: Return a pipeline by ID
      description: 'Return a single pipeline object identified by its unique `{pipelineId}`.'
      operationId: 'getById'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
    put:
      tags:
        - Pipelines
      summary: Replace a pipeline
      description: Replace all the properties of an existing pipeline with the values provided. This will overwrite any existing pipeline stages. The updated pipeline will be returned in the response.
      operationId: 'replace'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
    delete:
      tags:
        - Pipelines
      summary: Archive a pipeline
      description: 'Archive the pipeline identified by `{pipelineId}`.'
      operationId: 'archive'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
    patch:
      tags:
        - Pipelines
      summary: Update a pipeline
      description: 'Perform a partial update of the pipeline identified by `{pipelineId}`. The updated pipeline will be returned in the response.'
      operationId: 'update'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
  '/crm/v3/pipelines/{objectType}/{pipelineId}/stages':
    get:
      tags:
        - Pipeline Stages
      summary: Return all stages of a pipeline
      description: 'Return all the stages associated with the pipeline identified by `{pipelineId}`.'
      operationId: 'stage_getAll'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
    post:
      tags:
        - Pipeline Stages
      summary: Create a pipeline stage
      description: 'Create a new stage associated with the pipeline identified by `{pipelineId}`. The entire stage object, including its unique ID, will be returned in the response.'
      operationId: 'stage_create'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
  '/crm/v3/pipelines/{objectType}/{pipelineId}/stages/{stageId}':
    get:
      tags:
        - Pipeline Stages
      summary: Return a pipeline stage by ID
      description: 'Return the stage identified by `{stageId}` associated with the pipeline identified by `{pipelineId}`.'
      operationId: 'stage_getById'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
    put:
      tags:
        - Pipeline Stages
      summary: Replace a pipeline stage
      description: Replace all the properties of an existing pipeline stage with the values provided. The updated stage will be returned in the response.
      operationId: 'stage_replace'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
    delete:
      tags:
        - Pipeline Stages
      summary: Archive a pipeline stage
      description: 'Archive the pipeline stage identified by `{stageId}` associated with the pipeline identified by `{pipelineId}`.'
      operationId: 'stage_archive'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
    patch:
      tags:
        - Pipeline Stages
      summary: Update a pipeline stage
      description: 'Perform a partial update of the pipeline stage identified by `{stageId}` associated with the pipeline identified by `{pipelineId}`. Any properties not included in this update will keep their existing values. The updated stage will be returned in the response.'
      operationId: 'stage_update'
      security:
        - oauth2:
            - crm.objects.contacts.read
            - crm.schemas.contacts.read
            - contacts
            - tickets
        - hapikey: []
components:
  securitySchemes:
    # hapikey:
    #   type: apiKey
    #   name: hapikey
    #   in: query
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'https://app.hubspot.com/oauth/authorize'
          tokenUrl: 'https://api.hubapi.com/oauth/v1/token'
          scopes:
            crm.schemas.contacts.read: ' '
            contacts: Read from and write to my Contacts
            crm.objects.contacts.read: ' '
            tickets: Read and write tickets
x-hubspot-available-client-libraries:
  - PHP
  - Node
  - Python
  - Ruby
