// Copyright (c) 2021 WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
//
// WSO2 Inc. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

# A Company resource represents a company in the service. A company is the entity that owns job postings, that is, the hiring entity responsible for employing applicants for the job position.
public type Company record {
    # The URI to employer's career site or careers page on the employer's web site, for example, "https://careers.google.com".
    string careerSiteUri?;
    # Derived details about the company.
    CompanyDerivedInfo derivedInfo?;
    # Required. The display name of the company, for example, "Google LLC".
    string displayName?;
    # Equal Employment Opportunity legal disclaimer text to be associated with all jobs, and typically to be displayed in all roles. The maximum number of allowed characters is 500.
    string eeoText?;
    # Required. Client side company identifier, used to uniquely identify the company. The maximum number of allowed characters is 255.
    string externalId?;
    # The street address of the company's main headquarters, which may be different from the job location. The service attempts to geolocate the provided address, and populates a more specific location wherever possible in DerivedInfo.headquarters_location.
    string headquartersAddress?;
    # Set to true if it is the hiring agency that post jobs for other employers. Defaults to false if not provided.
    boolean hiringAgency?;
    # A URI that hosts the employer's company logo.
    string imageUri?;
    # A list of keys of filterable Job.custom_attributes, whose corresponding `string_values` are used in keyword searches. Jobs with `string_values` under these specified field keys are returned if any of the values match the search keyword. Custom field values with parenthesis, brackets and special symbols are not searchable as-is, and those keyword queries must be surrounded by quotes.
    string[] keywordSearchableJobCustomAttributes?;
    # Required during company update. The resource name for a company. This is generated by the service when a company is created. The format is "projects/{project_id}/tenants/{tenant_id}/companies/{company_id}", for example, "projects/foo/tenants/bar/companies/baz".
    string name?;
    # The employer's company size.
    string size?;
    # Output only. Indicates whether a company is flagged to be suspended from public availability by the service when job content appears suspicious, abusive, or spammy.
    boolean suspended?;
    # The URI representing the company's primary web site or home page, for example, "https://www.google.com". The maximum number of allowed characters is 255.
    string websiteUri?;
};

# The List tenants response object.
public type ListTenantsResponse record {
    # Additional information returned to client, such as debugging information.
    ResponseMetadata metadata?;
    # A token to retrieve the next page of results.
    string nextPageToken?;
    # Tenants for the current client.
    Tenant[] tenants?;
};

# Metadata used for long running operations returned by CTS batch APIs. It's used to replace google.longrunning.Operation.metadata.
public type BatchOperationMetadata record {
    # The time when the batch operation is created.
    string createTime?;
    # The time when the batch operation is finished and google.longrunning.Operation.done is set to `true`.
    string endTime?;
    # Count of failed item(s) inside an operation.
    int failureCount?;
    # The state of a long running operation.
    string state?;
    # More detailed information about operation state.
    string stateDescription?;
    # Count of successful item(s) inside an operation.
    int successCount?;
    # Count of total item(s) inside an operation.
    int totalCount?;
    # The time when the batch operation status is updated. The metadata and the update_time is refreshed every minute otherwise cached data is returned.
    string updateTime?;
};

# Histogram result that matches HistogramQuery specified in searches.
public type HistogramQueryResult record {
    # A map from the values of the facet associated with distinct values to the number of matching entries with corresponding value. The key format is: * (for string histogram) string values stored in the field. * (for named numeric bucket) name specified in bucket() function, like for `bucket(0, MAX, "non-negative")`, the key will be `non-negative`. * (for anonymous numeric bucket) range formatted as `-`, for example, `0-1000`, `MIN-0`, and `0-MAX`.
    record {} histogram?;
    # Requested histogram expression.
    string histogramQuery?;
};

# Derived details about the job posting.
public type JobDerivedInfo record {
    # Job categories derived from Job.title and Job.description.
    string[] jobCategories?;
    # Structured locations of the job, resolved from Job.addresses. locations are exactly matched to Job.addresses in the same order.
    Location[] locations?;
};

# Device information collected from the job seeker, candidate, or other entity conducting the job search. Providing this information improves the quality of the search results across devices.
public type DeviceInfo record {
    # Type of the device.
    string deviceType?;
    # A device-specific ID. The ID must be a unique identifier that distinguishes the device from other devices.
    string id?;
};

# Parameters needed for commute search.
public type CommuteFilter record {
    # If `true`, jobs without street level addresses may also be returned. For city level addresses, the city center is used. For state and coarser level addresses, text matching is used. If this field is set to `false` or isn't specified, only jobs that include street level addresses will be returned by commute search.
    boolean allowImpreciseAddresses?;
    # Required. The method of transportation to calculate the commute time for.
    string commuteMethod?;
    # Represents a time of day. The date and time zone are either not significant or are specified elsewhere. An API may choose to allow leap seconds. Related types are google.type.Date and `google.protobuf.Timestamp`.
    TimeOfDay departureTime?;
    # Specifies the traffic density to use when calculating commute time.
    string roadTraffic?;
    # An object that represents a latitude/longitude pair. This is expressed as a pair of doubles to represent degrees latitude and degrees longitude. Unless specified otherwise, this object must conform to the WGS84 standard. Values must be within normalized ranges.
    LatLng startCoordinates?;
    # Required. The maximum travel time in seconds. The maximum allowed value is `3600s` (one hour). Format is `123s`.
    string travelDuration?;
};

# Filter on job compensation type and amount.
public type CompensationFilter record {
    # If set to true, jobs with unspecified compensation range fields are included.
    boolean includeJobsWithUnspecifiedCompensationRange?;
    # Compensation range.
    CompensationRange range?;
    # Required. Type of filter.
    string 'type?;
    # Required. Specify desired `base compensation entry's` CompensationInfo.CompensationUnit.
    string[] units?;
};

# An object that represents a latitude/longitude pair. This is expressed as a pair of doubles to represent degrees latitude and degrees longitude. Unless specified otherwise, this object must conform to the WGS84 standard. Values must be within normalized ranges.
public type LatLng record {
    # The latitude in degrees. It must be in the range [-90.0, +90.0].
    float latitude?;
    # The longitude in degrees. It must be in the range [-180.0, +180.0].
    float longitude?;
};

# Custom ranking information for SearchJobsRequest.
public type CustomRankingInfo record {
    # Required. Controls over how important the score of CustomRankingInfo.ranking_expression gets applied to job's final ranking position. An error is thrown if not specified.
    string importanceLevel?;
    # Required. Controls over how job documents get ranked on top of existing relevance score (determined by API algorithm). A combination of the ranking expression and relevance score is used to determine job's final ranking position. The syntax for this expression is a subset of Google SQL syntax. Supported operators are: +, -, *, /, where the left and right side of the operator is either a numeric Job.custom_attributes key, integer/double value or an expression that can be evaluated to a number. Parenthesis are supported to adjust calculation precedence. The expression must be < 100 characters in length. The expression is considered invalid for a job if the expression references custom attributes that are not populated on the job or if the expression results in a divide by zero. If an expression is invalid for a job, that job is demoted to the end of the results. Sample ranking expression (year + 25) * 0.25 - (freshness / 0.5)
    string rankingExpression?;
};

# A Job resource represents a job posting (also referred to as a "job listing" or "job requisition"). A job belongs to a Company, which is the hiring entity responsible for the job.
public type Job record {
    # Strongly recommended for the best service experience. Location(s) where the employer is looking to hire for this job posting. Specifying the full street address(es) of the hiring location enables better API results, especially job searches by commute time. At most 50 locations are allowed for best search performance. If a job has more locations, it is suggested to split it into multiple jobs with unique requisition_ids (e.g. 'ReqA' becomes 'ReqA-1', 'ReqA-2', and so on.) as multiple jobs with the same company, language_code and requisition_id are not allowed. If the original requisition_id must be preserved, a custom field should be used for storage. It is also suggested to group the locations that close to each other in the same job for better search experience. Jobs with multiple addresses must have their addresses with the same LocationType to allow location filtering to work properly. (For example, a Job with addresses "1600 Amphitheatre Parkway, Mountain View, CA, USA" and "London, UK" may not have location filters applied correctly at search time since the first is a LocationType.STREET_ADDRESS and the second is a LocationType.LOCALITY.) If a job needs to have multiple addresses, it is suggested to split it into multiple jobs with same LocationTypes. The maximum number of allowed characters is 500.
    string[] addresses?;
    # Application related details of a job posting.
    ApplicationInfo applicationInfo?;
    # Required. The resource name of the company listing the job. The format is "projects/{project_id}/tenants/{tenant_id}/companies/{company_id}". For example, "projects/foo/tenants/bar/companies/baz".
    string company?;
    # Output only. Display name of the company listing the job.
    string companyDisplayName?;
    # Job compensation details.
    CompensationInfo compensationInfo?;
    # A map of fields to hold both filterable and non-filterable custom job attributes that are not covered by the provided structured fields. The keys of the map are strings up to 64 bytes and must match the pattern: a-zA-Z*. For example, key0LikeThis or KEY_1_LIKE_THIS. At most 100 filterable and at most 100 unfilterable keys are supported. For filterable `string_values`, across all keys at most 200 values are allowed, with each string no more than 255 characters. For unfilterable `string_values`, the maximum total size of `string_values` across all keys is 50KB.
    record {} customAttributes?;
    # The desired education degrees for the job, such as Bachelors, Masters.
    string[] degreeTypes?;
    # The department or functional area within the company with the open position. The maximum number of allowed characters is 255.
    string department?;
    # Derived details about the job posting.
    JobDerivedInfo derivedInfo?;
    # Required. The description of the job, which typically includes a multi-paragraph description of the company and related information. Separate fields are provided on the job object for responsibilities, qualifications, and other job characteristics. Use of these separate job fields is recommended. This field accepts and sanitizes HTML input, and also accepts bold, italic, ordered list, and unordered list markup tags. The maximum number of allowed characters is 100,000.
    string description?;
    # The employment type(s) of a job, for example, full time or part time.
    string[] employmentTypes?;
    # A description of bonus, commission, and other compensation incentives associated with the job not including salary or pay. The maximum number of allowed characters is 10,000.
    string incentives?;
    # The benefits included with the job.
    string[] jobBenefits?;
    # The end timestamp of the job. Typically this field is used for contracting engagements. Invalid timestamps are ignored.
    string jobEndTime?;
    # The experience level associated with the job, such as "Entry Level".
    string jobLevel?;
    # The start timestamp of the job in UTC time zone. Typically this field is used for contracting engagements. Invalid timestamps are ignored.
    string jobStartTime?;
    # The language of the posting. This field is distinct from any requirements for fluency that are associated with the job. Language codes must be in BCP-47 format, such as "en-US" or "sr-Latn". For more information, see [Tags for Identifying Languages](https://tools.ietf.org/html/bcp47){: class="external" target="_blank" }. If this field is unspecified and Job.description is present, detected language code based on Job.description is assigned, otherwise defaults to 'en_US'.
    string languageCode?;
    # Required during job update. The resource name for the job. This is generated by the service when a job is created. The format is "projects/{project_id}/tenants/{tenant_id}/jobs/{job_id}". For example, "projects/foo/tenants/bar/jobs/baz". Use of this field in job queries and API calls is preferred over the use of requisition_id since this value is unique.
    string name?;
    # Output only. The timestamp when this job posting was created.
    string postingCreateTime?;
    # Strongly recommended for the best service experience. The expiration timestamp of the job. After this timestamp, the job is marked as expired, and it no longer appears in search results. The expired job can't be listed by the ListJobs API, but it can be retrieved with the GetJob API or updated with the UpdateJob API or deleted with the DeleteJob API. An expired job can be updated and opened again by using a future expiration timestamp. Updating an expired job fails if there is another existing open job with same company, language_code and requisition_id. The expired jobs are retained in our system for 90 days. However, the overall expired job count cannot exceed 3 times the maximum number of open jobs over previous 7 days. If this threshold is exceeded, expired jobs are cleaned out in order of earliest expire time. Expired jobs are no longer accessible after they are cleaned out. Invalid timestamps are ignored, and treated as expire time not provided. If the timestamp is before the instant request is made, the job is treated as expired immediately on creation. This kind of job can not be updated. And when creating a job with past timestamp, the posting_publish_time must be set before posting_expire_time. The purpose of this feature is to allow other objects, such as Application, to refer a job that didn't exist in the system prior to becoming expired. If you want to modify a job that was expired on creation, delete it and create a new one. If this value isn't provided at the time of job creation or is invalid, the job posting expires after 30 days from the job's creation time. For example, if the job was created on 2017/01/01 13:00AM UTC with an unspecified expiration date, the job expires after 2017/01/31 13:00AM UTC. If this value isn't provided on job update, it depends on the field masks set by UpdateJobRequest.update_mask. If the field masks include job_end_time, or the masks are empty meaning that every field is updated, the job posting expires after 30 days from the job's last update time. Otherwise the expiration date isn't updated.
    string postingExpireTime?;
    # The timestamp this job posting was most recently published. The default value is the time the request arrives at the server. Invalid timestamps are ignored.
    string postingPublishTime?;
    # The job PostingRegion (for example, state, country) throughout which the job is available. If this field is set, a LocationFilter in a search query within the job region finds this job posting if an exact location match isn't specified. If this field is set to PostingRegion.NATION or PostingRegion.ADMINISTRATIVE_AREA, setting job Job.addresses to the same location level as this field is strongly recommended.
    string postingRegion?;
    # Output only. The timestamp when this job posting was last updated.
    string postingUpdateTime?;
    # Options for job processing.
    ProcessingOptions processingOptions?;
    # A promotion value of the job, as determined by the client. The value determines the sort order of the jobs returned when searching for jobs using the featured jobs search call, with higher promotional values being returned first and ties being resolved by relevance sort. Only the jobs with a promotionValue >0 are returned in a FEATURED_JOB_SEARCH. Default value is 0, and negative values are treated as 0.
    int promotionValue?;
    # A description of the qualifications required to perform the job. The use of this field is recommended as an alternative to using the more general description field. This field accepts and sanitizes HTML input, and also accepts bold, italic, ordered list, and unordered list markup tags. The maximum number of allowed characters is 10,000.
    string qualifications?;
    # Required. The requisition ID, also referred to as the posting ID, is assigned by the client to identify a job. This field is intended to be used by clients for client identification and tracking of postings. A job isn't allowed to be created if there is another job with the same company, language_code and requisition_id. The maximum number of allowed characters is 255.
    string requisitionId?;
    # A description of job responsibilities. The use of this field is recommended as an alternative to using the more general description field. This field accepts and sanitizes HTML input, and also accepts bold, italic, ordered list, and unordered list markup tags. The maximum number of allowed characters is 10,000.
    string responsibilities?;
    # Required. The title of the job, such as "Software Engineer" The maximum number of allowed characters is 500.
    string title?;
    # Deprecated. The job is only visible to the owner. The visibility of the job. Defaults to Visibility.ACCOUNT_ONLY if not specified.
    string visibility?;
};

# The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).
public type Status record {
    # The status code, which should be an enum value of google.rpc.Code.
    int code?;
    # A list of messages that carry the error details. There is a common set of message types for APIs to use.
    record {}[] details?;
    # A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client.
    string message?;
};

# Job compensation details.
public type CompensationInfo record {
    # Compensation range.
    CompensationRange annualizedBaseCompensationRange?;
    # Compensation range.
    CompensationRange annualizedTotalCompensationRange?;
    # Job compensation information. At most one entry can be of type CompensationInfo.CompensationType.BASE, which is referred as **base compensation entry** for the job.
    CompensationEntry[] entries?;
};

# Mutation result of a job from a batch operation.
public type JobResult record {
    # A Job resource represents a job posting (also referred to as a "job listing" or "job requisition"). A job belongs to a Company, which is the hiring entity responsible for the job.
    Job job?;
    # The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).
    Status status?;
};

# Response for SearchJob method.
public type SearchJobsResponse record {
    # If query broadening is enabled, we may append additional results from the broadened query. This number indicates how many of the jobs returned in the jobs field are from the broadened query. These results are always at the end of the jobs list. In particular, a value of 0, or if the field isn't set, all the jobs in the jobs list are from the original (without broadening) query. If this field is non-zero, subsequent requests with offset after this result set should contain all broadened results.
    int broadenedQueryJobsCount?;
    # The histogram results that match with specified SearchJobsRequest.histogram_queries.
    HistogramQueryResult[] histogramQueryResults?;
    # The location filters that the service applied to the specified query. If any filters are lat-lng based, the Location.location_type is Location.LocationType.LOCATION_TYPE_UNSPECIFIED.
    Location[] locationFilters?;
    # The Job entities that match the specified SearchJobsRequest.
    MatchingJob[] matchingJobs?;
    # Additional information returned to client, such as debugging information.
    ResponseMetadata metadata?;
    # The token that specifies the starting position of the next page of results. This field is empty if there are no more results.
    string nextPageToken?;
    # Spell check result.
    SpellingCorrection spellCorrection?;
    # Number of jobs that match the specified query. Note: This size is precise only if the total is less than 100,000.
    int totalSize?;
};

# Derived details about the company.
public type CompanyDerivedInfo record {
    # A resource that represents a location with full geographic information.
    Location headquartersLocation?;
};

# List jobs response.
public type ListJobsResponse record {
    # The Jobs for a given company. The maximum number of items returned is based on the limit field provided in the request.
    Job[] jobs?;
    # Additional information returned to client, such as debugging information.
    ResponseMetadata metadata?;
    # A token to retrieve the next page of results.
    string nextPageToken?;
};

# The result of JobService.BatchDeleteJobs. It's used to replace google.longrunning.Operation.response in case of success.
public type BatchDeleteJobsResponse record {
    # List of job mutation results from a batch delete operation. It can change until operation status is FINISHED, FAILED or CANCELLED.
    JobResult[] jobResults?;
};

# Meta information related to the job searcher or entity conducting the job search. This information is used to improve the performance of the service.
public type RequestMetadata record {
    # Only set when any of domain, session_id and user_id isn't available for some reason. It is highly recommended not to set this field and provide accurate domain, session_id and user_id for the best service experience.
    boolean allowMissingIds?;
    # Device information collected from the job seeker, candidate, or other entity conducting the job search. Providing this information improves the quality of the search results across devices.
    DeviceInfo deviceInfo?;
    # Required if allow_missing_ids is unset or `false`. The client-defined scope or source of the service call, which typically is the domain on which the service has been implemented and is currently being run. For example, if the service is being run by client *Foo, Inc.*, on job board www.foo.com and career site www.bar.com, then this field is set to "foo.com" for use on the job board, and "bar.com" for use on the career site. Note that any improvements to the model for a particular tenant site rely on this field being set correctly to a unique domain. The maximum number of allowed characters is 255.
    string domain?;
    # Required if allow_missing_ids is unset or `false`. A unique session identification string. A session is defined as the duration of an end user's interaction with the service over a certain period. Obfuscate this field for privacy concerns before providing it to the service. Note that any improvements to the model for a particular tenant site rely on this field being set correctly to a unique session ID. The maximum number of allowed characters is 255.
    string sessionId?;
    # Required if allow_missing_ids is unset or `false`. A unique user identification string, as determined by the client. To have the strongest positive impact on search quality make sure the client-level is unique. Obfuscate this field for privacy concerns before providing it to the service. Note that any improvements to the model for a particular tenant site rely on this field being set correctly to a unique user ID. The maximum number of allowed characters is 255.
    string userId?;
};

# Next ID: 15
public type NamespacedDebugInput record {
    # Set of experiment names to be absolutely forced. These experiments will be forced without evaluating the conditions.
    string[] absolutelyForcedExpNames?;
    # Set of experiment tags to be absolutely forced. The experiments with these tags will be forced without evaluating the conditions.
    string[] absolutelyForcedExpTags?;
    # Set of experiment ids to be absolutely forced. These ids will be forced without evaluating the conditions.
    int[] absolutelyForcedExps?;
    # Set of experiment names to be conditionally forced. These experiments will be forced only if their conditions and their parent domain's conditions are true.
    string[] conditionallyForcedExpNames?;
    # Set of experiment tags to be conditionally forced. The experiments with these tags will be forced only if their conditions and their parent domain's conditions are true.
    string[] conditionallyForcedExpTags?;
    # Set of experiment ids to be conditionally forced. These ids will be forced only if their conditions and their parent domain's conditions are true.
    int[] conditionallyForcedExps?;
    # If true, disable automatic enrollment selection (at all diversion points). Automatic enrollment selection means experiment selection process based on the experiment's automatic enrollment condition. This does not disable selection of forced experiments.
    boolean disableAutomaticEnrollmentSelection?;
    # Set of experiment names to be disabled. If an experiment is disabled, it is never selected nor forced. If an aggregate experiment is disabled, its partitions are disabled together. If an experiment with an enrollment is disabled, the enrollment is disabled together. If a name corresponds to a domain, the domain itself and all descendant experiments and domains are disabled together.
    string[] disableExpNames?;
    # Set of experiment tags to be disabled. All experiments that are tagged with one or more of these tags are disabled. If an experiment is disabled, it is never selected nor forced. If an aggregate experiment is disabled, its partitions are disabled together. If an experiment with an enrollment is disabled, the enrollment is disabled together.
    string[] disableExpTags?;
    # Set of experiment ids to be disabled. If an experiment is disabled, it is never selected nor forced. If an aggregate experiment is disabled, its partitions are disabled together. If an experiment with an enrollment is disabled, the enrollment is disabled together. If an ID corresponds to a domain, the domain itself and all descendant experiments and domains are disabled together.
    int[] disableExps?;
    # If true, disable manual enrollment selection (at all diversion points). Manual enrollment selection means experiment selection process based on the request's manual enrollment states (a.k.a. opt-in experiments). This does not disable selection of forced experiments.
    boolean disableManualEnrollmentSelection?;
    # If true, disable organic experiment selection (at all diversion points). Organic selection means experiment selection process based on traffic allocation and diversion condition evaluation. This does not disable selection of forced experiments. This is useful in cases when it is not known whether experiment selection behavior is responsible for a error or breakage. Disabling organic selection may help to isolate the cause of a given problem.
    boolean disableOrganicSelection?;
    # Flags to force in a particular experiment state. Map from flag name to flag value.
    record {} forcedFlags?;
    # Rollouts to force in a particular experiment state. Map from rollout name to rollout value.
    record {} forcedRollouts?;
};

# Represents a postal address, e.g. for postal delivery or payments addresses. Given a postal address, a postal service can deliver items to a premise, P.O. Box or similar. It is not intended to model geographical locations (roads, towns, mountains). In typical usage an address would be created via user input or from importing existing data, depending on the type of process. Advice on address input / editing: - Use an i18n-ready address widget such as https://github.com/google/libaddressinput) - Users should not be presented with UI elements for input or editing of fields outside countries where that field is used. For more guidance on how to use this schema, please see: https://support.google.com/business/answer/6397478
public type PostalAddress record {
    # Unstructured address lines describing the lower levels of an address. Because values in address_lines do not have type information and may sometimes contain multiple values in a single field (e.g. "Austin, TX"), it is important that the line order is clear. The order of address lines should be "envelope order" for the country/region of the address. In places where this can vary (e.g. Japan), address_language is used to make it explicit (e.g. "ja" for large-to-small ordering and "ja-Latn" or "en" for small-to-large). This way, the most specific line of an address can be selected based on the language. The minimum permitted structural representation of an address consists of a region_code with all remaining information placed in the address_lines. It would be possible to format such an address very approximately without geocoding, but no semantic reasoning could be made about any of the address components until it was at least partially resolved. Creating an address only containing a region_code and address_lines, and then geocoding is the recommended way to handle completely unstructured addresses (as opposed to guessing which parts of the address should be localities or administrative areas).
    string[] addressLines?;
    # Optional. Highest administrative subdivision which is used for postal addresses of a country or region. For example, this can be a state, a province, an oblast, or a prefecture. Specifically, for Spain this is the province and not the autonomous community (e.g. "Barcelona" and not "Catalonia"). Many countries don't use an administrative area in postal addresses. E.g. in Switzerland this should be left unpopulated.
    string administrativeArea?;
    # Optional. BCP-47 language code of the contents of this address (if known). This is often the UI language of the input form or is expected to match one of the languages used in the address' country/region, or their transliterated equivalents. This can affect formatting in certain countries, but is not critical to the correctness of the data and will never affect any validation or other non-formatting related operations. If this value is not known, it should be omitted (rather than specifying a possibly incorrect default). Examples: "zh-Hant", "ja", "ja-Latn", "en".
    string languageCode?;
    # Optional. Generally refers to the city/town portion of the address. Examples: US city, IT comune, UK post town. In regions of the world where localities are not well defined or do not fit into this structure well, leave locality empty and use address_lines.
    string locality?;
    # Optional. The name of the organization at the address.
    string organization?;
    # Optional. Postal code of the address. Not all countries use or require postal codes to be present, but where they are used, they may trigger additional validation with other parts of the address (e.g. state/zip validation in the U.S.A.).
    string postalCode?;
    # Optional. The recipient at the address. This field may, under certain circumstances, contain multiline information. For example, it might contain "care of" information.
    string[] recipients?;
    # Required. CLDR region code of the country/region of the address. This is never inferred and it is up to the user to ensure the value is correct. See http://cldr.unicode.org/ and http://www.unicode.org/cldr/charts/30/supplemental/territory_information.html for details. Example: "CH" for Switzerland.
    string regionCode?;
    # The schema revision of the `PostalAddress`. This must be set to 0, which is the latest revision. All new revisions **must** be backward compatible with old revisions.
    int revision?;
    # Optional. Additional, country-specific, sorting code. This is not used in most regions. Where it is used, the value is either a string like "CEDEX", optionally followed by a number (e.g. "CEDEX 7"), or just a number alone, representing the "sector code" (Jamaica), "delivery area indicator" (Malawi) or "post office indicator" (e.g. Côte d'Ivoire).
    string sortingCode?;
    # Optional. Sublocality of the address. For example, this can be neighborhoods, boroughs, districts.
    string sublocality?;
};

# Compensation range.
public type CompensationRange record {
    # Represents an amount of money with its currency type.
    Money maxCompensation?;
    # Represents an amount of money with its currency type.
    Money minCompensation?;
};

# The result of JobService.BatchCreateJobs. It's used to replace google.longrunning.Operation.response in case of success.
public type BatchCreateJobsResponse record {
    # List of job mutation results from a batch create operation. It can change until operation status is FINISHED, FAILED or CANCELLED.
    JobResult[] jobResults?;
};

# The List companies response object.
public type ListCompaniesResponse record {
    # Companies for the current client.
    Company[] companies?;
    # Additional information returned to client, such as debugging information.
    ResponseMetadata metadata?;
    # A token to retrieve the next page of results.
    string nextPageToken?;
};

# A compensation entry that represents one component of compensation, such as base pay, bonus, or other compensation type. Annualization: One compensation entry can be annualized if - it contains valid amount or range. - and its expected_units_per_year is set or can be derived. Its annualized range is determined as (amount or range) times expected_units_per_year.
public type CompensationEntry record {
    # Represents an amount of money with its currency type.
    Money amount?;
    # Compensation description. For example, could indicate equity terms or provide additional context to an estimated bonus.
    string description?;
    # Expected number of units paid each year. If not specified, when Job.employment_types is FULLTIME, a default value is inferred based on unit. Default values: - HOURLY: 2080 - DAILY: 260 - WEEKLY: 52 - MONTHLY: 12 - ANNUAL: 1
    float expectedUnitsPerYear?;
    # Compensation range.
    CompensationRange range?;
    # Compensation type. Default is CompensationType.COMPENSATION_TYPE_UNSPECIFIED.
    string 'type?;
    # Frequency of the specified amount. Default is CompensationUnit.COMPENSATION_UNIT_UNSPECIFIED.
    string unit?;
};

# Additional information returned to client, such as debugging information.
public type ResponseMetadata record {
    # A unique id associated with this call. This id is logged for tracking purposes.
    string requestId?;
};

# The Request body of the `SearchJobs` call.
public type SearchJobsRequest record {
    # Custom ranking information for SearchJobsRequest.
    CustomRankingInfo customRankingInfo?;
    # Controls whether to disable exact keyword match on Job.title, Job.description, Job.company_display_name, Job.addresses, Job.qualifications. When disable keyword match is turned off, a keyword match returns jobs that do not match given category filters when there are matching keywords. For example, for the query "program manager," a result is returned even if the job posting has the title "software developer," which doesn't fall into "program manager" ontology, but does have "program manager" appearing in its description. For queries like "cloud" that don't contain title or location specific ontology, jobs with "cloud" keyword matches are returned regardless of this flag's value. Use Company.keyword_searchable_job_custom_attributes if company-specific globally matched custom field/attribute string values are needed. Enabling keyword match improves recall of subsequent search requests. Defaults to false.
    boolean disableKeywordMatch?;
    # Controls whether highly similar jobs are returned next to each other in the search results. Jobs are identified as highly similar based on their titles, job categories, and locations. Highly similar results are clustered so that only one representative job of the cluster is displayed to the job seeker higher up in the results, with the other jobs being displayed lower down in the results. Defaults to DiversificationLevel.SIMPLE if no value is specified.
    string diversificationLevel?;
    # Controls whether to broaden the search when it produces sparse results. Broadened queries append results to the end of the matching results list. Defaults to false.
    boolean enableBroadening?;
    # An expression specifies a histogram request against matching jobs. Expression syntax is an aggregation function call with histogram facets and other options. Available aggregation function calls are: * `count(string_histogram_facet)`: Count the number of matching entities, for each distinct attribute value. * `count(numeric_histogram_facet, list of buckets)`: Count the number of matching entities within each bucket. Data types: * Histogram facet: facet names with format a-zA-Z+. * String: string like "any string with backslash escape for quote(\")." * Number: whole number and floating point number like 10, -1 and -0.01. * List: list of elements with comma(,) separator surrounded by square brackets, for example, [1, 2, 3] and ["one", "two", "three"]. Built-in constants: * MIN (minimum number similar to java Double.MIN_VALUE) * MAX (maximum number similar to java Double.MAX_VALUE) Built-in functions: * bucket(start, end[, label]): bucket built-in function creates a bucket with range of start, end). Note that the end is exclusive, for example, bucket(1, MAX, "positive number") or bucket(1, 10). Job histogram facets: * company_display_name: histogram by [Job.company_display_name. * employment_type: histogram by Job.employment_types, for example, "FULL_TIME", "PART_TIME". * company_size: histogram by CompanySize, for example, "SMALL", "MEDIUM", "BIG". * publish_time_in_day: histogram by the Job.posting_publish_time in days. Must specify list of numeric buckets in spec. * publish_time_in_month: histogram by the Job.posting_publish_time in months. Must specify list of numeric buckets in spec. * publish_time_in_year: histogram by the Job.posting_publish_time in years. Must specify list of numeric buckets in spec. * degree_types: histogram by the Job.degree_types, for example, "Bachelors", "Masters". * job_level: histogram by the Job.job_level, for example, "Entry Level". * country: histogram by the country code of jobs, for example, "US", "FR". * admin1: histogram by the admin1 code of jobs, which is a global placeholder referring to the state, province, or the particular term a country uses to define the geographic structure below the country level, for example, "CA", "IL". * city: histogram by a combination of the "city name, admin1 code". For example, "Mountain View, CA", "New York, NY". * admin1_country: histogram by a combination of the "admin1 code, country", for example, "CA, US", "IL, US". * city_coordinate: histogram by the city center's GPS coordinates (latitude and longitude), for example, 37.4038522,-122.0987765. Since the coordinates of a city center can change, customers may need to refresh them periodically. * locale: histogram by the Job.language_code, for example, "en-US", "fr-FR". * language: histogram by the language subtag of the Job.language_code, for example, "en", "fr". * category: histogram by the JobCategory, for example, "COMPUTER_AND_IT", "HEALTHCARE". * base_compensation_unit: histogram by the CompensationInfo.CompensationUnit of base salary, for example, "WEEKLY", "MONTHLY". * base_compensation: histogram by the base salary. Must specify list of numeric buckets to group results by. * annualized_base_compensation: histogram by the base annualized salary. Must specify list of numeric buckets to group results by. * annualized_total_compensation: histogram by the total annualized salary. Must specify list of numeric buckets to group results by. * string_custom_attribute: histogram by string Job.custom_attributes. Values can be accessed via square bracket notations like string_custom_attribute["key1"]. * numeric_custom_attribute: histogram by numeric Job.custom_attributes. Values can be accessed via square bracket notations like numeric_custom_attribute["key1"]. Must specify list of numeric buckets to group results by. Example expressions: * `count(admin1)` * `count(base_compensation, [bucket(1000, 10000), bucket(10000, 100000), bucket(100000, MAX)])` * `count(string_custom_attribute["some-string-custom-attribute"])` * `count(numeric_custom_attribute["some-numeric-custom-attribute"], [bucket(MIN, 0, "negative"), bucket(0, MAX, "non-negative")])`
    HistogramQuery[] histogramQueries?;
    # The query required to perform a search query.
    JobQuery jobQuery?;
    # The desired job attributes returned for jobs in the search response. Defaults to JobView.JOB_VIEW_SMALL if no value is specified.
    string jobView?;
    # A limit on the number of jobs returned in the search results. Increasing this value above the default value of 10 can increase search response time. The value can be between 1 and 100.
    int maxPageSize?;
    # An integer that specifies the current offset (that is, starting result location, amongst the jobs deemed by the API as relevant) in search results. This field is only considered if page_token is unset. The maximum allowed value is 5000. Otherwise an error is thrown. For example, 0 means to return results starting from the first matching job, and 10 means to return from the 11th job. This can be used for pagination, (for example, pageSize = 10 and offset = 10 means to return from the second page).
    int offset?;
    # The criteria determining how search results are sorted. Default is `"relevance desc"`. Supported options are: * `"relevance desc"`: By relevance descending, as determined by the API algorithms. Relevance thresholding of query results is only available with this ordering. * `"posting_publish_time desc"`: By Job.posting_publish_time descending. * `"posting_update_time desc"`: By Job.posting_update_time descending. * `"title"`: By Job.title ascending. * `"title desc"`: By Job.title descending. * `"annualized_base_compensation"`: By job's CompensationInfo.annualized_base_compensation_range ascending. Jobs whose annualized base compensation is unspecified are put at the end of search results. * `"annualized_base_compensation desc"`: By job's CompensationInfo.annualized_base_compensation_range descending. Jobs whose annualized base compensation is unspecified are put at the end of search results. * `"annualized_total_compensation"`: By job's CompensationInfo.annualized_total_compensation_range ascending. Jobs whose annualized base compensation is unspecified are put at the end of search results. * `"annualized_total_compensation desc"`: By job's CompensationInfo.annualized_total_compensation_range descending. Jobs whose annualized base compensation is unspecified are put at the end of search results. * `"custom_ranking desc"`: By the relevance score adjusted to the SearchJobsRequest.CustomRankingInfo.ranking_expression with weight factor assigned by SearchJobsRequest.CustomRankingInfo.importance_level in descending order. * Location sorting: Use the special syntax to order jobs by distance: `"distance_from('Hawaii')"`: Order by distance from Hawaii. `"distance_from(19.89, 155.5)"`: Order by distance from a coordinate. `"distance_from('Hawaii'), distance_from('Puerto Rico')"`: Order by multiple locations. See details below. `"distance_from('Hawaii'), distance_from(19.89, 155.5)"`: Order by multiple locations. See details below. The string can have a maximum of 256 characters. When multiple distance centers are provided, a job that is close to any of the distance centers would have a high rank. When a job has multiple locations, the job location closest to one of the distance centers will be used. Jobs that don't have locations will be ranked at the bottom. Distance is calculated with a precision of 11.3 meters (37.4 feet). Diversification strategy is still applied unless explicitly disabled in diversification_level.
    string orderBy?;
    # The token specifying the current offset within search results. See SearchJobsResponse.next_page_token for an explanation of how to obtain the next set of query results.
    string pageToken?;
    # Meta information related to the job searcher or entity conducting the job search. This information is used to improve the performance of the service.
    RequestMetadata requestMetadata?;
    # Mode of a search. Defaults to SearchMode.JOB_SEARCH.
    string searchMode?;
};

# Request to delete a batch of jobs.
public type BatchDeleteJobsRequest record {
    # The names of the jobs to delete. The format is "projects/{project_id}/tenants/{tenant_id}/jobs/{job_id}". For example, "projects/foo/tenants/bar/jobs/baz". A maximum of 200 jobs can be deleted in a batch.
    string[] names?;
};

# Custom attribute values that are either filterable or non-filterable.
public type CustomAttribute record {
    # If the `filterable` flag is true, the custom field values may be used for custom attribute filters JobQuery.custom_attribute_filter. If false, these values may not be used for custom attribute filters. Default is false.
    boolean filterable?;
    # If the `keyword_searchable` flag is true, the keywords in custom fields are searchable by keyword match. If false, the values are not searchable by keyword match. Default is false.
    boolean keywordSearchable?;
    # Exactly one of string_values or long_values must be specified. This field is used to perform number range search. (`EQ`, `GT`, `GE`, `LE`, `LT`) over filterable `long_value`. Currently at most 1 long_values is supported.
    string[] longValues?;
    # Exactly one of string_values or long_values must be specified. This field is used to perform a string match (`CASE_SENSITIVE_MATCH` or `CASE_INSENSITIVE_MATCH`) search. For filterable `string_value`s, a maximum total number of 200 values is allowed, with each `string_value` has a byte size of no more than 500B. For unfilterable `string_values`, the maximum total byte size of unfilterable `string_values` is 50KB. Empty string isn't allowed.
    string[] stringValues?;
};

# Job entry with metadata inside SearchJobsResponse.
public type MatchingJob record {
    # Commute details related to this job.
    CommuteInfo commuteInfo?;
    # A Job resource represents a job posting (also referred to as a "job listing" or "job requisition"). A job belongs to a Company, which is the hiring entity responsible for the job.
    Job job?;
    # A summary of the job with core information that's displayed on the search results listing page.
    string jobSummary?;
    # Contains snippets of text from the Job.title field most closely matching a search query's keywords, if available. The matching query keywords are enclosed in HTML bold tags.
    string jobTitleSnippet?;
    # Contains snippets of text from the Job.description and similar fields that most closely match a search query's keywords, if available. All HTML tags in the original fields are stripped when returned in this field, and matching query keywords are enclosed in HTML bold tags.
    string searchTextSnippet?;
};

# Application related details of a job posting.
public type ApplicationInfo record {
    # Use this field to specify email address(es) to which resumes or applications can be sent. The maximum number of allowed characters for each entry is 255.
    string[] emails?;
    # Use this field to provide instructions, such as "Mail your application to ...", that a candidate can follow to apply for the job. This field accepts and sanitizes HTML input, and also accepts bold, italic, ordered list, and unordered list markup tags. The maximum number of allowed characters is 3,000.
    string instruction?;
    # Use this URI field to direct an applicant to a website, for example to link to an online application form. The maximum number of allowed characters for each entry is 2,000.
    string[] uris?;
};

# The result of JobService.BatchUpdateJobs. It's used to replace google.longrunning.Operation.response in case of success.
public type BatchUpdateJobsResponse record {
    # List of job mutation results from a batch update operation. It can change until operation status is FINISHED, FAILED or CANCELLED.
    JobResult[] jobResults?;
};

# Message representing input to a Mendel server for debug forcing. See go/mendel-debug-forcing for more details. Next ID: 2
public type MendelDebugInput record {
    # When a request spans multiple servers, a MendelDebugInput may travel with the request and take effect in all the servers. This field is a map of namespaces to NamespacedMendelDebugInput protos. In a single server, up to two NamespacedMendelDebugInput protos are applied: 1. NamespacedMendelDebugInput with the global namespace (key == ""). 2. NamespacedMendelDebugInput with the server's namespace. When both NamespacedMendelDebugInput protos are present, they are merged. See go/mendel-debug-forcing for more details.
    record {} namespacedDebugInput?;
};

# This resource represents a long-running operation that is the result of a network API call.
public type Operation record {
    # If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available.
    boolean done?;
    # The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors).
    Status _error?;
    # Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.
    record {} metadata?;
    # The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.
    string name?;
    # The normal response of the operation in case of success. If the original method returns no data on success, such as `Delete`, the response is `google.protobuf.Empty`. If the original method is standard `Get`/`Create`/`Update`, the response should be the resource. For other methods, the response should have the type XxxResponse, where `Xxx` is the original method name. For example, if the original method name is TakeSnapshot(), the inferred response type is `TakeSnapshotResponse`.
    record {} response?;
};

# An event issued when an end user interacts with the application that implements Cloud Talent Solution. Providing this information improves the quality of results for the API clients, enabling the service to perform optimally. The number of events sent must be consistent with other calls, such as job searches, issued to the service by the client.
public type ClientEvent record {
    # Required. The timestamp of the event.
    string createTime?;
    # Required. A unique identifier, generated by the client application.
    string eventId?;
    # Notes about the event provided by recruiters or other users, for example, feedback on why a job was bookmarked.
    string eventNotes?;
    # An event issued when a job seeker interacts with the application that implements Cloud Talent Solution.
    JobEvent jobEvent?;
    # Strongly recommended for the best service experience. A unique ID generated in the API responses. It can be found in ResponseMetadata.request_id.
    string requestId?;
};

# Spell check result.
public type SpellingCorrection record {
    # Indicates if the query was corrected by the spell checker.
    boolean corrected?;
    # Corrected output with html tags to highlight the corrected words. Corrected words are called out with the "*...*" html tags. For example, the user input query is "software enginear", where the second word, "enginear," is incorrect. It should be "engineer". When spelling correction is enabled, this value is "software *engineer*".
    string correctedHtml?;
    # Correction output consisting of the corrected keyword string.
    string correctedText?;
};

# Represents an amount of money with its currency type.
public type Money record {
    # The three-letter currency code defined in ISO 4217.
    string currencyCode?;
    # Number of nano (10^-9) units of the amount. The value must be between -999,999,999 and +999,999,999 inclusive. If `units` is positive, `nanos` must be positive or zero. If `units` is zero, `nanos` can be positive, zero, or negative. If `units` is negative, `nanos` must be negative or zero. For example $-1.75 is represented as `units`=-1 and `nanos`=-750,000,000.
    int nanos?;
    # The whole units of the amount. For example if `currencyCode` is `"USD"`, then 1 unit is one US dollar.
    string units?;
};

# A generic empty message that you can re-use to avoid defining duplicated empty messages in your APIs. A typical example is to use it as the request or the response type of an API method. For instance: service Foo { rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty); } The JSON representation for `Empty` is empty JSON object `{}`.
public type Empty record {
};

# A Tenant resource represents a tenant in the service. A tenant is a group or entity that shares common access with specific privileges for resources like jobs. Customer may create multiple tenants to provide data isolation for different groups.
public type Tenant record {
    # Required. Client side tenant identifier, used to uniquely identify the tenant. The maximum number of allowed characters is 255.
    string externalId?;
    # Required during tenant update. The resource name for a tenant. This is generated by the service when a tenant is created. The format is "projects/{project_id}/tenants/{tenant_id}", for example, "projects/foo/tenants/bar".
    string name?;
};

# An event issued when a job seeker interacts with the application that implements Cloud Talent Solution.
public type JobEvent record {
    # Required. The job name(s) associated with this event. For example, if this is an impression event, this field contains the identifiers of all jobs shown to the job seeker. If this was a view event, this field contains the identifier of the viewed job. The format is "projects/{project_id}/tenants/{tenant_id}/jobs/{job_id}", for example, "projects/foo/tenants/bar/jobs/baz".
    string[] jobs?;
    # Required. The type of the event (see JobEventType).
    string 'type?;
};

# Commute details related to this job.
public type CommuteInfo record {
    # A resource that represents a location with full geographic information.
    Location jobLocation?;
    # The number of seconds required to travel to the job location from the query location. A duration of 0 seconds indicates that the job isn't reachable within the requested duration, but was returned as part of an expanded query.
    string travelDuration?;
};

# Resource that represents completion results.
public type CompletionResult record {
    # The URI of the company image for COMPANY_NAME.
    string imageUri?;
    # The suggestion for the query.
    string suggestion?;
    # The completion topic.
    string 'type?;
};

# Represents a time of day. The date and time zone are either not significant or are specified elsewhere. An API may choose to allow leap seconds. Related types are google.type.Date and `google.protobuf.Timestamp`.
public type TimeOfDay record {
    # Hours of day in 24 hour format. Should be from 0 to 23. An API may choose to allow the value "24:00:00" for scenarios like business closing time.
    int hours?;
    # Minutes of hour of day. Must be from 0 to 59.
    int minutes?;
    # Fractions of seconds in nanoseconds. Must be from 0 to 999,999,999.
    int nanos?;
    # Seconds of minutes of the time. Must normally be from 0 to 59. An API may allow the value 60 if it allows leap-seconds.
    int seconds?;
};

# Response of auto-complete query.
public type CompleteQueryResponse record {
    # Results of the matching job/company candidates.
    CompletionResult[] completionResults?;
    # Additional information returned to client, such as debugging information.
    ResponseMetadata metadata?;
};

# Options for job processing.
public type ProcessingOptions record {
    # If set to `true`, the service does not attempt to resolve a more precise address for the job.
    boolean disableStreetAddressResolution?;
    # Option for job HTML content sanitization. Applied fields are: * description * applicationInfo.instruction * incentives * qualifications * responsibilities HTML tags in these fields may be stripped if sanitiazation isn't disabled. Defaults to HtmlSanitization.SIMPLE_FORMATTING_ONLY.
    string htmlSanitization?;
};

# Message representing a period of time between two timestamps.
public type TimestampRange record {
    # End of the period (exclusive).
    string endTime?;
    # Begin of the period (inclusive).
    string startTime?;
};

# Geographic region of the search.
public type LocationFilter record {
    # The address name, such as "Mountain View" or "Bay Area".
    string address?;
    # The distance_in_miles is applied when the location being searched for is identified as a city or smaller. This field is ignored if the location being searched for is a state or larger.
    float distanceInMiles?;
    # An object that represents a latitude/longitude pair. This is expressed as a pair of doubles to represent degrees latitude and degrees longitude. Unless specified otherwise, this object must conform to the WGS84 standard. Values must be within normalized ranges.
    LatLng latLng?;
    # CLDR region code of the country/region. This field may be used in two ways: 1) If telecommute preference is not set, this field is used address ambiguity of the user-input address. For example, "Liverpool" may refer to "Liverpool, NY, US" or "Liverpool, UK". This region code biases the address resolution toward a specific country or territory. If this field is not set, address resolution is biased toward the United States by default. 2) If telecommute preference is set to TELECOMMUTE_ALLOWED, the telecommute location filter will be limited to the region specified in this field. If this field is not set, the telecommute job locations will not be See https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/territory_information.html for details. Example: "CH" for Switzerland.
    string regionCode?;
    # Allows the client to return jobs without a set location, specifically, telecommuting jobs (telecommuting is considered by the service as a special location. Job.posting_region indicates if a job permits telecommuting. If this field is set to TelecommutePreference.TELECOMMUTE_ALLOWED, telecommuting jobs are searched, and address and lat_lng are ignored. If not set or set to TelecommutePreference.TELECOMMUTE_EXCLUDED, telecommute job are not searched. This filter can be used by itself to search exclusively for telecommuting jobs, or it can be combined with another location filter to search for a combination of job locations, such as "Mountain View" or "telecommuting" jobs. However, when used in combination with other location filters, telecommuting jobs can be treated as less relevant than other jobs in the search response. This field is only used for job search requests.
    string telecommutePreference?;
};

# The histogram request.
public type HistogramQuery record {
    # An expression specifies a histogram request against matching jobs for searches. See SearchJobsRequest.histogram_queries for details about syntax.
    string histogramQuery?;
};

# Request to create a batch of jobs.
public type BatchCreateJobsRequest record {
    # Required. The jobs to be created. A maximum of 200 jobs can be created in a batch.
    Job[] jobs?;
};

# Request to update a batch of jobs.
public type BatchUpdateJobsRequest record {
    # Required. The jobs to be updated. A maximum of 200 jobs can be updated in a batch.
    Job[] jobs?;
    # Strongly recommended for the best service experience. Be aware that it will also increase latency when checking the status of a batch operation. If update_mask is provided, only the specified fields in Job are updated. Otherwise all the fields are updated. A field mask to restrict the fields that are updated. Only top level fields of Job are supported. If update_mask is provided, The Job inside JobResult will only contains fields that is updated, plus the Id of the Job. Otherwise, Job will include all fields, which can yield a very large response.
    string updateMask?;
};

# The query required to perform a search query.
public type JobQuery record {
    # Parameters needed for commute search.
    CommuteFilter commuteFilter?;
    # This filter specifies the company entities to search against. If a value isn't specified, jobs are searched for against all companies. If multiple values are specified, jobs are searched against the companies specified. The format is "projects/{project_id}/tenants/{tenant_id}/companies/{company_id}". For example, "projects/foo/tenants/bar/companies/baz". At most 20 company filters are allowed.
    string[] companies?;
    # This filter specifies the exact company Company.display_name of the jobs to search against. If a value isn't specified, jobs within the search results are associated with any company. If multiple values are specified, jobs within the search results may be associated with any of the specified companies. At most 20 company display name filters are allowed.
    string[] companyDisplayNames?;
    # Filter on job compensation type and amount.
    CompensationFilter compensationFilter?;
    # This filter specifies a structured syntax to match against the Job.custom_attributes marked as `filterable`. The syntax for this expression is a subset of SQL syntax. Supported operators are: `=`, `!=`, `<`, `<=`, `>`, and `>=` where the left of the operator is a custom field key and the right of the operator is a number or a quoted string. You must escape backslash (\\) and quote (\") characters. Supported functions are `LOWER([field_name])` to perform a case insensitive match and `EMPTY([field_name])` to filter on the existence of a key. Boolean expressions (AND/OR/NOT) are supported up to 3 levels of nesting (for example, "((A AND B AND C) OR NOT D) AND E"), a maximum of 100 comparisons or functions are allowed in the expression. The expression must be < 10000 bytes in length. Sample Query: `(LOWER(driving_license)="class \"a\"" OR EMPTY(driving_license)) AND driving_years > 10`
    string customAttributeFilter?;
    # This flag controls the spell-check feature. If false, the service attempts to correct a misspelled query, for example, "enginee" is corrected to "engineer". Defaults to false: a spell check is performed.
    boolean disableSpellCheck?;
    # The employment type filter specifies the employment type of jobs to search against, such as EmploymentType.FULL_TIME. If a value isn't specified, jobs in the search results includes any employment type. If multiple values are specified, jobs in the search results include any of the specified employment types.
    string[] employmentTypes?;
    # This filter specifies a list of job names to be excluded during search. At most 400 excluded job names are allowed.
    string[] excludedJobs?;
    # The category filter specifies the categories of jobs to search against. See JobCategory for more information. If a value isn't specified, jobs from any category are searched against. If multiple values are specified, jobs from any of the specified categories are searched against.
    string[] jobCategories?;
    # This filter specifies the locale of jobs to search against, for example, "en-US". If a value isn't specified, the search results can contain jobs in any locale. Language codes should be in BCP-47 format, such as "en-US" or "sr-Latn". For more information, see [Tags for Identifying Languages](https://tools.ietf.org/html/bcp47). At most 10 language code filters are allowed.
    string[] languageCodes?;
    # The location filter specifies geo-regions containing the jobs to search against. See LocationFilter for more information. If a location value isn't specified, jobs fitting the other search criteria are retrieved regardless of where they're located. If multiple values are specified, jobs are retrieved from any of the specified locations. If different values are specified for the LocationFilter.distance_in_miles parameter, the maximum provided distance is used for all locations. At most 5 location filters are allowed.
    LocationFilter[] locationFilters?;
    # Message representing a period of time between two timestamps.
    TimestampRange publishTimeRange?;
    # The query string that matches against the job title, description, and location fields. The maximum number of allowed characters is 255.
    string query?;
    # The language code of query. For example, "en-US". This field helps to better interpret the query. If a value isn't specified, the query language code is automatically detected, which may not be accurate. Language code should be in BCP-47 format, such as "en-US" or "sr-Latn". For more information, see [Tags for Identifying Languages](https://tools.ietf.org/html/bcp47).
    string queryLanguageCode?;
};

# A resource that represents a location with full geographic information.
public type Location record {
    # An object that represents a latitude/longitude pair. This is expressed as a pair of doubles to represent degrees latitude and degrees longitude. Unless specified otherwise, this object must conform to the WGS84 standard. Values must be within normalized ranges.
    LatLng latLng?;
    # The type of a location, which corresponds to the address lines field of google.type.PostalAddress. For example, "Downtown, Atlanta, GA, USA" has a type of LocationType.NEIGHBORHOOD, and "Kansas City, KS, USA" has a type of LocationType.LOCALITY.
    string locationType?;
    # Represents a postal address, e.g. for postal delivery or payments addresses. Given a postal address, a postal service can deliver items to a premise, P.O. Box or similar. It is not intended to model geographical locations (roads, towns, mountains). In typical usage an address would be created via user input or from importing existing data, depending on the type of process. Advice on address input / editing: - Use an i18n-ready address widget such as https://github.com/google/libaddressinput) - Users should not be presented with UI elements for input or editing of fields outside countries where that field is used. For more guidance on how to use this schema, please see: https://support.google.com/business/answer/6397478
    PostalAddress postalAddress?;
    # Radius in miles of the job location. This value is derived from the location bounding box in which a circle with the specified radius centered from google.type.LatLng covers the area associated with the job location. For example, currently, "Mountain View, CA, USA" has a radius of 6.17 miles.
    float radiusMiles?;
};
