openapi: 3.0.1
info:
  title: DocuSign Admin API
  description: >-
    This is [DocuSign Admin API](https://developers.docusign.com/docs/admin-api/) OpenAPI specification.
    An API for an organization administrator to manage organizations, accounts and users which enables you to automate user management with your existing systems while ensuring governance and compliance.
  termsOfService: https://www.docusign.com/company/terms-and-conditions/developers
  contact:
    name: DocuSign Developer Center
    url: https://developers.docusign.com
    email: devcenter@docusign.com
  version: v2.1
  x-ballerina-init-description: 
      Create a [DocuSign account](https://www.docusign.com/) and obtain tokens by following [this guide](https://developers.docusign.com/docs/admin-api/admin101/auth/).
  x-ballerina-display:
    label: DocuSign Admin
    iconPath: "icon.png"
servers:
- url: https://api.docusign.net/Management
tags:
- name: Users
  description: Methods to manage users in an account.
- name: eSignUserManagement
  description: Methods to manage eSignature users in an account.
- name: MultiProductUserManagement
  description: Methods to manage multi-product users in an account.
- name: UserExport
  description: Methods for exporting a user list.
- name: AccountSettingsExport
  description: Methods and objects to get account information.
- name: UserImport
  description: |-
    Methods to import users.

    To ensure your CSV is properly formatted, use the
    [Sample Bulk Add CSV file](https://admin.docusign.com/static-resources/organization-user-import.csv)
     as a template.

    You can add up to 2,000 users to an account and include up to 50 accounts per import. The maximum number of users per import is 8,000.
- name: IdentityProviders
  description: Methods to get a list of identity providers.
- name: ReservedDomains
  description: Methods to get a list of reserved domains.
- name: Organization
  description: Methods for working with organizations.
- name: AccountSettingsImport
  description: Methods and objects to update account settings.
- name: SingleAccountUserImport
  description: Methods to import users.
paths:
  /v2/organizations:
    get:
      tags:
      - Organization
      summary: Returns a list of organizations that the authenticated user belongs
        to.
      description: |-
        Returns a list of organizations that the authenticated user belongs to.

        - Required scopes: `organization_read`.

        Note that the DocuSign Admin API only returns JSON, not XML.
      operationId:  Get Organization List
      security:
      - accessCode:
        - organization_read
      x-ds-methodname: getOrganizations
      x-ds-method: getOrganizations
      x-ds-service: Accounts
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/accounts/{accountId}/permissions:
    get:
      tags:
      - eSignUserManagement
      summary: Returns the list of permission profiles in an account.
      description: |+
        Returns the list of permission profiles in an account.

        - Required scopes: `permission_read`

      operationId: Get Accounts Permission Profiles
      security:
      - accessCode:
        - permission_read
      x-ds-methodname: getPermissions
      x-ds-method: getPermissions
      x-ds-service: Accounts
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/accounts/{accountId}/groups:
    get:
      tags:
      - eSignUserManagement
      summary: Returns the list of groups in an account.
      description: |
        Returns the list of groups in an account.

        - Required scopes: `group_read`
      operationId: Get Groups In Account
      security:
      - accessCode:
        - group_read
      x-ds-methodname: getGroups
      x-ds-method: getGroups
      x-ds-service: Accounts
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/exports/user_list:
    get:
      tags:
      - UserExport
      summary: Returns a list of pending and completed export requests.
      description: |
        Returns a list of pending and completed export requests.

        - Required scopes: `user_read`
      operationId: Get Organization Export Requests
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getUserListExports
      x-ds-method: getUserListExports
      x-ds-service: BulkExports
      x-ds-in-sdk: true
    post:
      tags:
      - UserExport
      summary: Creates a user list export request.
      description: "Create a user list export request.\n\n- Required scopes: `user_read`\n\
        \nThis method initiates a user list export request. You specify the type of\
        \ export request as JSON in the body of method, like this:\n\n``` json\n{\n\
        \t\"type\": \"organization_memberships_export\"\n}\n```\n\n\n\n\nThe export\
        \ request type is one of three values:\n\n| Value                        \
        \              | Description                                             \
        \                                                |\n| :-----------------------------------------\
        \ | :------------------------------------------------------------------------------------------------------\
        \ |\n| `organization_memberships_export`          | Every user in every account\
        \ in the organization. Users in multiple accounts will appear more than once.\
        \ |\n| `organization_domain_users_export`         | All users of the reserved\
        \ domains.                                                               \
        \       |\n| `organization_external_memberships_export` | Users whose email\
        \ address domain is *not* linked to the organization.                    \
        \               |\n"
      operationId: Create User List Export Request
      security:
      - accessCode:
        - user_read
      x-ds-methodname: createUserListExport
      x-ds-method: createUserListExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/exports/account_settings:
    get:
      tags:
      - AccountSettingsExport
      summary: Returns a list of pending and completed account settings export request.
      description: |
        Returns a list of pending and completed account settings export request.

        - Required scopes: `account_read`
      operationId: Get Account Setting Export Requests
      security:
      - accessCode:
        - account_read
      x-ds-methodname: getAccountSettingsExports
      x-ds-method: getAccountSettingsExports
      x-ds-service: BulkExports
      x-ds-in-sdk: true
    post:
      tags:
      - AccountSettingsExport
      summary: Creates a  new account settings export request.
      description: "Creates a  new account settings export request.\n\nSpecify the\
        \ accounts whose settings you are requesting as JSON in the body of method,\
        \ like this:\n\n``` json\n{\n  \"accounts\":\t[\n  \t{ \"account_id\": \"\
        9ca037f4-xxxx-xxxx-xxxx-212e57d4f22e\"},\n  \t{ \"account_id\": \"624e3e00-xxxx-xxxx-xxxx-43918c520dab\"\
        }\n\n  ]\n}\n```\n"
      operationId: Create Account Settings Export Request
      security:
      - accessCode:
        - account_read
      x-ds-methodname: createAccountSettingsExport
      x-ds-method: createAccountSettingsExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/exports/user_list/{exportId}:
    get:
      tags:
      - UserExport
      summary: Returns the results for single user list export request.
      description: |-
        Returns the results for single user list export request.

        - Required scopes: `user_read`

        Given an export id, this method returns the results of a single user list export request.
        To get a list of all the export requests, use `getUserListExports`.

        Note that the `metadata_url` property of the response from `createUserListExport` is a read-to-use HTTP GET request to get the status.

        You can find the actual list of users at  `results[n].url` in the response.
      operationId: Get User List Export Request By Export Id
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getUserListExport
      x-ds-method: getUserListExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
    delete:
      tags:
      - UserExport
      summary: Deletes a single user list export request.
      description: |+
        Deletes a single user list export request.
        Use this method to delete pending or completed user export requests.

        - Required scopes: `user_read`

      operationId: Delete User List Expot By Export Id
      security:
      - accessCode:
        - user_read
      x-ds-methodname: deleteUserListExport
      x-ds-method: deleteUserListExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/exports/account_settings/{exportId}:
    get:
      tags:
      - AccountSettingsExport
      summary: Returns the results for a single account settings export request.
      description: |
        Returns the results for a single account settings export request.

        - Required scopes: `account_read`

        Given an export id, this method returns the results of an account settings export request.
        To get a list of all the export requests, use `getAccountSettingsExports`.

        You can find the actual list of settings at  `results[n].url` in the response. The settings export is formatted like this:

        ``` json
        {
          "accounts": [
            {
              "account_id": "9ca037f4-xxxx-xxxx-xxxx-212e57d4f22e",
              "name": "The Happy Company",
              . . .
            },
            {
              "account_id": "624e3e00-xxxx-xxxx-xxxx-43918c520dab",
              "name": "LoanCo",
              . . .
            }
          ],
          "settings": [
            . . .
            {
              "category": "Signing",
              "name": "SignerCanSignOnMobile",
              "account_values": [
                {
                  "account_id": "9ca037f4-xxxx-xxxx-xxxx-212e57d4f22e",
                  "value": "true",
                  "rights": "editable"
                },
                {
                  "account_id": "624e3e00-xxxx-xxxx-xxxx-43918c520dab",
                  "value": "true",
                  "rights": "editable"
                }
              ]
            },
            . . .
          ]
        }

        ```
      operationId: Get Account Settings Export By Export Id
      security:
      - accessCode:
        - account_read
      x-ds-methodname: getAccountSettingsExport
      x-ds-method: getAccountSettingsExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
    delete:
      tags:
      - AccountSettingsExport
      summary: Deletes a single account settings export request.
      description: |+
        Deletes a single account settings export request.
        Any data associated with the request is also deleted.

        - Required scopes: `account_read`

      operationId: Delete Account Settings Export By Export Id
      security:
      - accessCode:
        - account_read
      x-ds-methodname: deleteAccountSettingsExport
      x-ds-method: deleteAccountSettingsExport
      x-ds-service: BulkExports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/account_settings:
    get:
      tags:
      - AccountSettingsImport
      summary: Returns the details and metadata for Bulk Account Settings Import requests
        in the organization.
      description: |-
        Returns the details and metadata for Bulk Account Settings Import requests in the organization.

        - Required scopes: `account_read`
      operationId: Get Organization Import Account Settings Requests
      security:
      - accessCode:
        - account_read
      x-ds-methodname: getBulkAccountSettingsImports
      x-ds-method: getBulkAccountSettingsImports
      x-ds-service: BulkImports
      x-ds-in-sdk: true
    post:
      tags:
      - AccountSettingsImport
      summary: Creates a new account settings import request.
      description: |-
        Creates a new account settings import request.


        - Required scopes: `account_write`
      operationId: Create Import Account Settings Request
      security:
      - accessCode:
        - account_write
      x-ds-methodname: addBulkAccountSettingsImport
      x-ds-method: addBulkAccountSettingsImport
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/account_settings/{importId}:
    get:
      tags:
      - AccountSettingsImport
      summary: Returns the details/metadata for a Bulk Account Settings Import request.
      description: |+
        Returns the details/metadata for a Bulk Account Settings Import request.

        Required - scopes: `account_read`



        Given an import ID, this method returns the results of an account settings import request.
        To get a list of all the import requests, use `getAccountSettingsImports`.

      operationId: Get Bulk Account Settings Import Request By Id
      security:
      - accessCode:
        - account_read
      x-ds-methodname: getBulkAccountSettingsImport
      x-ds-method: getBulkAccountSettingsImport
      x-ds-service: BulkImports
      x-ds-in-sdk: true
    delete:
      tags:
      - AccountSettingsImport
      summary: Deletes a Bulk Account Settings Import request.
      description: |-
        Deletes a single account settings import request.
        Any data associated with the request is also deleted.

        - Required scopes: `account_write`
      operationId: Delete Account Settings Import Request By Id
      security:
      - accessCode:
        - account_write
      x-ds-methodname: deleteBulkAccountSettingsImport
      x-ds-method: deleteBulkAccountSettingsImport
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/add:
    post:
      tags:
      - UserImport
      summary: Creates a request to import new users into an account.
      description: |-
        Creates a request to import *new* users.

        - Required scopes: `user_write`



        Your CSV import file is made up of a header row with the column headers and a row of user or account data for each user you want to add to an account. Only new users can be imported. Any changes to existing users will be ignored. To make changes to existing users, use `updateBulkUserImports`.

        To ensure your CSV is properly formatted, use the
        [Sample Bulk Add CSV file](https://admin.docusign.com/static-resources/organization-user-import.csv)
         as a template. The following table describes the columns.



        | Column              | Required | Description                                                                                                                                                                                                                                                                                                                                                                                                         |
        | :------------------ | :------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
        | AccountID           | yes      | The API account ID for the account to which you want you add the user. You can find this id in the Admin area for the account under **API and Keys**.                                                                                                                                                                                                                                                            |
        | AccountName         |          | The name of the user's account in your organization. The account name must match the account ID provided.                                                                                                                                                                                                                                                                                                           |
        | FirstName           | yes      | The user's first name.                                                                                                                                                                                                                                                                                                                                                                                              |
        | LastName            | yes      | The user's last name.                                                                                                                                                                                                                                                                                                                                                                                               |
        | UserEmail           | yes      | The user's complete email address.                                                                                                                                                                                                                                                                                                                                                                                  |
        | PermissionSet       | yes      | The user's permission set. The PermissionSet value must match an existing permission set for the account. This value is not case sensitive.                                                                                                                                                                                                                                                                         |
        | UserTitle           |          | The user's job title.                                                                                                                                                                                                                                                                                                                                                                                               |
        | CompanyName         |          | The user's company name.                                                                                                                                                                                                                                                                                                                                                                                            |
        | Group               |          | The user's assigned groups. The Group values must match existing Group names for the account. Additional Group columns can be added to the file to add users to more than one group. You do not need to add users to the Everyone group, since all new users are automatically added to that group.                                                                                                                 |
        | AddressLine1        |          | The user's address, first line.                                                                                                                                                                                                                                                                                                                                                                                     |
        | AddressLine2        |          | The user's address, second line.                                                                                                                                                                                                                                                                                                                                                                                    |
        | City                |          | The user's city name.                                                                                                                                                                                                                                                                                                                                                                                               |
        | StateRegionProvince |          | The user's regional location.                                                                                                                                                                                                                                                                                                                                                                                       |
        | PostalCode          |          | The user's postal code.                                                                                                                                                                                                                                                                                                                                                                                             |
        | Phone               |          | The user's phone number.                                                                                                                                                                                                                                                                                                                                                                                            |
        | Language            |          | The user's display language for their DocuSign account. Must be one of: <ul><li>Chinese Simplified: <code>zh_CN</code></li><li>Chinese Traditional: <code>zh_TW</code></li><li>Dutch: <code>nl</code></li><li>English: <code>en</code></li><li>French: <code>fr</code></li><li>German: <code>de</code></li><li>Italian: <code>it</code></li><li>Japanese: <code>ja</code></li><li>Korean: <code>ko</code></li><li>Portuguese: <code>pt</code></li><li>Portuguese Brazil: [...]
        | LoginPolicy         |          | The user's login policy. Valid values include the following: <ul> <li>Column left blank = The user is created with no policy assigned.</li> <li>FedAuthRequired = The user must log in with an Identity Provider.</li> <li>FedAuthBypass = The user may log in with an Identity Provider or their DocuSign username and password.</li> </ul> For more information on login policies, see [Setting User Login Policy](https://support.docusign.com/en/guides/org-admin-gui[...]
        | AutoActivate        |          | For domain users, new users can be activated automatically for domain accounts using SSO by setting the value to **true**. The user is activated automatically once the import is complete. Memberships activated in this way do not receive an activation email.                                                                                                                                                   |


        You can add up to 2,000 users to an account and include up to 50 accounts per import. The maximum number of users per import is 8,000.
      operationId: Create Import Users Request  
      security:
      - accessCode:
        - user_write
      x-ds-methodname: addBulkUserImport
      x-ds-method: addBulkUserImport
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/accounts/{accountId}/imports/bulk_users/add:
    post:
      tags:
      - SingleAccountUserImport
      summary: |
        Import request for adding user to a single account within the organization.
      description: |
        Import request for adding user to a single account within the organization.
        This method lets you upload user information without requiring an AccountId column.

        - Required scopes: `user_write`
      operationId: Create Import Single Account Users Insert Request
      security:
      - accessCode:
        - user_write
      x-ds-methodname: createBulkImportSingleAccountAddUsersRequest
      x-ds-method: createBulkImportSingleAccountAddUsersRequest
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/update:
    post:
      tags:
      - UserImport
      summary: Bulk updates information for existing users.
      description: |-
        Bulk updates information for existing users.

        - Required scopes: `user_write`



        Your CSV import file is made up of a header row with the column headers and a row of user or account data for each user you want to add to an account. Only new users can be imported. Any changes to existing users will be ignored. To make changes to existing users, use `updateBulkUserImports`.

        **Update limit**: You can update up to 2,000 users on an account and include up to 50 accounts per import. The maximum number of updated users per import is 8,000.

        This method requires the following HTTP headers:

        | Header | Value |
        | :--- |  :--- |
        | Content-Type | `text/csv` |
        | Content-Disposition |  `filename=filename.csv` |



        To ensure your CSV is properly formatted, use the
        [Sample Bulk Update CSV file](https://admin.docusign.com/static-resources/organization-user-update-import.csv)
         as a template. The following table describes the columns.

        Note that the columns for bulk adding users and bulk update users are slightly different.
        The update CSV file requires an `APIUserName` column, and does not have an `AutoActivate` column.



        | Column              | Required | Description                                                                                                                                                                                                                                                                                                                                                                                                         |
        | :------------------ | :------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
        | AccountID           | yes      | The 32-character API account ID of the user's account in your organization. You can find this value in the API and Keys section of the Admin area of the account.                                                                                                                                                                                                                                                             |
        | AccountName         |          | The name of the user's account in your organization. The account name must match the account ID provided.                                                                                                                                                                                                                                                                                                           |
        | FirstName           | yes      | The user's first name.                                                                                                                                                                                                                                                                                                                                                                                              |
        | LastName            | yes      | The user's last name.                                                                                                                                                                                                                                                                                                                                                                                               |
        | UserEmail           | yes      | The user's complete email address.                                                                                                                                                                                                                                                                                                                                                                                  |
        | PermissionSet       | yes      | The user's permission set. The PermissionSet value must match an existing permission set for the account. This value is not case sensitive.                                                                                                                                                                                                                                                                         |
        | UserTitle           |          | The user's job title.                                                                                                                                                                                                                                                                                                                                                                                               |
        | CompanyName         |          | The user's company name.                                                                                                                                                                                                                                                                                                                                                                                            |
        | Group               |          | The user's assigned groups. The Group values must match existing Group names for the account. Additional Group columns can be added to the file to add users to more than one group. You do not need to add users to the Everyone group, since all new users are automatically added to that group.                                                                                                                 |
        | AddressLine1        |          | The user's address, first line.                                                                                                                                                                                                                                                                                                                                                                                     |
        | AddressLine2        |          | The user's address, second line.                                                                                                                                                                                                                                                                                                                                                                                    |
        | City                |          | The user's city name.                                                                                                                                                                                                                                                                                                                                                                                               |
        | StateRegionProvince |          | The user's regional location.                                                                                                                                                                                                                                                                                                                                                                                       |
        | PostalCode          |          | The user's postal code.                                                                                                                                                                                                                                                                                                                                                                                             |
        | Phone               |          | The user's phone number.                                                                                                                                                                                                                                                                                                                                                                                            |
        | Language            |          | The user's display language for their DocuSign account. Must be one of: <ul><li>Chinese Simplified: <code>zh_CN</code></li><li>Chinese Traditional: <code>zh_TW</code></li><li>Dutch: <code>nl</code></li><li>English: <code>en</code></li><li>French: <code>fr</code></li><li>German: <code>de</code></li><li>Italian: <code>it</code></li><li>Japanese: <code>ja</code></li><li>Korean: <code>ko</code></li><li>Portuguese: <code>pt</code></li><li>Portuguese Brazil: [...]
        | LoginPolicy         |          | The user's login policy. Valid values include the following: <ul> <li>Column left blank = The user is created with no policy assigned.</li> <li>FedAuthRequired = The user must log in with an Identity Provider.</li> <li>FedAuthBypass = The user may log in with an Identity Provider or their DocuSign username and password.</li> </ul> For more information on login policies, see [Setting User Login Policy](https://support.docusign.com/en/guides/org-admin-gui[...]
        | AutoActivate        |          | For domain users, new users can be activated automatically for domain accounts using SSO by setting the value to **true**. The user is activated automatically once the import is complete. Memberships activated in this way do not receive an activation email.                                                                                                                                                   |



        ## Updating user email addresses

        Changing a user's email address should be done carefully. The user's email address is used to log in to DocuSign and receive documents to sign from others.
        Once changed, existing documents that were sent or received:

        - Will still appear in the user's documents list.
        - Notifications about these documents will be sent to the new email address. If someone sends a new document to the old email address:
        - DocuSign will send a notification to the old address.
        - It will not appear in the documents list of the account.

        This change of email address will be applied to all of the user's account memberships.
      operationId: Update Imported Users
      security:
      - accessCode:
        - user_write
      x-ds-methodname: updateBulkUserImports
      x-ds-method: updateBulkUserImports
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/accounts/{accountId}/imports/bulk_users/update:
    post:
      tags:
      - SingleAccountUserImport
      summary: |-
        Import request for updating users for a single account
        within the organization.
      description: |+
        Import request for updating users for a single account
        within the organization.

        - Required scopes: `user_write`

        This method lets you upload user information without requiring an AccountId column.

      operationId: Update Single Account Users In Organization
      security:
      - accessCode:
        - user_write
      x-ds-methodname: createBulkImportSingleAccountUpdateUsersRequest
      x-ds-method: createBulkImportSingleAccountUpdateUsersRequest
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/close:
    post:
      tags:
      - UserImport
      summary: Creates a request to close the accounts of existing users.
      description: |
        Creates a request to close the accounts of existing users.

        - Required scopes: `user_write`

        Given a CSV list of users, close their accounts.


        Your CSV import file is made up of a header row with the column headers and a row of user or account data for each user whose account you want to close.

        To ensure your CSV is properly formatted, use the
        [Sample Bulk Update CSV file](https://admin.docusign.com/static-resources/organization-user-update-import.csv)
         as a template. The following table describes the columns.




        | Column              | Required | Description                                                                                                                                                                                                                                                                                                                                                                                                         |
        | :------------------ | :------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
        | AccountID           | yes      | The 32-character API account ID of the user's account in your organization. You can find this value in the API and Keys section of the Admin area of the account.                                                                                                                                                                                                                                                             |
        | AccountName         |          | The name of the user's account in your organization. The account name must match the account ID provided.                                                                                                                                                                                                                                                                                                           |
        | FirstName           | yes      | The user's first name.                                                                                                                                                                                                                                                                                                                                                                                              |
        | LastName            | yes      | The user's last name.                                                                                                                                                                                                                                                                                                                                                                                               |
        | UserEmail           | yes      | The user's complete email address.                                                                                                                                                                                                                                                                                                                                                                                  |
        | PermissionSet       | yes      | The user's permission set. The PermissionSet value must match an existing permission set for the account. This value is not case sensitive.                                                                                                                                                                                                                                                                         |
      operationId: Create Import Users Account Close Request
      security:
      - accessCode:
        - user_write
      x-ds-methodname: closeBulkUserImportRequest
      x-ds-method: closeBulkUserImportRequest
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/close_external:
    post:
      tags:
      - UserImport
      summary: Closes external memberships.
      description: |
        Closes external memberships.

        - Required scopes: `user_write`

        External memberships are:

        - Users who have an email address at a verified domain
        - But do not belong to the organization
      operationId: Close Extenal Memberships
      security:
      - accessCode:
        - user_write
      x-ds-methodname: closeBulkExternalUserImportRequest
      x-ds-method: closeBulkExternalUserImportRequest
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users:
    get:
      tags:
      - UserImport
      summary: Gets a list of all of the user import requests.
      description: |
        Gets a list of all of the user import requests.

        - Required scopes: `user_read`
      operationId: Get Import Users Requests
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getBulkUserImportRequests
      x-ds-method: getBulkUserImportRequests
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/{importId}:
    get:
      tags:
      - UserImport
      summary: Returns the details of a single user import request.
      description: |-
        Returns the details of a single user import request.

        - Required scopes: `user_read`

        Use this method to check the status of the request by looking at the `status` property of the response.
        Once the status becomes `completed` (or fails), use this method to get the details.

        To get a list of all of the user import requests, use `getBulkUserImportRequests`.
      operationId: Get Import User Request By Id
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getBulkUserImportRequest
      x-ds-method: getBulkUserImportRequest
      x-ds-service: BulkImports
      x-ds-in-sdk: true
    delete:
      tags:
      - UserImport
      summary: Deletes a specific user import request.
      description: |-
        Deletes a specific import request and its results.

        - Required scopes: `user_write`


        To delete a user, see `closeBulkUserImportRequest`.
      operationId: Delete Import User Request By Id
      security:
      - accessCode:
        - user_write
      x-ds-methodname: deleteBulkUserImport
      x-ds-method: deleteBulkUserImport
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/imports/bulk_users/{importId}/results_csv:
    get:
      tags:
      - UserImport
      summary: |-
        Given the ID of a user import request,
        return the CSV file that was imported.
      description: |
        Returns the contents of the CSV file
        associated with a user import request.

        - Required scopes: `user_read`

        The results have an additional column,
        `ProcessingResults`,
        that describes the results of importing that row.
      operationId: Get CSV Results of User Import Request
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getBulkUserImportCSV
      x-ds-method: getBulkUserImportCSV
      x-ds-service: BulkImports
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/identity_providers:
    get:
      tags:
      - IdentityProviders
      summary: Returns the list of identity providers for an organization.
      description: |
        Returns the list of identity providers for an organization.

        - Required scopes: `identity_provider_read`
      operationId: Get Identity Providers of Organization
      security:
      - accessCode:
        - identity_provider_read
      x-ds-methodname: getIdentityProviders
      x-ds-method: getIdentityProviders
      x-ds-service: IdentityProviders
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/reserved_domains:
    get:
      tags:
      - ReservedDomains
      summary: Returns the list of reserved domains for the organization.
      description: |-
        Returns the list of reserved domains for the organization.

        - Required scopes: `domain_read`.

        Please note the DocuSign Admin API only returns JSON, not XML.
      operationId: Get Reserved Domains of Organization
      security:
      - accessCode:
        - domain_read
      x-ds-methodname: getReservedDomains
      x-ds-method: getReservedDomains
      x-ds-service: ReservedDomains
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/profiles:
    post:
      tags:
      - eSignUserManagement
      summary: Updates a user's information.
      description: |+
        Updates a user's information.

        - Required scopes: `user_write`

      operationId: Update User
      security:
      - accessCode:
        - user_write
      x-ds-methodname: updateUser
      x-ds-method: updateUser
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/email_addresses:
    post:
      tags:
      - Users
      summary: Updates a user's email address.
      description: |+
        Updates a user's email address.

        - Required scopes: `user_write`

      operationId: Upate User Email Address
      security:
      - accessCode:
        - user_write
      x-ds-methodname: updateEmailAddress
      x-ds-method: updateEmailAddress
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/{userId}/accounts:
    delete:
      tags:
      - eSignUserManagement
      summary: Closes a user's memberships.
      description: |+
        Closes a user's memberships.

        - Required scopes: `user_write`

      operationId: Close User Memberships
      # requestBody:
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/DeleteMembershipsRequest'
        # required: true
      security:
      - accessCode:
        - user_write
      x-ds-methodname: closeMemberships
      x-ds-method: closeMemberships
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users:
    get:
      tags:
      - Users
      summary: Returns information about the users in an organization.
      description: |-
        Returns information about the users in an organization.


        - Required scopes: `user_read`

        You must include at least one of the following query parameters in the request:

        - `account_id`: The id of an account associated with the organization.
        - `organization_reserved_domain_id`: The id of one of the organization's reserved domains.
        - `email`: An email address associated with the users that you want to return.
      operationId: Get Users in Organization
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getUsers
      x-ds-method: getUsers
      x-ds-service: Users
      x-ds-in-sdk: true
    post:
      tags:
      - eSignUserManagement
      summary: Creates a new user.
      description: |+
        Creates a new user.

        - Required scopes: `user_write`

      operationId: Create User
      security:
      - accessCode:
        - user_write
      x-ds-methodname: createUser
      x-ds-method: createUser
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/{userId}/memberships/{membershipId}:
    post:
      tags:
      - eSignUserManagement
      summary: Activates user memberships.
      description: |
        Activates user memberships.

        - Required scopes: `user_write`
      operationId: Activate User Membership
      security:
      - accessCode:
        - user_write
      x-ds-methodname: activateMembership
      x-ds-method: activateMembership
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/profile:
    get:
      tags:
      - eSignUserManagement
      summary: |
        Returns information about recently modified users.
      description: |+
        Returns information about recently modified users.

        - Required scopes: `user_read`

        The response includes up to the first 20 users modified
        in the last 10 days.
      operationId: Get Recently Modified Users
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getUserProfiles
      x-ds-method: getUserProfiles
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/users/{userId}/identities:
    delete:
      tags:
      - eSignUserManagement
      summary: Deletes user identities.
      description: |+
        Deletes user identities.

        - Required scopes: `user_write`

      operationId: Delete User Identities
      # requestBody:
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/DeleteUserIdentityRequest'
      #   required: true
      security:
      - accessCode:
        - user_write
      x-ds-methodname: deleteIdentities
      x-ds-method: deleteIdentities
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2/organizations/{organizationId}/accounts/{accountId}/users:
    post:
      tags:
      - eSignUserManagement
      summary: Adds users to an account.
      description: |+
        Adds users to an account.

        - Required scopes: `user_write`

      operationId: Create Account Users
      security:
      - accessCode:
        - user_write
      x-ds-methodname: addUsers
      x-ds-method: addUsers
      x-ds-service: Users
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups:
    get:
      tags:
      - MultiProductUserManagement
      summary: Returns a list of DSGroups.
      description: |-
        Returns a list of DSGroups

        - Required scopes: `user_read`
      operationId: Get DS Groups
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getDSGroups
      x-ds-method: getDSGroups
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    post:
      tags:
      - MultiProductUserManagement
      summary: Creates a new DSGroup.
      description: |-
        Creates a new DSGroup.

        - Required scopes: `user_write`
      operationId: Create DS Group
      security:
      - accessCode:
        - user_write
      x-ds-methodname: addDSGroup
      x-ds-method: addDSGroup
      x-ds-service: DSGroups
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups/{dsGroupId}:
    get:
      tags:
      - MultiProductUserManagement
      summary: Returns details about a single DSGroup.
      description: |-
        Returns details about a single DSGroup.

        - Required scopes: `user_read`
      operationId: Get DS Group
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getDSGroup
      x-ds-method: getDSGroup
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    delete:
      tags:
      - MultiProductUserManagement
      summary: Deletes a DSGroup.
      description: |-
        Deletes a DSGroup

        - Required scopes: `user_write`
      operationId: Delete DS Group
      security:
      - accessCode:
        - user_write
      x-ds-methodname: deleteDSGroup
      x-ds-method: deleteDSGroup
      x-ds-service: DSGroups
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/dsgroups/{dsGroupId}/users:
    get:
      tags:
      - MultiProductUserManagement
      summary: Gets a list of users in a DSGroup.
      description: |-
        Gets a list of users in a DSGroup.

        - Required scopes: `user_read`
      operationId: Get DS Group Users
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getDSGroupUsers
      x-ds-method: getDSGroupUsers
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    post:
      tags:
      - MultiProductUserManagement
      summary: Adds a list of users to a DSGroup.
      description: |-
        Adds a list of users to a DSGroup.

        - Required scopes: `user_write`
      operationId: Add DS Group Users
      security:
      - accessCode:
        - user_write
      x-ds-methodname: addDSGroupUsers
      x-ds-method: addDSGroupUsers
      x-ds-service: DSGroups
      x-ds-in-sdk: true
    delete:
      tags:
      - MultiProductUserManagement
      summary: Removes a list of users from a DSGroup.
      description: |-
        Removes a list of users from a DSGroup.

        - Required scopes: `user_write`
      operationId: Remove DS Group Users
      # requestBody:
      #   content:
      #     application/json:
      #       schema:
      #         $ref: '#/components/schemas/DSGroupUsersRemoveRequest'
      #   required: true
      security:
      - accessCode:
        - user_write
      x-ds-methodname: removeDSGroupUsers
      x-ds-method: removeDSGroupUsers
      x-ds-service: DSGroups
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/products/permission_profiles:
    get:
      tags:
      - MultiProductUserManagement
      summary: Gets products associated with the account and the available permission
        profiles.
      description: |-
        Gets products associated with the account and the available permission profiles.

        - Required scopes: `user_read`
      operationId: Get Product Permission Profiles
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getProductPermissionProfiles
      x-ds-method: getProductPermissionProfiles
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/products/users/{userId}/permission_profiles:
    get:
      tags:
      - MultiProductUserManagement
      summary: Retrieves a list of user's permission profiles for each account's product.
      description: |-
        Retrieves a list of user's permission profiles for each account's product.

        - Required scopes: `user_read`
      operationId: Get User Product Permission Profiles of Product
      security:
      - accessCode:
        - user_read
      x-ds-methodname: getUserProductPermissionProfiles
      x-ds-method: getUserProductPermissionProfiles
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
    post:
      tags:
      - MultiProductUserManagement
      summary: Assigns user to permission profiles for one or more products.
      description: |-
        Assigns user to permission profiles for one or more products.

        - Required scopes: `user_write`
      operationId: Assign User to Product Permission Profiles
      security:
      - accessCode:
        - user_write
      x-ds-methodname: addUserProductPermissionProfiles
      x-ds-method: addUserProductPermissionProfiles
      x-ds-service: ProductPermissionProfiles
      x-ds-in-sdk: true
  /v2.1/organizations/{organizationId}/accounts/{accountId}/users:
    post:
      tags:
      - MultiProductUserManagement
      summary: Creates and updates a multi-product user.
      description: |-
        Creates and updates a multi-product user.

        - Required scopes: `user_write`
      operationId: Create or Update Multi Product Users
      security:
      - accessCode:
        - user_write
      x-ds-methodname: addOrUpdateUser
      x-ds-method: addOrUpdateUser
      x-ds-service: Users
      x-ds-in-sdk: true
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    oAuth2Auth:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow. [More info](https://developers.docusign.com/platform/auth/)
      flows:
        implicit:
          authorizationUrl: https://account-d.docusign.com/oauth/auth
          scopes:
            organization_read: "Gets lists of organizations and organization data."
            permission_read: "Gets lists of permission profiles associated with an account."
            group_read: "Gets lists of groups associated with an account."
            user_read: "Reads user data."
            account_read: "Gets account data."
            account_write: ""
            user_write: "Updates, creates, or deletes users."
            identity_provider_read: "Gets data on already-defined identity providers for an organization."
            domain_read: "Gets data on reserved domains for the organization."
        authorizationCode:
          authorizationUrl: https://account-d.docusign.com/oauth/auth
          tokenUrl: https://account-d.docusign.com/oauth/token
          scopes:
            organization_read: "Gets lists of organizations and organization data."
            permission_read: "Gets lists of permission profiles associated with an account."
            group_read: "Gets lists of groups associated with an account."
            user_read: "Reads user data."
            account_read: "Gets account data."
            account_write: ""
            user_write: "Updates, creates, or deletes users."
            identity_provider_read: "Gets data on already-defined identity providers for an organization."
            domain_read: "Gets data on reserved domains for the organization."
x-ds-categories:
- name: UserManagement
  summary: Methods to manage users in an account.
  description: Methods to manage users in an account.
- name: BulkOperations
  summary: Methods to import and export users and accounts.
  description: Methods to import and export users and accounts.
- name: IdentityProviders
  summary: Methods to get a list of identity providers.
  description: Methods to get a list of identity providers.
- name: ReservedDomains
  summary: Methods to get a list of reserved domains.
  description: Methods to get a list of reserved domains.
- name: Organization
  summary: Methods for working with organizations.
  description: Methods for working with organizations.
