{
    "openapi": "3.0.1",
    "info": {
        "title": "CRM Associations",
        "description": "Associations define the relationships between objects in HubSpot. These endpoints allow you to create, read, and remove associations.",
        "version": "v3",
        "x-hubspot-product-tier-requirements": {
            "marketing": "FREE",
            "sales": "FREE",
            "service": "FREE",
            "cms": "FREE"
        },
        "x-hubspot-documentation-banner": "NONE",
        "x-hubspot-api-use-case": "When an existing contact has moved to a new company, update their associated company to keep your CRM up to date.",
        "x-hubspot-related-documentation": [
            {
                "name": "Associations guide",
                "url": "https://developers.hubspot.com/docs/guides/api/crm/associations/associations-v3"
            }
        ],
        "x-hubspot-introduction": "Use the associations API to create, retrieve, update, or delete associations between records, or between records and activities. "
    },
    "servers": [
        {
            "url": "https://api.hubapi.com"
        }
    ],
    "tags": [
        {
            "name": "Batch"
        }
    ],
    "paths": {
        "/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/create": {
            "post": {
                "tags": ["Batch"],
                "summary": "Create a batch of associations",
                "description": "Associate all pairs of objects identified in the request body.",
                "operationId": "post-/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/create_create",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/read": {
            "post": {
                "tags": ["Batch"],
                "summary": "Read a batch of associations",
                "description": "Get the IDs of all `{toObjectType}` objects associated with those specified in the request body.",
                "operationId": "post-/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/read_read",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        },
        "/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/archive": {
            "post": {
                "tags": ["Batch"],
                "summary": "Archive a batch of associations",
                "description": "Remove the associations between all pairs of objects identified in the request body.",
                "operationId": "post-/crm/v3/associations/{fromObjectType}/{toObjectType}/batch/archive_archive",
                "security": [
                    {
                        "private_apps": ["crm.objects.listings.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.write"]
                    },
                    {
                        "oauth2_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.read"]
                    },
                    {
                        "private_apps": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.read"]
                    },
                    {
                        "private_apps_legacy": ["contacts"]
                    },
                    {
                        "oauth2": ["crm.objects.subscriptions.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.read"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "private_apps": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["media_bridge.read"]
                    },
                    {
                        "private_apps": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2": ["crm.objects.companies.write"]
                    },
                    {
                        "oauth2_legacy": ["tickets"]
                    },
                    {
                        "private_apps": ["crm.objects.users.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.users.read"]
                    },
                    {
                        "oauth2": ["crm.objects.users.write"]
                    },
                    {
                        "private_apps_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.write"]
                    },
                    {
                        "oauth2_legacy": ["e-commerce"]
                    },
                    {
                        "private_apps_legacy": ["tickets"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.goals.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.write"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.orders.write"]
                    },
                    {
                        "private_apps": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.services.write"]
                    },
                    {
                        "oauth2": ["crm.objects.orders.write"]
                    },
                    {
                        "oauth2": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.commercepayments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.deals.write"]
                    },
                    {
                        "oauth2": ["crm.objects.deals.write"]
                    },
                    {
                        "private_apps": ["crm.objects.appointments.read"]
                    },
                    {
                        "oauth2": ["crm.objects.invoices.read"]
                    },
                    {
                        "oauth2": ["crm.objects.appointments.read"]
                    },
                    {
                        "private_apps": ["crm.objects.invoices.read"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.write"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.write"]
                    },
                    {
                        "oauth2": ["crm.objects.leads.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.write"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "oauth2": ["crm.objects.contacts.write"]
                    },
                    {
                        "private_apps": ["crm.objects.contacts.write"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.write"]
                    },
                    {
                        "private_apps": ["crm.objects.leads.read"]
                    },
                    {
                        "oauth2_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "private_apps_legacy": ["crm.objects.custom.read"]
                    },
                    {
                        "oauth2": ["crm.objects.line_items.write"]
                    },
                    {
                        "private_apps": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.line_items.write"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.read"]
                    },
                    {
                        "private_apps": ["crm.objects.courses.read"]
                    },
                    {
                        "oauth2": ["crm.objects.listings.read"]
                    },
                    {
                        "private_apps": ["crm.objects.carts.read"]
                    },
                    {
                        "oauth2": ["crm.objects.courses.write"]
                    },
                    {
                        "oauth2": ["crm.objects.quotes.read"]
                    },
                    {
                        "oauth2": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "oauth2": ["crm.objects.services.read"]
                    },
                    {
                        "oauth2": ["crm.objects.carts.read"]
                    },
                    {
                        "private_apps": ["crm.objects.partner-clients.read"]
                    },
                    {
                        "private_apps": ["crm.objects.quotes.read"]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "oauth2_legacy": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.custom.read": "View custom object records",
                            "tickets": "Read and write tickets",
                            "crm.objects.goals.read": "Read goals",
                            "media_bridge.read": "Read media and media events",
                            "crm.objects.custom.write": "Change custom object records",
                            "e-commerce": "e-commerce"
                        }
                    }
                }
            },
            "oauth2": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://app.hubspot.com/oauth/authorize",
                        "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
                        "scopes": {
                            "crm.objects.courses.write": "Write courses",
                            "crm.objects.carts.write": "Write cart",
                            "crm.objects.listings.read": "Read listings",
                            "crm.objects.contacts.read": " ",
                            "crm.objects.orders.read": "Read Orders",
                            "crm.objects.services.read": "Read services",
                            "crm.objects.quotes.read": "Quotes",
                            "crm.objects.orders.write": "Write orders",
                            "crm.objects.carts.read": "Read carts",
                            "crm.objects.subscriptions.read": "Read Commerce Subscriptions",
                            "crm.objects.leads.write": "Modify lead objects",
                            "crm.objects.commercepayments.read": "Read the COMMERCE_PAYMENT object.",
                            "crm.objects.users.write": "Write User CRM objects",
                            "crm.objects.contacts.write": " ",
                            "crm.objects.companies.write": " ",
                            "crm.objects.listings.write": "Write listings",
                            "crm.objects.line_items.write": "Line Items",
                            "crm.objects.deals.write": " ",
                            "crm.objects.partner-clients.read": "View Partner Client CRM objects",
                            "crm.objects.invoices.read": "Read invoices objects",
                            "crm.objects.deals.read": " ",
                            "crm.objects.courses.read": "Read courses",
                            "crm.objects.line_items.read": "Line Items",
                            "crm.objects.services.write": "Write services",
                            "crm.objects.appointments.write": "Write appointments",
                            "crm.objects.leads.read": "Read lead objects",
                            "crm.objects.partner-clients.write": "Modify Partner Client CRM objects",
                            "crm.objects.appointments.read": "Read appointments",
                            "crm.objects.companies.read": " ",
                            "crm.objects.users.read": "Read User CRM objects",
                            "crm.objects.quotes.write": "Quotes"
                        }
                    }
                }
            },
            "private_apps_legacy": {
                "type": "apiKey",
                "name": "private-app-legacy",
                "in": "header"
            },
            "private_apps": {
                "type": "apiKey",
                "name": "private-app",
                "in": "header"
            }
        }
    },
    "x-hubspot-available-client-libraries": ["PHP", "Node", "Ruby", "Python"],
    "x-hubspot-product-tier-requirements": {
        "marketing": "FREE",
        "sales": "FREE",
        "service": "FREE",
        "cms": "FREE"
    },
    "x-hubspot-documentation-banner": "NONE"
}
